airgun/entities/architecture.py, airgun/entities/os.py, airgun/views/architecture.py, airgun/views/common.py, airgun/views/os.py, airgun/widgets.py
=> Refactor Search widget and introduce SearchableViewMixin

airgun/views/architecture.py, airgun/views/os.py, airgun/widgets.py
=> Refactor two pane multiselect widget, keep read/fill interface

airgun/entities/os.py, airgun/views/common.py, airgun/widgets.py, setup.py
```
py.test /home/ashtayer/Desktop/robottelo/tests/foreman/ui_airgun/test_os.py
==================================================================================== test session starts =====================================================================================
platform linux2 -- Python 2.7.14, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/ashtayer/Desktop/robottelo, inifile:
plugins: wait-for-1.0.9, services-1.2.1, mock-1.6.3
collected 5 items                                                                                                                                                                            
2018-02-27 16:08:35 - conftest - DEBUG - BZ deselect is disabled in settings …
```
=> Add support for 6.4 navigation

airgun/browser.py, airgun/session.py, airgun/widgets.py
=> Lazy entities init & correct exception handling in Session.__enter__

airgun/views/os.py
Closes https://github.com/SatelliteQE/airgun/issues/35
=> added tab func

.travis.yml, Makefile, airgun/browser.py, airgun/navigation.py, airgun/session.py, airgun/widgets.py, docs/Makefile, docs/conf.py, docs/index.rst, docs/spelling_wordlist.txt, requirements-optional.txt
What about enabling spellcheck on documentation as well?
=> Add documentation spellcheck into CI process

airgun/entities/architecture.py, airgun/views/architecture.py
For PR: https://github.com/abalakh/robottelo/pull/24
=> Architecture delete

airgun/entities/activationkey.py, airgun/views/activationkey.py, airgun/widgets.py
Part of https://github.com/SatelliteQE/airgun/issues/27
=> Add edit entry widget

airgun/entities/activationkey.py, airgun/views/activationkey.py, airgun/views/common.py, airgun/views/os.py, airgun/widgets.py, setup.py
=> Implemented AddRemoveResourcesTab view

airgun/entities/lifecycleenvironment.py, airgun/session.py, airgun/views/lifecycleenvironment.py
=> Add LCE entity

airgun/entities/activationkey.py, airgun/views/activationkey.py, airgun/widgets.py
See SatelliteQE/robottelo#5933 for test results
=> Added AK Content Hosts tab and remove_host_collection helper

airgun/views/activationkey.py
See SatelliteQE/robottelo#5935 for test results
=> Added AK Repository Sets tab

airgun/entities/product.py, airgun/session.py, airgun/views/product.py
Going to add basic things in that PR and add more views in the next ones
=> Add Products entity(part_1)

airgun/entities/partitiontable.py, airgun/session.py, airgun/views/partitiontable.py
Please give me a feedback, @abalakh  @oshtaier  
And here are questions, some things I didn't quite understand:
1.ACEEditor using fill method with pure string for create, works fine, but then when I clone I use read|fill method again to change or clone for ACEEditor and it doesn't work, the template is empty.  Do I fill ACEEditor properly , what I should change?
2.audit commit cannot be asserted with read because it's equal to "" why ?
3.How to test lock and unlock ?
4.How I can check if the help is not empty?
5.Is in organizations always Default Organization ?
6.Is necessary to write negative tests ?
7.And of course I didn't know how to solve this conditional widget so I improvise
I have to still work on 
`tier2 tests`
=> partition table entity implementation

airgun/browser.py, airgun/settings.py, airgun/views/common.py, setup.py
Per @omaciel request here: https://github.com/SatelliteQE/airgun/pull/79#discussion_r188379682
=> Drop six & py2 backwards compatibility

airgun/entities/location.py, airgun/views/location.py
Adding some additional functionality to location, please review @oshtaier or @abalakh.
=> adding create to location

airgun/entities/computeresource.py, airgun/session.py, airgun/views/computeresource.py, airgun/widgets.py
Test example
```
from nailgun import entities
from robottelo.datafactory import gen_string, valid_data_list
from robottelo.decorators import parametrize
@parametrize('name', valid_data_list())
def test_positive_create_docker(session, name):
"""Create new CR, provider is Docker"""
with session:
session.computeresource.create({
'name': name,
'provider':'Docker',
'url':'https://docker.example.com:4243'
})
assert session.computeresource.search(name) == name
@parametrize('name', valid_data_list())
def test_positive_create_libvirt(session, name):
"""Create new CR, provider is Libvirt"""
with session:
session.computeresource.create({
'name': name,
'provider':'Libvirt',
'url':'qemu://host.example.com/system',
'display_type':'VNC',
})
assert session.computeresource.search(name) == name
```
=> First attend to implement compute resource view and entity

airgun/entities/location.py, airgun/views/location.py, airgun/views/organization.py
It's not done yet. You can find some TODO's there.
But please give me a feedback @oshtaier or @abalakh  on what is already written.
=> adding more functionality to location

airgun/entities/domain.py, airgun/views/common.py, airgun/widgets.py
=> Implemented ValidationErrors widget

airgun/entities/ldap_authentication.py, airgun/session.py, airgun/views/ldapauthentication.py
=> Add LDAP Auth support

airgun/entities/puppet_environment.py, airgun/views/puppet_environment.py
```
def test_positive_import(session):
name = 'common'
with session:
session.puppetenvironment.import_environments(value=name)
assert session.puppetenvironment.search(
name)[0]['Name'] == name
```
=> Adding code for button import environments

airgun/entities/errata.py, airgun/session.py, airgun/views/common.py, airgun/views/errata.py, airgun/views/product.py, airgun/widgets.py
=> Implemented Errata entity

airgun/entities/puppet_class.py, airgun/views/puppet_class.py
Tested out with
```
@fixture(scope='module')
def module_org():
return entities.Organization().create()
@fixture(scope='function')
def puppet_class_with_scp(module_org):
puppet_modules = [
{'author': 'robottelo', 'name': 'ui_test_classparameters'}]
cv = publish_puppet_module(
puppet_modules, CUSTOM_PUPPET_REPO, module_org)
env = entities.Environment().search(
query={'search': u'content_view="{0}"'.format(cv.name)}
)[0]
puppet_class = entities.PuppetClass().search(query={
'search': u'name = "{0}" and environment = "{1}"'.format(
puppet_modules[0]['name'], env.name)
})[0]
sc_params_list = entities.SmartClassParameters().search(
query={
'search': 'puppetclass="{0}"'.format(puppet_class.name),
'per_page': 1000
})
yield {
'puppet_class': puppet_class.name,
'sc_parameter': sc_params_list.pop()
} …
```
=> Add Smart Class Parameters functionality to puppet classes

airgun/entities/package.py, airgun/exceptions.py, airgun/session.py, airgun/views/package.py, airgun/widgets.py
close https://github.com/SatelliteQE/airgun/issues/137
=> Implement Package entity

airgun/views/computeresource.py
Close https://github.com/SatelliteQE/robottelo/issues/6178
tests output at https://github.com/SatelliteQE/robottelo/pull/6179
=> Fix compute_resource RHVProviderForm

airgun/entities/lifecycleenvironment.py, airgun/views/lifecycleenvironment.py
=> Added LCE packages and puppet modules views/helpers

airgun/entities/rhai/inventory.py, airgun/session.py, airgun/views/rhai.py
Added RHAI Invintory entity and the respectful views.
=> Added RHAI Inventory

airgun/entities/rhai/overview.py, airgun/session.py, airgun/views/rhai.py
Added RHAI Overview entity and the respectful views.
=> Added RHAI Overview

airgun/entities/oscapcontent.py, airgun/session.py, airgun/views/oscapcontent.py
@oshtaier or @abalakh please review. 
TODO: replace indexes to Actions
Question: If I want also implement download option, which widget I will use and how the test and assert will look like ?
=> OpenSCAP content entity and view

airgun/entities/oscaptailoringfile.py, airgun/session.py, airgun/views/oscaptailoringfile.py
Adding SCAP Tailoring File entity with view. Please review @abalakh or @oshtaier .
I didn't push test yet, because some of them are connected with oscap policy entity.
QUESTION: what about stubbed tier2,tier3,tier4 test ? Do I port them ? Do I delete them from ui?
=> SCAP Tailoring File entity

airgun/entities/job_invocation.py, airgun/session.py, airgun/views/job_invocation.py, airgun/widgets.py
Additionally, run next code for sanity reason:
```
def test_test(session):
with session:
session.jobinvocation.run({
'job_category': 'Commands',
'job_template': 'Run Command - SSH Default',
'template_content.command': 'ls',
'advanced_options.effective_user': 'test',
'advanced_options.use_default': False,
'advanced_options.description_content.description_template': 'test',
'advanced_options.timeout': '323',
'advanced_options.password': 'test',
'advanced_options.passphrase': 'test',
'advanced_options.sudo_password': 'test',
'advanced_options.concurrency_level': '12',
'advanced_options.time_span': '34',
'advanced_options.query_type': 'Dynamic Query',
'schedule': 'Set up recurring execution',
'schedule_content.repeats': 'monthly',
'schedule_content.repeats_content.at_days': '6', …
```
=> Implement job invocation functionality

airgun/entities/rhai/action.py, airgun/session.py, airgun/views/rhai.py
Added RHAI Actions entity and the respectful views.
=> Added RHAI Actions

airgun/entities/rhai/inventory.py
- fixed session property;
- improved search method of `InventoryHostEntity`
=> RHAI Inventory fix

airgun/entities/rhai/manage.py, airgun/session.py, airgun/views/rhai.py
Added RHAI Mange entity and the respectful views.
=> Added RHAI Manage

airgun/browser.py, airgun/entities/host.py, airgun/settings.py, airgun/views/host.py, settings.ini.example
Currently for chrome only as it's the only supported browser.
=> Added support of downloading & transferring files from browser

airgun/entities/contenthost.py, airgun/session.py, airgun/views/common.py, airgun/views/contenthost.py
=> Implemented content host entity

airgun/entities/oscappolicy.py, airgun/session.py, airgun/views/oscappolicy.py
Hello please review @abalakh or @oshtaier 
Here are the [test](https://github.com/SatelliteQE/robottelo/pull/6248) please look too,
#144
=> Oscap policy entity

airgun/browser.py, airgun/entities/contenthost.py, airgun/entities/dashboard.py, airgun/entities/host.py, airgun/entities/task.py, airgun/session.py, airgun/views/dashboard.py, airgun/views/task.py, airgun/widgets.py, setup.py
!!! Remove backward compatibility for previous widgetastic versions
=> Adding dashboard and task entities

airgun/entities/hostcollection.py, airgun/views/hostcollection.py, airgun/views/job_invocation.py
close https://github.com/SatelliteQE/airgun/issues/136
see tests at robottelo PR  https://github.com/SatelliteQE/robottelo/pull/6218
=> Implement Host Collection Content Management Actions

airgun/entities/contentview.py, airgun/views/common.py, airgun/views/contentview.py
=> Added some CV helpers and views

airgun/views/product.py
test run at PR https://github.com/SatelliteQE/robottelo/pull/6270
=> Fix products view create from discovered repo

airgun/views/oscappolicy.py
Please @abalakh or @oshtaier take a look.
=> changes to oscap policy, to cover chart and status

airgun/entities/discoveredhosts.py, airgun/session.py, airgun/views/discoveredhosts.py
related issue https://github.com/SatelliteQE/airgun/issues/150
test run output https://github.com/SatelliteQE/robottelo/pull/6252
=> Implement Discovered Hosts Entity

airgun/entities/containerimagetag.py, airgun/session.py, airgun/views/containerimagetag.py
@oshtaier please review.
#132 
[tests](https://github.com/SatelliteQE/robottelo/pull/6318)
=> implementation of Container Image Tag Entity

Makefile, airgun/entities/sync_status.py, airgun/session.py, airgun/views/sync_status.py
close issue https://github.com/SatelliteQE/airgun/issues/131
test run at robottelo PR https://github.com/SatelliteQE/robottelo/pull/6283
=> Implement Sync Status entity

airgun/entities/rhai/plan.py, airgun/session.py, airgun/views/rhai.py
In this PR I implemented create, update and delete methods for RHAI Plan entity.
=> Added RHAI Plan

airgun/entities/discoveryrule.py
close https://github.com/SatelliteQE/airgun/issues/118
test output: https://github.com/SatelliteQE/robottelo/pull/6319
=> Implement discovery rule associated and discovered hosts actions

airgun/entities/contentview.py, airgun/entities/contentviewfilter.py, airgun/session.py, airgun/views/common.py, airgun/views/contentview.py, airgun/views/contentviewfilter.py, airgun/widgets.py
=> Implemented helpers and views for content view filter entity

airgun/entities/ldap_authentication.py, airgun/views/host.py, setup.py
Depends on https://github.com/RedHatQE/widgetastic.core/pull/115
Closes #138
=> Add puppet class parameters table to host entity

airgun/entities/base.py, airgun/entities/bookmark.py, airgun/session.py, airgun/views/bookmark.py, airgun/views/common.py, airgun/widgets.py
=> Implemented Bookmarks entity

airgun/entities/product.py
Closes #195
Remove completely unneeded method
Checked robottelo code to make sure that method is never used
=> Remove redundant method

airgun/entities/subscription.py
Test results in SatelliteQE/robottelo#6424
=> Fix subscription waiter helper

airgun/views/computeresource.py
related tests output https://github.com/SatelliteQE/robottelo/pull/6432
=> Fix Compute Resource EC2 Region field

airgun/entities/discoveredhosts.py
https://github.com/SatelliteQE/robottelo/pull/6252#issuecomment-432316662
=> Discovered hosts may need more time to provision in custom mode

airgun/browser.py, airgun/entities/discoveredhosts.py, airgun/widgets.py
This will fix all the nav problems, search box not detected on some entities, the page spinner id has changed that leaded to many nav problems firstly and some other problem for example after search, the ensure_page_safe was not working properly, after this fix all was working as expected.
test output https://github.com/SatelliteQE/robottelo/pull/6252#issuecomment-437946142
=> Fix for 6.5 and discovered host entity read 

airgun/entities/redhat_repository.py, airgun/entities/repository.py, airgun/session.py, airgun/views/redhat_repository.py, airgun/views/repository.py
Implement RH repository entity and fix repository entity.
test coverage at https://github.com/SatelliteQE/robottelo/pull/6448
=> Implement RH repository entity + some fixes for 6.5

airgun/widgets.py
=> filter input field class != "ms-input" but contains it

airgun/entities/computeresource.py, airgun/views/computeresource.py
Add vm_import to computeresource and hostgroup entity only with functionality required for compute resource testing (deploy_on can't be set using API).
=> vm_import + hostgroup

airgun/entities/location.py, airgun/entities/organization.py, airgun/entities/subscription.py, airgun/views/host.py, airgun/views/hostgroup.py, airgun/views/ldapauthentication.py, airgun/views/location.py, airgun/views/organization.py, airgun/views/puppet_class.py, airgun/views/role.py, airgun/views/user.py, airgun/views/usergroup.py, airgun/widgets.py
* Fixed breadcrumb checks for Edit pages (fixes #246)
* Added manifest refresh, improvements for organization delete and subscription waiters
=> Fixed breadcrumb checks for Edit pages and few other improvements

airgun/views/syncplan.py
This is related to Satellite 6.5 Feature to support custom_cron. 
- Added this Create View Page 
- Same also added in Edit View Page with Recurring Logic 
Corresponding tests will be added in robottelo soon.
=> Added support for new field custom cron

airgun/entities/organization.py, airgun/views/common.py
Reverts SatelliteQE/airgun#258
Need update from widgetastic side
=> Revert "Added support of alert screen which appears after switching organization"

airgun/entities/computeresource.py, airgun/views/computeresource.py
tests output: https://github.com/SatelliteQE/robottelo/pull/6534
=> Fixes compute resource entity and implement images and profiles

airgun/browser.py, airgun/entities/organization.py, airgun/views/common.py, airgun/views/host.py, setup.py
=> Wrap new wait_for_element + alert handle for org switch

airgun/entities/host.py, airgun/entities/job_template.py, airgun/views/computeresource.py, airgun/views/host.py, airgun/views/job_invocation.py, airgun/views/job_template.py, airgun/widgets.py
Tests output https://github.com/SatelliteQE/robottelo/pull/6659
=> Fixes for Remote Execution jobs

airgun/entities/subscription.py, airgun/views/subscription.py, airgun/widgets.py
Test output at https://github.com/SatelliteQE/robottelo/pull/6708
=> Fixes Subscription entity delete upload manifest

airgun/views/contenthost.py, airgun/widgets.py
New feature of 6.5.
To get reproducer data in your Satellite, use the following steps: https://gitlab.sat.engineering.redhat.com/satellite6/katello/wikis/System-Purpose#db-queries-method
=> System_purpose

airgun/entities/host.py
test output https://github.com/SatelliteQE/robottelo/pull/6659#issuecomment-461393340
=> Fixes host entity schedule_remote_job

airgun/views/discoveryrule.py, airgun/widgets.py
test output https://github.com/SatelliteQE/robottelo/pull/6736#issue-252762785
=> Fixes Discovery Rule entity

airgun/entities/base.py, airgun/entities/host.py, airgun/helpers/base.py, airgun/helpers/host.py, airgun/views/host.py, airgun/widgets.py
tests output https://github.com/SatelliteQE/robottelo/pull/6696
=> Fixes Host entity

airgun/entities/host.py, airgun/views/host.py
test output https://github.com/SatelliteQE/robottelo/pull/6696#issuecomment-467798324
=> Fixes Host entity delete interface

airgun/entities/modulestream.py
adding stream_version attribute in read function to fix [SatelliteQE/robottelo#6762](https://github.com/SatelliteQE/robottelo/issues/6762)
```
platform linux -- Python 3.4.8, pytest-4.0.2, py-1.7.0, pluggy-0.8.1 -- /home/okhatavk/Satellite/robottelo/env/bin/python3.4
rootdir: /home/okhatavk/Satellite/robottelo, inifile:
plugins: xdist-1.26.1, services-1.3.1, mock-1.10.0, forked-1.0.2, cov-2.6.1
collecting 337 items                                                                                              2019-02-26 17:04:47 - conftest - DEBUG - Collected 383 test cases
2019-02-26 17:04:47 - …
```
=> Fixing robottelo 6762, adding stream_version attribute

airgun/entities/container.py, airgun/views/container.py
Test results in https://github.com/SatelliteQE/robottelo/pull/6773#issue-256759373
=> Fixes, new views and helpers for Container entity

airgun/browser.py
=> Fixes saucelabs idle_timeout

airgun/entities/rhai/action.py, airgun/entities/rhai/base.py, airgun/entities/rhai/inventory.py, airgun/entities/rhai/manage.py, airgun/entities/rhai/overview.py, airgun/entities/rhai/plan.py, airgun/entities/rhai/rule.py, airgun/exceptions.py, airgun/views/rhai.py
test output https://github.com/SatelliteQE/robottelo/pull/6813
=> Fixes rhai entities

airgun/browser.py, airgun/entities/contentview.py, airgun/entities/host.py, airgun/entities/rhai/action.py, airgun/entities/rhai/base.py, airgun/entities/rhai/inventory.py, airgun/entities/rhai/manage.py, airgun/entities/rhai/overview.py, airgun/entities/rhai/plan.py, airgun/entities/rhai/rule.py, airgun/exceptions.py, airgun/utils.py, airgun/views/common.py, airgun/views/rhai.py, airgun/widgets.py
Back port fixes to RHAI entities with some missing features.
testoutput https://github.com/SatelliteQE/robottelo/pull/6821
=> 6.4.z fixes back port rhai entities

airgun/views/dashboard.py
- Added Discovered Host widget .
=> added discovered hosts widget for dashboard

airgun/entities/host.py, airgun/entities/smart_variable.py, airgun/helpers/host.py, airgun/views/host.py, airgun/views/smart_variable.py
Affected by rowspan issue https://github.com/RedHatQE/widgetastic.core/issues/143
test output https://github.com/SatelliteQE/robottelo/pull/6783
=> Fixes Smart Variable and Host entities

airgun/entities/host.py
tesout put at https://github.com/SatelliteQE/robottelo/pull/6783#issuecomment-482589840
=> Fixes hosts set_puppet_class_parameter_value validation

airgun/entities/hostcollection.py
Proposing an if statement to close the Update Packages dialogue. I did try an else statement at the end but got errors.
Edit: I found this was required while working on https://github.com/SatelliteQE/robottelo/pull/6974
=> call done.click() if via Katello Agent (#331)

airgun/entities/settings.py, airgun/session.py, airgun/views/settings.py, airgun/widgets.py
This will add support for Settings UI component from Satellite. 
```
(env) [root@okhatavk robottelo]# pytest tests/foreman/ui_airgun/test_settings.py -v
========================================================= test session starts ==========================================================
platform linux -- Python 3.4.8, pytest-4.0.2, py-1.7.0, pluggy-0.9.0 -- /home/okhatavk/Satellite/robottelo/env/bin/python3.4
rootdir: /home/okhatavk/Satellite/robottelo, inifile:
plugins: xdist-1.26.1, services-1.3.1, mock-1.10.0, forked-1.0.2, cov-2.6.1
collecting ... 2019-06-04 11:24:11 - conftest - DEBUG - Collected 24 test cases
collected 24 items …
```
=> added support for component Settings UI

airgun/views/host.py
fixing https://github.com/SatelliteQE/airgun/issues/336
=> Fix regression for host entity

airgun/entities/ldap_authentication.py
Fixes https://github.com/SatelliteQE/robottelo/issues/6687
=> Added search for ldap auth

airgun/views/computeresource.py
Added support for GCE Compute Resource for :
=> GCE Compute Profile and Load Zones support added

docs/examples.rst
2-3 weeks ago, we removed old Robottelo UI framework and all Airgun checks moved from `ui_airgun` back to `ui`.
But I need this primarily to better understand shape of our automation around docs.
=> Update path in docs/examples

airgun/entities/virtwho_configure.py, airgun/session.py, airgun/views/virtwho_configure.py
This is a new support for virt-who configure page in satellite webUI, the following functions are ready to use:
1. create virtwho configuration
2. delete
3. edit
4. search
5. read
=> Add a new session for virtwho configure page

airgun/views/discoveredhosts.py
=> Fix UI Locator for Submit Form button

airgun/views/computeresource.py
- Updated the locator for create image
- Test result:
```
tests/foreman/ui/test_computeresource.py::test_positive_image_end_to_end PASSED                                                                                  [ 50%]
tests/foreman/ui/test_computeresource_vmware.py::test_positive_image_end_to_end PASSED                                                                           [100%]
```
=> Updated the locator for create image

airgun/browser.py, airgun/settings.py, settings.ini.example
Support to run webUI tests in headless mode for chrome
=> local web UI tests in headless mode

airgun/entities/contentview.py
This the succession PR from https://github.com/SatelliteQE/airgun/pull/371/files. I created this PR just to avoid confusion for people to understand.
=> Added fix for content view table

airgun/entities/oscapcontent.py, airgun/entities/oscaptailoringfile.py
=> fixes oscapcontent and oscaptailoringfile views

airgun/views/contentview.py
New RFE for dependency solving in content view and cv details.  Adding this new functionality to the view for use later.  I've also tested it out to make sure that UI selects the checkbox and dropdown correctly.
=> Add Solve Dependencies to View

airgun/views/virtwho_configure.py
1. other more options need to read in the detailed page.
2. get the debug checkbox status by the class  `VirtwhoConfiguresDebug`.
=> Read all the elements in the detail page

airgun/views/job_invocation.py
Resolving #350 
Tested with edited robottelo ui/test_jobinvocation.py
=> implemented checkbox group widget

airgun/entities/host.py, airgun/views/computeresource.py, airgun/views/host.py
New:
- ComputeResourceGoogleProfileStorageItem
- GoogleResourceForm
- Image support in Host Operating System
Updates to:
- Host Entity is updated to wait for JQuery to finish for 20 minutes
- load_zones moved under Zone class in GCE
=> GCE Host Provisioning support and updates to existing helpers

airgun/views/task.py
required due to: https://github.com/SatelliteQE/robottelo/issues/7220
must wait on changes from https://github.com/theforeman/foreman-tasks/pull/432 to get downstream
=> Update task table locator

airgun/entities/redhat_repository.py, airgun/views/redhat_repository.py
output:
```
(Pdb) dir(session.redhatrepository)
['HELPER_CLASS', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_helper', 'browser', 'create_bookmark', 'disable', 'enable', 'helper', 'navigate_to', 'read', 'recommended_repos', 'search', 'session']
(Pdb) 
(Pdb) rrepos = session.redhatrepository.recommended_repos()
NAVIGATE: Checking if already at All
NAVIGATE: I'm not at All
NAVIGATE: Heading to destination All
(Pdb) rrepos
[{'name': 'Red Hat Ansible Engine 2.8 RPMs for Red Hat Enterprise Linux 7 …
```
=> Added support for RH Recommended Repo

setup.py
Since https://github.com/SatelliteQE/robottelo/pull/7357 got merged, we can unpin dependencies here. Fixes #393
=> Don't version dependencies

airgun/entities/task.py, airgun/views/task.py, airgun/widgets.py
Adding view for new tasks dashboard.
=> add tasks charts support

airgun/entities/rhai/inventory.py, airgun/views/rhai.py
=> Fixes RHAI wait for inventory host view to be displayed.

airgun/entities/rhai/inventory.py, airgun/views/rhai.py
=> 6.4.z Fixes RHAI wait for inventory host view to be displayed.

airgun/entities/rhai/inventory.py, airgun/views/rhai.py
=> 6.5.z Fixes RHAI wait for inventory host view to be displayed.

airgun/views/virtwho_configure.py
Add function to get the name of virt-who options on Overview Page to support coverage for [BZ1649928](https://bugzilla.redhat.com/show_bug.cgi?id=1649928)
=> add function to get the name of virt-who options

airgun/browser.py, airgun/session.py
the commit extends the `Session` so it can accept optional `requests.sessions.Session` object.
This allows us to ue external mechanism to carry out the authentication, and make the UI session to use it.
e.g. robottelo [get_web_session()](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/helpers.py#L713) helper:
```python
from robottelo.helpers import get_web_session
from airgun.session import Session
def test_sesh():
with Session(session=get_web_session()):
pass
def test_old():
with Session():
pass
```
```bash
$ py.test --durations=0 test_sesh.py -s
2019-11-05 12:43:06 - conftest - DEBUG - Registering custom pytest_configure
============================================== test session starts ===============================================
platform linux -- Python 3.6.8, …
```
=> airgun.Session can now accept requests.sessions.Session cookie

airgun/entities/contentviewfilter.py, airgun/views/contentviewfilter.py
Adding support for module stream filter in UI From Upstream PR https://github.com/Katello/katello/pull/8295
https://github.com/SatelliteQE/robottelo/pull/7339
=> added support for the module stream filter in UI

airgun/views/job_invocation.py
This is new feature in Satellite and will be used in tests. I also moved query type because it is no longer hidden in advanced fields
=> add support for new rex ordering

airgun/widgets.py
Fixing the small input textbox and large input text box in settings.  Currently, automation does not recognize the large text area textbox and cannot update values in there.  This fix corrects this issue.
=> Input textbox fix

airgun/entities/http_proxy.py, airgun/session.py, airgun/views/http_proxy.py
=> Fixes #431 - Add http-proxy support

airgun/views/common.py, airgun/views/job_template.py
=> update view for new template editor

airgun/entities/provisioning_template.py
pretty straightforward fix.
my test cases were failing on this.
=> fix the provisioning_templates URI

airgun/browser.py
Another way of fixing problem described in #438 .
Let's first discuss in other PR which one we should merge.
```
$ pytest -v tests/foreman/ui/test_reporttemplates.py::test_positive_end_to_end tests/foreman/ui/test_host.py::test_positive_export
platform linux -- Python 3.6.3, pytest-4.6.3, py-1.8.0, pluggy-0.12.0 -- /home/mzalewsk/.virtualenvs/robottelo/bin/python3
rootdir: /home/mzalewsk/sources/robottelo
plugins: cov-2.7.1, forked-1.0.2, xdist-1.29.0, mock-1.10.4, services-1.3.1, repeat-0.8.0
collecting 2 items
2020-01-15 09:38:18 - conftest - DEBUG - Collected 2 test cases
2020-01-15 10:38:20 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f61ceca9cc0
2020-01-15 10:38:20 - robottelo.ssh - INFO - …
```
=> Rework downloading file from remote browser

airgun/entities/contenthost.py
Hello
For 6.5.z branch we need same as #451
Thank you
=> Change Remove Hosts to Delete Hosts (#451)

airgun/views/oscaptailoringfile.py
=> Fixes #446 - Fix Oscap Tailoring file view and entity.

airgun/entities/product.py, airgun/views/product.py
=> Fixes #448 - Add support for Product Select Action

airgun/views/contenthost.py
=> Use locator to resolve to OS not BIOS (#462)

airgun/entities/rhsso_login.py, airgun/session.py, airgun/views/rhsso_login.py
added support for PR SatelliteQE/robottelo#7657
=> added suppot for rhsso/keycloak login

airgun/entities/rhsso_login.py, airgun/views/common.py, airgun/views/rhsso_login.py, airgun/widgets.py
Adding support to Rhsso ext_logout scenarios. Which means any user logged in into Satellite as RHSSO User when they sign out there are seeing https://satellite_host/users/extlogout page. This Pr adds that support so we can validate scenarios based on the sign out in Satellite.
=> added ext logout support code

airgun/views/task.py
Hello
This change works in Firefox Dev Edition's console. But still not able to read the table in a test.
=> Fix task table locator

airgun/entities/settings.py, airgun/views/settings.py
=> Added "Test Mail" support for Sendmail/SMTP delivery method.

airgun/views/task.py
Custom paginaton needed due to changed button id. 
Will need a cherry-pick once acked
=> custom pagination for tasks page

airgun/views/task.py
cherry pick of https://github.com/SatelliteQE/airgun/pull/480
=> [cherry-pick 6.7] custom pagination for tasks page

airgun/entities/oscappolicy.py, airgun/views/oscappolicy.py
=> Fixes #368 -  Added view for deployment_option tab of scap policy

airgun/entities/ldap_authentication.py
Changes happened in the menu bar link cause the failure in regression. This is an expected UI from the product point of view.
```
tests/foreman/ui/test_ldap_authentication.py::test_positive_end_to_end_ad
==================== 1 passed, 2 warnings in 255.44 seconds ====================   
```
=> updating the latest link url based on Satellite 6.8

airgun/entities/ldap_authentication.py
=> Adding "Test Connection" for LDAPAuthenticationEntity.

airgun/entities/host.py
Cherry pick #492 into 6.7.z branch.
=> [cherry-pick] Rename "Play Ansible roles" action on hosts page

airgun/entities/ldap_authentication.py, airgun/views/ldapauthentication.py, airgun/widgets.py, docs/conf.py
https://github.com/SatelliteQE/airgun/pull/488
=> added changes related to card widget

airgun/entities/sync_templates.py, airgun/session.py, airgun/views/sync_templates.py, airgun/widgets.py
Support Sync (Import / Export) of templates from UI.
=> Sync Templates Support

airgun/views/job_invocation.py
Cherry-picking 38ffc7965955691a9f05c99b297e23a430cd6dbb (#493) to 6.6.z branch
=> [cherry-pick] Convert <a> to <input> on Job page (#493)

airgun/views/job_invocation.py
Affects 6.8 job invocation UI tests
=> job invocaton search query  changed identification

airgun/entities/cloud_inventory.py, airgun/session.py, airgun/views/cloud_inventory.py, airgun/widgets.py
Adding entity and view for RH Cloud - Inventory plugin, available in Satellite under "RH Cloud" -> "Inventory Upload" menu item.
In Satellite before 6.8 snap 5 you need to install plugin manually: `satellite-installer --enable-foreman-plugin-inventory-upload` or `satellite-installer --enable-foreman-plugin-rh-cloud` (depending on Satellite version).
Currently, there are no Robottelo tests that use these. I will be adding them later, but I'm going to need some changes in Robottelo first.
Also, I will be backporting these to all branches for supported Satellite versions, once I complete entire workflow.
tests:
```bash
$ cat tests/foreman/ui/test_cloudinventory.py 
from airgun.session import Session
def test_cloud():
with Session(user='admin', password='changeme') as session: …
```
=> Add RH Cloud - Inventory support

airgun/entities/job_template.py, airgun/views/job_template.py
Updated breadcrumb and added wait for dialog to appear.
=> fix in job template creation

airgun/views/computeresource.py
for test result see: https://github.com/SatelliteQE/robottelo/pull/7917
=> Add http_proxy parameter for ec2 and gce

airgun/entities/host.py, airgun/views/host.py
Description: This PR adds `Change OpenSCAP Capsule` and `Unassign Compliance Policy` host action support.
=> update host action list

airgun/entities/cloud_inventory.py, airgun/session.py, airgun/views/cloud_inventory.py, airgun/widgets.py
Cherry-pick #500 into `6.7.z`.
This is part of larger effort of running inventory upload tests on 6.7.z snaps.
Test result: see https://github.com/SatelliteQE/robottelo/pull/7983
=> [cherry-pick 6.7.z] Add RH Cloud - Inventory support (#500)

airgun/entities/syncplan.py
Hello
this blocks https://github.com/SatelliteQE/robottelo/pull/8012
test results will be there
=> Add support for removing a product from a syncplan

airgun/entities/user.py, airgun/views/product.py
Signed-off-by: Gaurav Talreja <gtalreja@redhat.com>
=> Add new column_widgets to create_repos_table

airgun/entities/ldap_authentication.py
```
Testing started at 9:38 PM ...
/home/okhatavk/okhatavk/Satellite/robottelo/env/bin/python /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 35839 --file /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pycharm/_jb_pytest_runner.py --target test_ldap_authentication.py::test_positive_test_connection_functionality
/home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pydev/_pydevd_bundle/pydevd_resolver.py:127: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if found.get(name) is not 1:
pydev debugger: process 23342 is connecting
Connected to pydev debugger (build 181.5087.37)
Launching py.test with arguments test_ldap_authentication.py::test_positive_test_connection_functionality …
```
=> fixed the ldap creation using kebab

airgun/views/contenthost.py
Hello
I need this for a pagination test. I will post test results with the new test when its ready.
Thank you
=> Add pagination support on CHost's errata tab

airgun/entities/contenthost.py
Hello
I need this for a new pagination test. Test results will be in that test soon.
Thank you
=> Add support to install all CHost's errata

airgun/views/host.py
Test Result:
```
$ pytest tests/foreman/ui/test_computeresource_azurerm.py -k test_positive_azurerm_host_provision_ud
=================== test session starts =====================
collected 2 items / 1 deselected / 1 selected                                                                                                                                                                     
tests/foreman/ui/test_computeresource_azurerm.py . 
============= 1 passed, 1 deselected in 501.71s (0:08:21) ========
```
=> Fix the 'Create new host' locator

airgun/entities/rhsso_login.py, airgun/views/rhsso_login.py
watch the result of the PR https://github.com/SatelliteQE/robottelo/pull/8270
=> added support for the TOTP feature

airgun/views/common.py
locator for account menu changed in 6.9 
```
collected 30 items / 29 deselected / 1 selected
test_host.py::test_positive_read_from_details_page 2020-12-14 15:30:34 - robottelo - DEBUG - Finished Test: test_host.py/test_positive_read_from_details_page
========== 1 passed, 29 deselected, 21 warnings in 132.23s (0:02:12) ===========
```
=> locator fix for account menu

airgun/entities/report_template.py, airgun/views/common.py, airgun/views/job_template.py, airgun/views/report_template.py
=> Fix reporting for Sat 6.9

airgun/entities/host.py
previously airgun failed on attempting to fill in the form before actually getting to the dialog
=> wait for registration dialog to come up

airgun/views/host.py
=> new insecure option for global registration UI

airgun/views/contenthost.py
requested IDs landed within https://bugzilla.redhat.com/show_bug.cgi?id=1931527 modifying the view accordingly
=> ids for SyspurposeBulkActionView

airgun/entities/repository.py
This PR fixes the logic for looking up the global default http proxy for content repositories. In Satellite 6.8, the setting has a value of 'no global default' when unset, while on Satellite 6.9 the value is 'Empty'.
=> Fix global default http proxy lookup

airgun/browser.py, airgun/entities/cloud_inventory.py, airgun/views/cloud_inventory.py, airgun/widgets.py, setup.py
This PR fixes Entities/Views for Inventory upload page.
The page is based on PF4 so I have used widgets available in widgetastic_patternfly4 library(Specifically the Switch widget).
=> Update rh_cloud inventory page code to support pf4

airgun/entities/contentview.py, airgun/views/contentview.py
Puppet module removal from views and entities section.
=> Removing all elements of puppet modules from view and entities file

.github/workflows/pull_request.yml, .pre-commit-config.yaml
Airgun doesn't have GHA for commits and this PR is for implementing that to be like robottelo.
=> GHA for airgun

airgun/entities/cloud_insights.py, airgun/session.py, airgun/views/cloud_insights.py, airgun/widgets.py
This PR adds airgun support for RH Insights page.
It allows to sync, search and remediate insights recommendations.
I will provide some kind of test result soon.
=> Add support for Red Hat Insights page

airgun/entities/provisioning_template.py, airgun/views/provisioning_template.py, airgun/views/sync_templates.py
Cherry-pick of #588 from master to 6.9.z.
=> Cherry-pick: Changes needed to fix templatesync tests

airgun/entities/login.py, airgun/views/login.py
=> [Cherry-pick]Added flash data cleanup before logout

airgun/entities/settings.py, airgun/views/common.py
**Test result:**
```
#pytest tests/foreman/ui/test_settings.py::test_negative_settings_access_to_non_admin
tests/foreman/ui/test_settings.py .                                                                                                                                                                         [100%]
================================================================================================ warnings summary ================================================================================================= …
```
=> Added  permission denied entity in settings module

airgun/entities/settings.py, airgun/views/common.py
**Test Result:**
```
$ pytest -s tests/foreman/ui/test_settings.py::test_negative_settings_access_to_non_admin
platform linux -- Python 3.8.0, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
collected 1 item                                                                                                                                                                                                  
tests/foreman/ui/test_settings.py 
.
========================================================================================= 1 passed, 4 warnings in 48.70s …
```
=> [Cherry-pick] Added permission denied entity in settings module

airgun/entities/host.py
Test Result :
https://github.com/SatelliteQE/robottelo/pull/8864
=> gr fix with navigate using left panel

airgun/views/host.py, airgun/views/smart_class_parameter.py, airgun/widgets.py
connected to https://bugzilla.redhat.com/show_bug.cgi?id=1996035
and with issue #608 
the problem is we can't have only one of these locators, because sometimes we use the mouse to hover over and sometimes not, so just fixing is this way, even though I think it's not the best solution but definitely with the least effort possible. 
this is not fixing the issue,  just showing the way how to workaround it, issue can occur also with other elements
=> hover over issue resolved

airgun/widgets.py
wt.core removed it, and airgun didn't have it as a direct dependency.
instead of including it, since the project is unmaintained, remove it
=> Remove jsmin dependency

airgun/views/hostgroup.py
Robottelo PR : https://github.com/SatelliteQE/robottelo/pull/8996
=> added support for the nested host-groups

airgun/widgets.py
wt.core removed it, and airgun didn't have it as a direct dependency.
instead of including it, since the project is unmaintained, remove it
cherry-pick into 6.7.z
=> [6.7.z cherry-pick] Remove jsmin dependency (#616)

airgun/widgets.py
wt.core removed it, and airgun didn't have it as a direct dependency.
instead of including it, since the project is unmaintained, remove it
Cherry pick for 6.8.z
=> [6.8.z cherry-pick] Remove jsmin dependency (#616)

airgun/browser.py, airgun/settings.py, settings.ini.example, setup.py
- Addition of Web-Kaifuku 
- Removing dead code for the Browser Factory
- Removing dead code form sauce lab, docker selenium and adding them in web-kaifuku repo
- Addition of ui.yaml file for configuration (https://github.com/SatelliteQE/robottelo/pull/9015)       
- CI PR : 399
=> handling the browser factory using the webkaifuku

airgun/browser.py, airgun/settings.py, settings.ini.example, setup.py
(cherry picked from commit 5109fe27d8339e7eca99cb980ffb98f7b38c5cb0)
=> [6.9.z] handling the browser factory using the webkaifuku

airgun/entities/product.py, airgun/views/product.py
1]  Added support for Advanced Sync on products page.
2]  Added both Optimized sync as well as Complete sync.
=> Add support for Product Advanced Sync

.pre-commit-config.yaml, airgun/entities/product.py, airgun/views/cloud_insights.py, airgun/views/subscription.py, airgun/views/sync_status.py, airgun/widgets.py
same problem as robottelo has 
https://github.com/SatelliteQE/robottelo/pull/9150
=> update pre commit

.pre-commit-config.yaml, airgun/entities/product.py, airgun/entities/repository.py, airgun/views/subscription.py, airgun/views/sync_status.py, airgun/widgets.py
SSIA
`""" "` changed to only three double quotes `"""`
and max indeed takes list comprehension, but it a bit more time, i think we don't care about that here :)
=> update pre-commit for 6.9.z

airgun/entities/host.py, airgun/views/host.py
See https://github.com/SatelliteQE/robottelo/pull/9161#issue-1054469888 for test result.
=> Add read_insights_recommendations for host entity

airgun/browser.py, setup.py
Sibling PR to https://github.com/SatelliteQE/robottelo/pull/9235
=> replace attrdict with box

airgun/widgets.py
This PR fixes locators for Search(`searchbar`) which is causing some of the Satellite UI tests to fail.
=> Fix search for Satellite 7.0

airgun/exceptions.py
=> [Cherry-Pick] Add selenium exceptions to airgun

airgun/widgets.py
Satellite 7.0 has new Confirmation dialog for deleting entities. This PR adds new ConfirmationBox widget to support it.
=> PF4 confirmation dialog for Satellite 7.0

airgun/entities/configgroup.py, airgun/entities/puppet_class.py, airgun/entities/puppet_environment.py, airgun/entities/smart_class_parameter.py
The puppet-related URLs changed with movement into a plugin in 7.0.
=> Fix puppet-related URLs

airgun/widgets.py
Hi
locators for flash messages on SyncPlan add product page have changed
`<h4 class="pf-c-alert__title"><span class="pf-u-screen-reader">Success alert:</span>Added 1 products to sync plan "HvfkNBdVvg".</h4>`
`<h4 class="pf-c-alert__title"><span class="pf-u-screen-reader">Success alert:</span>Removed 1 products from sync plan "HvfkNBdVvg".</h4>`
`<ul class="pf-c-alert-group pf-m-toast"><li><div class="pf-c-alert pf-m-success foreman-toast" aria-label="Success Alert" data-ouia-component-type="PF4/Alert" data-ouia-safe="true" data-ouia-component-id="OUIA-Generated-Alert-success-1"><div class="pf-c-alert__icon"><svg fill="currentColor" height="1em" width="1em" viewBox="0 0 512 512" aria-hidden="true" role="img" style="vertical-align: -0.125em;"><path d="M504 256c0 136.967-111.033 248-248 …
=> Update SyncPlan flash locator

setup.py
$subject
i.e. c-pick https://github.com/SatelliteQE/airgun/pull/663
=> Cherry pick 663 - adding selenium4 dependancy

airgun/views/host.py
Hello
An update to support the "Update packages" check box on the global registration form, advanced tab.
Required for:
[ Add test update packages checkbox #9380 ](https://github.com/SatelliteQE/robottelo/pull/9380)
Thank you
=> Add support reg update packages

airgun/entities/host.py
Adding option to use old UI which is used in RHEL7 and new UI that is used in both RHEL8 and 9.
=> Update cockpit new UI

airgun/views/repository.py
Added mirroring policy to the repository view page as well as added the file repo in repoEdit section.  Rearranged some fields so it matches with what we have in the UI for better comparison.
=> Add mirroring policy to repository page

airgun/views/dashboard.py
adding a view for the job invocations table on the dashboard
=> add view for job invocation dashboard

airgun/entities/role.py, airgun/entities/user.py, airgun/entities/usergroup.py
1.  Adding Delete confirmation for Users&Roles
=> Delete Confirmation for UsersRoles

airgun/entities/computeresource.py
**Test results** -
```
$ pytest  tests/foreman/ui/test_computeresource_gce.py -k test_positive_default_end_to_end_with_custom_profile 
========================================================================================================= test session starts =========================================================================================================
platform linux -- Python 3.8.6, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
rootdir: /home/sganar/satellite/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, mock-3.6.1, forked-1.3.0, ibutsu-2.0.2, reportportal-5.0.11, cov-3.0.0, xdist-2.5.0 …
```
=> Delete confirmation for Compute resource - [GCE]

setup.py
selenium 4 was introduced through wt.core 1.0.0 and wt.pf4 1.0.0
=> Switch back to wt.pf4 released version

setup.py
https://github.com/SatelliteQE/airgun/pull/692
=> Backport 692, wt.pf4 update

airgun/views/cloud_inventory.py
`Small fix for rh_cloud test_cases failing with element locator error.`
=> rhcloud-UI fix for test cases failing with locator error

airgun/views/host_new.py
new dropdown locator
and new host ui details, each card and tab is loaded separately, last network response comes from recent job cards, so I used it to ensure page is loaded
=> new host details dropdown locator fix

airgun/entities/login.py, airgun/views/login.py
For https://github.com/SatelliteQE/robottelo/pull/9609
=> [6.10.z] Reading sat version from login screen

airgun/browser.py, airgun/entities/activationkey.py, airgun/entities/computeresource.py, airgun/entities/configgroup.py, airgun/entities/contentcredential.py, airgun/entities/contenthost.py, airgun/entities/host.py, airgun/entities/hostcollection.py, airgun/entities/http_proxy.py, airgun/entities/location.py, airgun/entities/organization.py, airgun/entities/oscapcontent.py, airgun/entities/oscappolicy.py, airgun/entities/oscaptailoringfile.py, airgun/entities/product.py, airgun/entities/puppet_environment.py, airgun/entities/repository.py, airgun/entities/role.py, airgun/entities/syncplan.py, airgun/entities/user.py, airgun/entities/usergroup.py, airgun/entities/virtwho_configure.py
=> Added custom behaviour get_alert and handle_alert

airgun/views/filter.py
Adding pagination to Filtersview required for the test `test_positive_create_with_21_filters` in ui/test_role.py
=> Add pagination to Filtersview

airgun/views/filter.py
Cherrypick of https://github.com/SatelliteQE/airgun/pull/706
=> [6.10]Add pagination to Filtersview 

airgun/views/hostgroup.py
Robottelo PR https://github.com/SatelliteQE/robottelo/pull/9644
=> fixed the puppet ui tests for Sat-6.11

airgun/entities/discoveredhosts.py, airgun/entities/discoveryrule.py, airgun/views/discoveredhosts.py, airgun/views/discoveryrule.py
Back porting: https://github.com/SatelliteQE/airgun/pull/712
Fixes creating a rule with no other rules created and clicking dialog submit button.
=> Fixing discovery failures for 6.10.z

airgun/widgets.py
=> Close action dropdown after reading

airgun/entities/user.py
Removing unnecessary handle_alert which  is causing User end_to_end test to fail
=> Remove unnecessary handle_alert

airgun/browser.py, airgun/entities/computeresource.py
Workaround for e.g. https://bugzilla.redhat.com/show_bug.cgi?id=2106022
=> Skipping ensure_page_safe on timeout. 

airgun/entities/hardware_model.py, airgun/views/hardware_model.py, airgun/views/host.py, airgun/widgets.py
Targeted mainly for 6.12, but should not cause any issues on 6.11 as locators are the same for creating host and search is just adding another option.
=> fix locators for hardware models tests

airgun/entities/task.py, airgun/views/task.py
In 6.12 Tasks pagination has changed to PF4. Also, adding support for getting the total count of items in the table via entities due to changes in class implementation.
=> Fix tasks pagination

airgun/views/login.py
Locator for login page footer is updated which is causing test failures around components.
=> Fixing locator for login page footer

airgun/entities/host_new.py, airgun/views/host_new.py
Also part of this PR is replacing Cards locators that were based on their position in UI with locators based on names. As those elements are dynamically generated we cannot rely on their position.
All locators were tested and seem to work without any issue, except those ones that are disabled/not presented in 6.11.
=> Add content tab to new host UI

airgun/entities/host.py
Tests in linked robotello PR: SatelliteQE/robottelo#10011
=> Ensure cockpit page is safe before locating elements

.github/workflows/auto_cherry_pick.yml
applying same as https://github.com/SatelliteQE/robottelo/pull/10015
=> updating the airgun autocherrypick n-1 version as robottelo

airgun/entities/puppet_class.py, airgun/views/puppet_class.py
The change was introduced in 6.12 with transition to PF4.
=> Rename column in puppet class table

airgun/views/rhsso_login.py
fixing the locator for logout page rhsso
=> fixing the locator for logout page rhsso

airgun/widgets.py
As [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2111222) was resolved we can use static OUIA id
=> Add static OUIA id for close button in confirmation dialog

airgun/views/contenthost.py
Locator fix for failing UI tests.
=> Locator fix for errata

airgun/entities/contentview_new.py, airgun/session.py, airgun/views/common.py, airgun/views/contentview_new.py, airgun/widgets.py
Just the basic functionality of creating a cv and searching for the cv.
=> Create cv and search for new CV UI

airgun/widgets.py
Locator updated for settings field for 6.11 and 6.12
=> Updated locator for Text field in Settings

airgun/views/host.py, airgun/views/host_new.py
Some of the IDs were changed to static ones. 
There are still dynamic IDs in the registration form, as there was a new option for pull provider (included in this PR), the ID for LCE has increased.
=> Fix OUIA IDs in hosts

airgun/entities/hostgroup.py
https://github.com/SatelliteQE/robottelo/pull/10190
=> added the support for the clone host-group

airgun/entities/cloud_insights.py
=> Uncommenting select_all_hits

airgun/views/provisioning_template.py
Fixing a minor typo in provisioning_template.py
=> Fix minor typo

airgun/views/host_new.py
Tests in: SatelliteQE/robottelo/pull/10085
=> Change status id to static one

.github/auto_assign.yml, .github/workflows/auto_assignment.yaml, .github/workflows/auto_cherry_pick.yml
Aligning ACP GHA with Robottelo:
- Adding branch labels
- Assigning the autocherrypicked PR to original user
- Adding Notifications to GChat group improvement on failed auto cherrypick
- Adding Create issue on failed auto cherrypick
- [New] Added AutoAssigning
=> Aligning ACP GHA with Robottelo

.pre-commit-config.yaml, setup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/784
Recommended by @abravalheri in https://github.com/pypa/setuptools/issues/3707#issuecomment-1325605870
=> [6.11.z] Switch classifiers from a tuple to a list

airgun/entities/ansible_role.py, airgun/views/ansible_role.py, airgun/views/ansible_variable.py, airgun/widgets.py
Couple of changes here to fix some role/Variable UI tests - including removing some "failsafe" checks that always failed
=> Fixes for Robottelo Role/Variable UI tests

airgun/entities/host_new.py, airgun/views/host_new.py
This will be used in SatelliteQE/robottelo/pull/10151
=> Add repository sets to new host details UI

airgun/views/ansible_role.py, airgun/views/ansible_variable.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/775
Couple of changes here to fix some role/Variable UI tests - including removing some "failsafe" checks that always failed
=> [6.11.z] Fixes for Robottelo Role/Variable UI tests

.github/workflows/auto_cherry_pick.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/788
Refer: https://github.com/SatelliteQE/robottelo/pull/10366
=> [6.12.z] Cherrypicking based on branch labels added to the parent PR

.github/workflows/auto_cherry_pick.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/788
Refer: https://github.com/SatelliteQE/robottelo/pull/10366
=> [6.11.z] Cherrypicking based on branch labels added to the parent PR

.github/workflows/auto_cherry_pick.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/788
Refer: https://github.com/SatelliteQE/robottelo/pull/10366
=> [6.13.z] Cherrypicking based on branch labels added to the parent PR

airgun/entities/ansible_role.py, airgun/views/ansible_role.py, airgun/views/ansible_variable.py
`Test results`
pytest tests/foreman/ui/test_ansible.py 
============================================================================ test session starts ============================================================================
platform linux -- Python 3.8.6, pytest-7.1.3, pluggy-1.0.0
rootdir: /home/addubey/work/robottelo, configfile: pyproject.toml
plugins: forked-1.4.0, services-2.2.1, cov-3.0.0, xdist-3.1.0, ibutsu-2.2.4, reportportal-5.1.3, mock-3.10.0
collected 3 items                                                                                                                                                           
tests/foreman/ui/test_ansible.py ... …
=> Ansible UI fixes

airgun/entities/config_report.py, airgun/session.py, airgun/views/config_report.py
`Adding entities & views for the config report parameter`
=> Adding support for config_report

airgun/entities/config_report.py, airgun/session.py, airgun/views/config_report.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/791
`Adding entities & views for the config report parameter`
=> [6.13.z] Adding support for config_report

airgun/entities/config_report.py, airgun/session.py, airgun/views/config_report.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/791
`Adding entities & views for the config report parameter`
=> [6.12.z] Adding support for config_report

.github/workflows/auto_cherry_pick.yml, .github/workflows/automerge.yaml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/801
Added support in AIrgun for automerge
=> [6.11.z] adding auto merge in airgun

.github/workflows/auto_cherry_pick.yml, .github/workflows/automerge.yaml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/801
Added support in AIrgun for automerge
=> [6.12.z] adding auto merge in airgun

.github/workflows/auto_cherry_pick.yml, .github/workflows/automerge.yaml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/801
Added support in AIrgun for automerge
=> [6.13.z] adding auto merge in airgun

airgun/entities/cloud_inventory.py
The test is failing because of a missing confirmation dialog click.
Fixes https://github.com/SatelliteQE/robottelo/pull/10660
=> Fix configure_cloud_connector method

airgun/views/computeresource.py
=> Removing email project_id cert_path based on the new GCE-CR feature

airgun/entities/ansible_role.py, airgun/views/ansible_role.py, airgun/views/ansible_variable.py
Ansible UI fixes
https://github.com/SatelliteQE/airgun/pull/790
=> Cherry-picking Ansible UI fixes

airgun/entities/host_new.py, airgun/views/host_new.py
@adarshdubey-star - sorry for the delay! here's the cherrypick you requested.
=> Cherrypick New Host Ansible work

airgun/views/common.py, airgun/views/job_invocation.py
Updated the remote execution view to accommodate the new job wizard
=> new job-inv page

airgun/views/common.py, airgun/views/job_invocation.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/819
Updated the remote execution view to accommodate the new job wizard
=> [6.13.z] new job-inv page

airgun/entities/host_new.py, airgun/views/host_new.py
In this PR, I am improving airgun by adding new host details cards and finishing unfinished views (Overview, Details, Content, Parameters, Traces, Reports, Insights, Puppet). Basic entities for reading values from UI are present too.
For more info see SAT-16452.
=> View for multiple host tabs added

airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/835
Minor fix in view.host for organization locator
=> [6.12.z] Fix Organization in Host

airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/835
Minor fix in view.host for organization locator
=> [6.11.z] Fix Organization in Host

airgun/entities/host_new.py, airgun/views/host_new.py
I have implemented new entities that allow us to do several actions on the new host details page: 
* Edit system purpose
* Add host to host collection
* Remove host from host collection
* Add new parameter
* Edit parameter
* Delete parameter
* Remediate with insights
I have also made some view extension that was needed, to create those entities.
=> Extension of NewHostUI entities

.github/workflows/auto_cherry_pick.yml
Now Autocherrypick the merged PR by adding a branch and/or CherryPick label.
=> AutoCherrypick of merged PRs

airgun/session.py
=> logging session-id, it can be used by while searching test in grid4

.github/workflows/auto_cherry_pick.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/854
null
=> [6.14.z] fixed the cherry pick GHA

airgun/browser.py
=> removing the unknown desired capability attributes

airgun/browser.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/853
=> [6.14.z] removing the unknown desired capability attributes

airgun/browser.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/853
=> [6.13.z] removing the unknown desired capability attributes

airgun/browser.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/853
=> [6.11.z] removing the unknown desired capability attributes

airgun/browser.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/853
=> [6.12.z] removing the unknown desired capability attributes

airgun/entities/virtwho_configure.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/851
Test cases: PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_hyperv.py  -k test_positive_hypervisor_id_option --disable-pytest-warnings -q
1 passed, 5 deselected, 4 warnings in 301.34s (0:05:01)
```
.
=> [6.14.z] add check virtwho config create&edit&delete flash message

airgun/views/host.py
Changes from https://github.com/Katello/katello/pull/10590
=> Update Activation Keys OUIA ID

airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/866
Changes from https://github.com/Katello/katello/pull/10590
=> [6.14.z] Update Activation Keys OUIA ID

airgun/views/host_new.py
This view is for a 6.13.z RFE
Updating host views with new locators
=> [RFE 6.13.z] Updating host views for 6.13.z

airgun/views/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/865
This view is for a 6.13.z RFE
Updating host views with new locators
=> [6.13.z] [RFE 6.13.z] Updating host views for 6.13.z

airgun/entities/activationkey.py, airgun/entities/host_new.py, airgun/views/activationkey.py, airgun/views/host_new.py
New views and entities for Host and Activation Keys
Host:
- Added bulk override of repository sets
- Added new Repository Type field
Activation Keys:
- Get repository data for repository sets
- Added repository type field added to table
=> [6.14 RFE] New Host and AK views and entities

airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/892
Fixes for failing UI test cases - new locators for org and loc in ContextSelector.
=> [6.14.z] Fixing organization and location locators

airgun/entities/activationkey.py, airgun/entities/host_new.py, airgun/views/activationkey.py, airgun/views/host_new.py
https://github.com/SatelliteQE/airgun/pull/852
Fixes https://github.com/SatelliteQE/airgun/issues/889
* updating new hosts and ak views/entities
* updated docstring
* removed widget_name and updated views
(cherry picked from commit 759adea42ea83f12685d65e49da05455c705b555)
=> [6.14 RFE] [6.14.z] New Host and AK views and entities (#852)

airgun/views/common.py
Needed to fix audit tests
```
pytest tests/foreman/ui/test_audit.py -k  test_positive_audit_comment
================================================ test session starts =================================================
tests/foreman/ui/test_audit.py .                                                                               [100%]
=============================== 1 passed, 5 deselected, 1 warning in 84.57s (0:01:24) ================================
```
=> current user dropdown updated

airgun/views/common.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/903
Needed to fix audit tests
```
pytest tests/foreman/ui/test_audit.py -k  test_positive_audit_comment
================================================ test session starts =================================================
tests/foreman/ui/test_audit.py .                                                                               [100%]
=============================== 1 passed, 5 deselected, 1 warning in 84.57s (0:01:24) ================================
```
=> [6.14.z] current user dropdown updated

airgun/views/common.py
Pulling out only the search changes.
=> Add check for existence of title

airgun/views/common.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/934
Pulling out only the search changes.
=> [6.14.z] Add check for existence of title

airgun/views/common.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/934
Pulling out only the search changes.
=> [6.13.z] Add check for existence of title

airgun/views/common.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/934
Pulling out only the search changes.
=> [6.12.z] Add check for existence of title

airgun/entities/configgroup.py, airgun/entities/puppet_class.py, airgun/entities/puppet_environment.py, airgun/entities/smart_class_parameter.py
Missed during https://github.com/SatelliteQE/airgun/pull/919
=> Update puppet entity routes for PF4 navigation

airgun/entities/cloud_insights.py
Required for https://github.com/SatelliteQE/robottelo/pull/12210
=> Fix remediate method of CloudInsightsEntity

setup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/951
After upgrading to selenium `4.12.0`, it caused the issue. Everything works fine with `4.11.2  `
=> [6.12.z] pining the selenium version to 4.11.2

airgun/browser.py
=> adding the test name as metadata for searching in grid sessions

airgun/entities/redhat_repository.py
In this small PR, I have added an option to search for RedHat repository via custom query which was not available in the current implementation of the `enable` function.
=> Enabling RedHat repositories enhanced

airgun/browser.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/964
=> [6.12.z] adding the test name as metadata for searching in grid sessions

airgun/entities/host_new.py, airgun/views/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/966
* add Host Statues modal support
* address comments
* address comments & fix stuck modal
=> [6.12.z] add Host statuses modal support (#966)

airgun/entities/host_new.py, airgun/views/host_new.py
Parent PR https://github.com/SatelliteQE/airgun/pull/966
* add Host Statues modal support
* address comments
* address comments & fix stuck modal
(cherry picked from commit f8c114b7015733e50c7e53be3c2a48b06631d061)
=> [6.14.z] add Host statuses modal support (#966)

airgun/entities/filter.py, airgun/views/filter.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/979
null
=> [6.14.z] Add PF4 versions of MultiSelect and FilteredDropdown. Use them in Filters.

airgun/entities/acs.py
Adding wait_for to fix test stability issues.
=> ACS Stability issues fix

airgun/views/host.py
Missed during https://github.com/SatelliteQE/airgun/pull/866
Changes from https://github.com/Katello/katello/pull/10590
=> Update Activation Keys helper OUIA ID

airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1006
null
=> [6.14.z] Add read() method for BaseMultiSelect widget

airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1006
null
=> [6.12.z] Add read() method for BaseMultiSelect widget

.github/workflows/pull_request.yml, .pre-commit-config.yaml
Doing similar in Airgun what we did here in https://github.com/SatelliteQE/nailgun/pull/997 nailgun
=> enabled the pre-commit CI and remove pre-commit GH action

airgun/views/ansible_role.py, airgun/views/ansible_variable.py, airgun/views/cloud_insights.py, airgun/views/filter.py, airgun/views/host_new.py, airgun/views/location.py, airgun/views/task.py, airgun/widgets.py
Cherrypick from #947 to 6.13.z
=> [6.13.z] Pagination refactor

airgun/entities/eol_banner.py, airgun/session.py, airgun/views/eol_banner.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1049
end of life banner view and entity
=> [6.15.z] eol banner

airgun/entities/provisioning_template.py, airgun/views/provisioning_template.py
=> Add check to verify supported provisioning templates

airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1064
null
=> [6.15.z] Add error-msg class in ValidationErrors for settings

airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1064
null
=> [6.14.z] Add error-msg class in ValidationErrors for settings

airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1064
null
=> [6.12.z] Add error-msg class in ValidationErrors for settings

airgun/entities/provisioning_template.py, airgun/views/provisioning_template.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1059
=> [6.13.z] Add check to verify supported provisioning templates

airgun/entities/provisioning_template.py, airgun/views/provisioning_template.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1059
=> [6.15.z] Add check to verify supported provisioning templates

airgun/entities/provisioning_template.py, airgun/views/provisioning_template.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1059
=> [6.12.z] Add check to verify supported provisioning templates

airgun/views/host.py
Related Katello PR https://github.com/Katello/katello/pull/10764
=> Remove LCE field from HostRegisterView

airgun/entities/capsule.py, airgun/session.py, airgun/views/capsule.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1050
In this PR I have added views and entities for Satellite page coverage.
=> [6.15.z] Added Satellite Capsule page coverage

airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1069
Related Katello PR https://github.com/Katello/katello/pull/10764
=> [6.15.z] Remove LCE field from HostRegisterView

airgun/entities/capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1082
Adding few `wait_displayed`. I've spotted slightly slower response on 6.15 and CP PRT was failing due to that.
=> [6.15.z] Add some wait_displayed

airgun/entities/base.py, airgun/views/common.py, airgun/widgets.py
Adding new widgets and function for new search feature in the vertical navigation menu.
You can use the menu search functionality in any entity via `BaseEntity.search_menu()`.
=> Search functionality for vertical navigation menu

airgun/__init__.py, airgun/entities/errata.py, airgun/views/errata.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1013
in the form DSA-1234-1
=> [6.15.z] Added possibility to search for debian errata

.github/workflows/auto_cherry_pick_merge.yaml
Automerge is failing, not because of the right changes. This PR will fix this.  
This will fix the auto-merge failing at PR https://github.com/SatelliteQE/airgun/pull/1100
=> fixing the auto-merge PR's in Airgun

.github/workflows/auto_cherry_pick_merge.yaml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1113
Automerge is failing, not because of the right changes. This PR will fix this.  
This will fix the auto-merge failing at PR https://github.com/SatelliteQE/airgun/pull/1100
=> [6.15.z] fixing the auto-merge PR's in Airgun

.github/workflows/auto_cherry_pick_merge.yaml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1113
Automerge is failing, not because of the right changes. This PR will fix this.  
This will fix the auto-merge failing at PR https://github.com/SatelliteQE/airgun/pull/1100
=> [6.14.z] fixing the auto-merge PR's in Airgun

airgun/views/job_invocation.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1099
null
=> [6.15.z] Correct capitalization

airgun/views/job_invocation.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1099
null
=> [6.14.z] Correct capitalization

airgun/entities/subscription.py
Moving method into SubscriptionEntity class.
=> moving sca alert into sub class

airgun/__init__.py, airgun/entities/errata.py, airgun/views/errata.py
Manual cherry-pick of https://github.com/SatelliteQE/airgun/pull/1013
=> [6.14.z] Added possibility to search for debian errata

airgun/views/oscapcontent.py
=> SCAP content > SCAP contents

airgun/views/oscapcontent.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1203
Updating the page title
=> [6.15.z] SCAP content > SCAP contents

airgun/entities/host.py, airgun/entities/job_invocation.py, airgun/views/host.py, airgun/views/job_invocation.py
Manual cherry-pick of https://github.com/SatelliteQE/airgun/pull/1226
=> [6.15.z] Change content source cherry-pick

airgun/entities/errata.py
supports errata UI e2e fix https://github.com/SatelliteQE/robottelo/pull/14095
=>  wait to display page in search_content_hosts()

airgun/entities/errata.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1240
supports errata UI e2e fix https://github.com/SatelliteQE/robottelo/pull/14095
=> [6.15.z]  wait to display page in search_content_hosts()

airgun/entities/errata.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1240
supports errata UI e2e fix https://github.com/SatelliteQE/robottelo/pull/14095
=> [6.14.z]  wait to display page in search_content_hosts()

airgun/views/computeresource.py, airgun/views/dashboard.py, airgun/views/discoveryrule.py, airgun/views/package.py, airgun/views/repository.py, airgun/views/subnet.py, airgun/widgets.py
manual cherrypick of https://github.com/SatelliteQE/airgun/pull/1200, closes https://github.com/SatelliteQE/airgun/issues/1230
=> [6.13] pf4 bookmarks dropdown

airgun/views/computeresource.py, airgun/views/dashboard.py, airgun/views/discoveryrule.py, airgun/views/package.py, airgun/views/repository.py, airgun/views/subnet.py, airgun/widgets.py
manual cherrypick of https://github.com/SatelliteQE/airgun/pull/1200, closes https://github.com/SatelliteQE/airgun/issues/1229
=> [6.14] pf4 bookmarks dropdown

airgun/views/job_invocation.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1263
null
=> [6.14.z] Fixing some views in job_invocation

airgun/views/job_invocation.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1263
null
=> [6.15.z] Fixing some views in job_invocation

.github/workflows/prt_labels.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1261
some more updated on PRT label checks, adding conditional statements.
=> [6.15.z] some more updated on PRT label checks

.github/workflows/prt_labels.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1261
some more updated on PRT label checks, adding conditional statements.
=> [6.14.z] some more updated on PRT label checks

.github/workflows/prt_labels.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1261
some more updated on PRT label checks, adding conditional statements.
=> [6.13.z] some more updated on PRT label checks

airgun/views/repository.py
Original PR was only merged into master  https://github.com/SatelliteQE/airgun/pull/1029#issuecomment-1996623083
=> [CP] Add debian repository to views

airgun/entities/contenthost.py
=> Check that breadcrumb is displayed

airgun/entities/host.py
manual cherry pick of https://github.com/SatelliteQE/airgun/pull/1087 It seems parts of it were already cherrypicked somehow, but this piece was missing
=> [6.14] Update get_register_command to reflect new mandatory fields (#1087)

airgun/entities/hardware_model.py
=> Wait for toast/flash message to be visible

airgun/entities/host.py, airgun/entities/host_new.py, airgun/entities/job_invocation.py
I have done TFA for SAT-20041 and found that these airgun changes are needed for the tests to start working.
This PR is needed for https://github.com/SatelliteQE/robottelo/pull/14512
=> Fixes needed for some Endeavour tests to run correctly

airgun/entities/host.py, airgun/entities/host_new.py, airgun/entities/job_invocation.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1295
I have done TFA for SAT-20041 and found that these airgun changes are needed for the tests to start working.
This PR is needed for https://github.com/SatelliteQE/robottelo/pull/14512
=> [6.14.z] Fixes needed for some Endeavour tests to run correctly

airgun/entities/host.py, airgun/entities/host_new.py, airgun/entities/job_invocation.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1295
I have done TFA for SAT-20041 and found that these airgun changes are needed for the tests to start working.
This PR is needed for https://github.com/SatelliteQE/robottelo/pull/14512
=> [6.15.z] Fixes needed for some Endeavour tests to run correctly

airgun/entities/hardware_model.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1280
Error occured in 6.15.z
=> [6.15.z] Wait for toast/flash message to be visible

airgun/entities/host_new.py, airgun/views/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1300
=> [6.14.z] add/update host_new entities & views

airgun/entities/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1325
=> [6.15.z] added properties for airgun

airgun/entities/host_new.py, airgun/views/host_new.py
changes added which will help to remove single ansible role from host.
=> added changes in host_new entities

.pre-commit-config.yaml, airgun/browser.py, airgun/exceptions.py, airgun/fixtures.py, airgun/navigation.py, airgun/session.py, docs/conf.py
updates:
- [github.com/psf/black: 24.3.0 → 24.4.0](https://github.com/psf/black/compare/24.3.0...24.4.0)
- [github.com/astral-sh/ruff-pre-commit: v0.3.5 → v0.3.7](https://github.com/astral-sh/ruff-pre-commit/compare/v0.3.5...v0.3.7)
fixes #1352
=> [6.14.z] pre-commit cherry-pick and formatting changes

.pre-commit-config.yaml, airgun/browser.py, airgun/exceptions.py, airgun/fixtures.py, airgun/navigation.py, airgun/session.py, docs/conf.py
updates:
[github.com/psf/black: 24.3.0 → 24.4.0](https://github.com/psf/black/compare/24.3.0...24.4.0)
[github.com/astral-sh/ruff-pre-commit: v0.3.5 → v0.3.7](https://github.com/astral-sh/ruff-pre-commit/compare/v0.3.5...v0.3.7)
fixes #1350
=> [6.13.z] pre-commit bumps and formatting changes

.pre-commit-config.yaml, airgun/browser.py, airgun/exceptions.py, airgun/fixtures.py, airgun/navigation.py, airgun/session.py, docs/conf.py
updates:
[github.com/psf/black: 24.3.0 → 24.4.0](https://github.com/psf/black/compare/24.3.0...24.4.0)
[github.com/astral-sh/ruff-pre-commit: v0.3.5 → v0.3.7](https://github.com/astral-sh/ruff-pre-commit/compare/v0.3.5...v0.3.7)
fixes #1351
=> [6.12.z] pre-commit bumps and formatting changes

airgun/views/hostgroup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1372
null
=> [6.13.z] Add pagination from ansible_roles tab in hostgroup create view

airgun/entities/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1347
changes added which will help to remove single ansible role from host.
=> [6.15.z] added changes in host_new entities

airgun/entities/host.py, airgun/views/host.py
For PR https://github.com/SatelliteQE/robottelo/pull/14986
=> Basic host statuses page

airgun/views/hostgroup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1372
null
=> [6.15.z] Add pagination from ansible_roles tab in hostgroup create view

airgun/entities/discoveredhosts.py, airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1397
null
=> [6.14.z] Enable root_password in discovered_host_edit_view

airgun/entities/discoveredhosts.py, airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1397
null
=> [6.15.z] Enable root_password in discovered_host_edit_view

airgun/entities/host_new.py, airgun/entities/hostgroup.py, airgun/views/host_new.py, airgun/views/hostgroup.py
Added new entities and views in hostgroup module for adding and removing ansible role for hostgroup.
Dependent PR:https://github.com/SatelliteQE/robottelo/pull/14672
=> added properties for hostgroup

airgun/entities/host_new.py, airgun/entities/hostgroup.py, airgun/views/host_new.py, airgun/views/hostgroup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1316
Added new entities and views in hostgroup module for adding and removing ansible role for hostgroup.
Dependent PR:https://github.com/SatelliteQE/robottelo/pull/14672
=> [6.14.z] added properties for hostgroup

airgun/entities/host_new.py, airgun/entities/hostgroup.py, airgun/views/host_new.py, airgun/views/hostgroup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1316
Added new entities and views in hostgroup module for adding and removing ansible role for hostgroup.
Dependent PR:https://github.com/SatelliteQE/robottelo/pull/14672
=> [6.15.z] added properties for hostgroup

airgun/entities/host_new.py, airgun/entities/hostgroup.py, airgun/views/host_new.py, airgun/views/hostgroup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1316
Added new entities and views in hostgroup module for adding and removing ansible role for hostgroup.
Dependent PR:https://github.com/SatelliteQE/robottelo/pull/14672
=> [6.16.z] added properties for hostgroup

airgun/entities/hostgroup.py, airgun/views/hostgroup.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1424
Add and remove functionality for ansible roles in hostgroup
:steps:
1. Import all roles available by default.
2. Assign ansible role while create a hostgroup
3. Assign ansible role after create a hostgroup
4. Remove previously added ansible roles from the hostgroup
:expectedresults: The Ansible Role is successfully add and remove to the hostgroup.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/14672
=> [6.14.z] adding and removing ansible role

airgun/entities/host_new.py, airgun/views/fact.py
1. Added module for Facts page and locator for the facts table.
2. Added a function in host entities to read host facts.
=> Add Facts View and add function to read host facts

airgun/entities/host_new.py, airgun/views/fact.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1427
1. Added module for Facts page and locator for the facts table.
2. Added a function in host entities to read host facts.
=> [6.14.z] Add Facts View and add function to read host facts

airgun/entities/host_new.py, airgun/views/fact.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1427
1. Added module for Facts page and locator for the facts table.
2. Added a function in host entities to read host facts.
=> [6.15.z] Add Facts View and add function to read host facts

airgun/entities/host_new.py, airgun/views/fact.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1427
1. Added module for Facts page and locator for the facts table.
2. Added a function in host entities to read host facts.
=> [6.13.z] Add Facts View and add function to read host facts

airgun/views/host.py
OUID changed in upstream PR https://github.com/theforeman/foreman_remote_execution/pull/876
=> Fix OUID for rex_pull_mode in host registration

airgun/entities/host_new.py, airgun/views/fact.py
Added entities.host_new.get_host_facts () to read nested value optionally. 
Related robottelo PR: https://github.com/SatelliteQE/robottelo/pull/14933
=> Update get_host_facts to read a nested value

.github/workflows/pull_request.yml
Pull Request checks on Python 3.12
=> PR checks for python 3.12

.github/workflows/pull_request.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1449
Pull Request checks on Python 3.12
=> [6.15.z] PR checks for python 3.12

.github/workflows/pull_request.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1449
Pull Request checks on Python 3.12
=> [6.14.z] PR checks for python 3.12

.github/workflows/pull_request.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1449
Pull Request checks on Python 3.12
=> [6.13.z] PR checks for python 3.12

airgun/entities/host_new.py, airgun/views/fact.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1437
Added entities.host_new.get_host_facts () to read nested value optionally. 
Related robottelo PR: https://github.com/SatelliteQE/robottelo/pull/14933
=> [6.15.z] Update get_host_facts to read a nested value

airgun/entities/host_new.py, airgun/views/fact.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1437
Added entities.host_new.get_host_facts () to read nested value optionally. 
Related robottelo PR: https://github.com/SatelliteQE/robottelo/pull/14933
=> [6.14.z] Update get_host_facts to read a nested value

airgun/entities/host_new.py, airgun/views/fact.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1437
Added entities.host_new.get_host_facts () to read nested value optionally. 
Related robottelo PR: https://github.com/SatelliteQE/robottelo/pull/14933
=> [6.13.z] Update get_host_facts to read a nested value

airgun/entities/host.py, airgun/views/host.py
Add support of new widget on Host Register page for adding multiple repositories
=> Add support of new widget on Host Register page for adding multiple repositories

airgun/views/computeresource.py, airgun/views/host.py
This locator helps to inherit the compute profile option.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/15488
=> Locator added in host view

.github/workflows/auto_cherry_pick_merge.yaml
Automerge is failing because of wait for status looking wrong Runner Context, This PR will fix that
=> making auto-merge should be same as master

airgun/views/computeresource.py, airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1439
This locator helps to inherit the compute profile option.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/15488
=> [6.15.z] Locator added in host view

airgun/views/computeresource.py, airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1439
This locator helps to inherit the compute profile option.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/15488
=> [6.14.z] Locator added in host view

airgun/views/hostgroup.py
Problem: Locator updated for activation key dropdown locator on Hostgroup create page
Fix: Updated activation key dropdown locator on Hostgroup create page
=> Update activation key dropdown locator on Hostgroup create page

airgun/entities/file.py, airgun/session.py, airgun/views/file.py
Adds Views/Entities for the Content -> Content Types -> File screen. 
Supporting this robottelo PR:
=> Add support for File page in Content section of UI

airgun/views/computeresource.py, airgun/views/host.py
Removed in upstream PR https://github.com/theforeman/foreman/pull/9963
=> Remove cpu_mode option from host and compute_profile view

airgun/entities/activationkey.py, airgun/entities/host_new.py, airgun/views/activationkey.py, airgun/views/host_new.py
Written some entities and views to schedule the Ansible job and fetch data from the configuration report log.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/15770
=> changes to fetch the config report data

airgun/entities/activationkey.py, airgun/entities/host_new.py, airgun/views/activationkey.py, airgun/views/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1479
Written some entities and views to schedule the Ansible job and fetch data from the configuration report log.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/15770
=> [6.14.z] changes to fetch the config report data

airgun/entities/all_hosts.py, airgun/entities/host_new.py, airgun/views/all_hosts.py, airgun/views/job_invocation.py
This Airgun PR adds coverage for the Manage Packages wizard. 
It is a new 6.16 feature with which users can manage packages.
This PR is needed by: https://github.com/SatelliteQE/robottelo/pull/15913
=> Add coverage for Manage Packages feature

airgun/entities/activationkey.py, airgun/entities/host_new.py, airgun/views/activationkey.py, airgun/views/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1479
Written some entities and views to schedule the Ansible job and fetch data from the configuration report log.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/15770
=> [6.15.z] changes to fetch the config report data

airgun/entities/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1442
updates:
- [github.com/psf/black: 24.4.2 → 24.8.0](https://github.com/psf/black/compare/24.4.2...24.8.0)
- [github.com/astral-sh/ruff-pre-commit: v0.4.9 → v0.5.7](https://github.com/astral-sh/ruff-pre-commit/compare/v0.4.9...v0.5.7)
=> [6.15.z] [pre-commit.ci] pre-commit autoupdate

airgun/entities/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1442
updates:
- [github.com/psf/black: 24.4.2 → 24.8.0](https://github.com/psf/black/compare/24.4.2...24.8.0)
- [github.com/astral-sh/ruff-pre-commit: v0.4.9 → v0.5.7](https://github.com/astral-sh/ruff-pre-commit/compare/v0.4.9...v0.5.7)
=> [6.14.z] [pre-commit.ci] pre-commit autoupdate

airgun/entities/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1442
updates:
- [github.com/psf/black: 24.4.2 → 24.8.0](https://github.com/psf/black/compare/24.4.2...24.8.0)
- [github.com/astral-sh/ruff-pre-commit: v0.4.9 → v0.5.7](https://github.com/astral-sh/ruff-pre-commit/compare/v0.4.9...v0.5.7)
=> [6.13.z] [pre-commit.ci] pre-commit autoupdate

airgun/entities/job_invocation.py, airgun/views/job_invocation.py
Cherry-pick of https://github.com/SatelliteQE/airgun/pull/1515
New view and navigation was added for the first part of the new job invocation details page.
This feature is still an experimantal feature/tech preview and it is not yet fully completed.
Other content will be added in later phases.
=> [6.16.z] New job invocation details page

airgun/entities/all_hosts.py, airgun/views/all_hosts.py
1 small addition to @LadislavVasina1's excellent work.
=> [6.16] All Hosts Manage Errata

airgun/entities/host.py, airgun/views/host.py
Adds support for the "New UI" button on the old Hosts page.
Supporting: https://github.com/SatelliteQE/robottelo/pull/16113
=> [6.16] Add support for the new ui button

airgun/entities/host.py, airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1536
Adds support for the "New UI" button on the old Hosts page.
Supporting: https://github.com/SatelliteQE/robottelo/pull/16113
=> [6.16.z] [6.16] Add support for the new ui button

airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1544
null
=> [6.15.z] Fix sattable locators

airgun/views/filter.py
the id got updated some time ago
=> override checkbox id updated in filters

airgun/views/filter.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1547
the id got updated some time ago
=> [6.16.z] override checkbox id updated in filters

airgun/views/filter.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1547
the id got updated some time ago
=> [6.15.z] override checkbox id updated in filters

airgun/entities/dashboard.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1556
similar to https://github.com/SatelliteQE/airgun/pull/1555
=> [6.16.z] wait for a dashboard card to load

airgun/entities/hostcollection.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1563
This PR fixes timing issues that are happening while running Install package action on some hostCollection.
Needed by: https://github.com/SatelliteQE/robottelo/pull/16322
=> [6.16.z] Fix hostCollection airgun entities

airgun/views/job_invocation.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1463
Dependant PR https://github.com/SatelliteQE/robottelo/pull/15595
=> [6.15.z] Add ansible_collections_path in job invocation advanced_fields

airgun/views/report_template.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1539
Adding Installability views to the ReportTemplateGenerateView Class
=> [6.15.z] [Comp Eval] Add installability to generate views

airgun/entities/package.py, airgun/views/package.py
CC Automation SAT-26967
Related robottelo PR - https://github.com/SatelliteQE/robottelo/pull/16641
=> add airgun support for parsing package details page link

airgun/views/common.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1649
Required by https://github.com/SatelliteQE/robottelo/pull/17091
=> [6.16.z] Template editor error widget

airgun/views/common.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1649
Required by https://github.com/SatelliteQE/robottelo/pull/17091
=> [6.14.z] Template editor error widget

.pre-commit-config.yaml, airgun/views/contentviewfilter.py, airgun/views/redhat_repository.py, airgun/widgets.py, pyproject.toml
=> [6.13.z] [pre-commit.ci] pre-commit autoupdate (#1645)

.pre-commit-config.yaml, airgun/views/contentviewfilter.py, airgun/views/redhat_repository.py, airgun/widgets.py, pyproject.toml
Backports https://github.com/SatelliteQE/airgun/pull/1645
=> [6.14.z] [pre-commit.ci] pre-commit autoupdate (#1645)

.github/dependabot.yml, setup.py
Related: https://github.com/SatelliteQE/robottelo/pull/17166
=> Revert selenium bump and ignore it by dependabot.

setup.py
Related: https://github.com/SatelliteQE/robottelo/pull/17166
=> Revert selenium dependency bump.

.github/dependabot.yml, setup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1668
Related: https://github.com/SatelliteQE/robottelo/pull/17166
=> [6.16.z] Revert selenium bump and ignore it by dependabot.

airgun/entities/job_invocation.py, airgun/views/job_invocation.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1677
Add view for leapp preupgrade remidiation.
Robottelo PR: https://github.com/SatelliteQE/robottelo/pull/17180
=> [6.16.z] Add leapp preupgrade remidiation view

airgun/entities/eol_banner.py, airgun/views/eol_banner.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1644
Need to test the link validity
=> [6.14.z] check links in EOL banner

airgun/entities/eol_banner.py, airgun/views/eol_banner.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1644
Need to test the link validity
=> [6.15.z] check links in EOL banner

airgun/entities/eol_banner.py, airgun/views/eol_banner.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1644
Need to test the link validity
=> [6.16.z] check links in EOL banner

airgun/entities/user.py, airgun/views/user.py
Related Feature: SAT-27385 
Related robottelo PR: https://github.com/SatelliteQE/robottelo/pull/17465
=> Add support to invalidate users JSON Web Tokens

airgun/views/computeresource.py, airgun/views/host.py, airgun/widgets.py
The FilteredDropdown locator has changed, affecting multiple tests. Therefore, I have updated the locator accordingly.
=> update FilteredDropdown locator in widgets

airgun/views/common.py
This PR changes the locator that has been changed and fixes one test
```
pytest: tests/foreman/ui/test_reporttemplates.py::test_positive_end_to_end
```
=> Change TemplateInputItem

airgun/views/common.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1751
This PR changes the locator that has been changed and fixes one test
```
pytest: tests/foreman/ui/test_reporttemplates.py::test_positive_end_to_end
```
=> [6.17.z] Change TemplateInputItem

airgun/views/capsule.py, airgun/views/computeresource.py, airgun/views/host.py, airgun/views/hostgroup.py, airgun/views/oscappolicy.py, airgun/views/partitiontable.py, airgun/views/report_template.py, airgun/views/usergroup.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1750
Some locators have changed after the jQuery3 update, so update the locators accordingly to ensure the test functions correctly.
=> [6.17.z] remove s2id from the locator

airgun/views/os.py
Update the locator to retrieve the value from the operating system template.
=> fix TemplatesList locator to fetch value

airgun/entities/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1749
updates:
- [github.com/astral-sh/ruff-pre-commit: v0.9.6 → v0.11.0](https://github.com/astral-sh/ruff-pre-commit/compare/v0.9.6...v0.11.0)
=> [6.17.z] [pre-commit.ci] pre-commit autoupdate

airgun/entities/host_new.py, airgun/views/host_new.py
Simple PR, supporting the last bootc robottelo PR : 
Leaving the comment in about the bootc card until we get a fix from dev.
Edit: https://issues.redhat.com/browse/SAT-31814 - issue to fix the bootc card
=> Add entity to run bootc REX jobs, and add view for bootc card

airgun/entities/host_new.py, airgun/views/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1757
Simple PR, supporting the last bootc robottelo PR : 
Leaving the comment in about the bootc card until we get a fix from dev.
Edit: https://issues.redhat.com/browse/SAT-31814 - issue to fix the bootc card
=> [6.17.z] Add entity to run bootc REX jobs, and add view for bootc card

airgun/views/user.py
users table: added column 'Last login time'
=> users: Last login time column added

airgun/views/user.py
users table: added column 'Last login time'
=> [6.17.z] users: Last login time column added

airgun/entities/job_invocation.py, airgun/views/host.py, airgun/views/job_invocation.py
This PR is another batch of PF4-PF5 fixes, this particular one fixes `test_change_content_source`
=> Fix_ChangeContentSource

airgun/views/cloud_insights.py, airgun/views/common.py, airgun/views/host_new.py
Update Patternfly4 -> Patternfly5 locators for Insights views
Required by: https://github.com/SatelliteQE/robottelo/pull/18133
PRT test results are in that PR.
=> Insights patternfly 5 updates

airgun/entities/cloud_inventory.py, airgun/views/cloud_inventory.py
This PR adds some helper entities used in https://github.com/SatelliteQE/robottelo/pull/18259 and updates some views.
PRT runs in the robottelo PR.
=> Add helper entites for RH inventory

airgun/entities/job_invocation.py, airgun/views/job_invocation.py
=> pf5 related adjustments for rex

airgun/entities/cloud_inventory.py
This PR is needed for this robottelo PR as a feature extension: https://github.com/SatelliteQE/robottelo/pull/18319
PRT Passed in https://github.com/SatelliteQE/robottelo/pull/18319
=> Get displayed Inventory tabs entity

airgun/views/common.py
=> user info dropdown to PF5

airgun/entities/cloud_inventory.py, airgun/views/cloud_inventory.py
Just a small alteration of the view and entity for cloud_inventory.
Needed by: https://github.com/SatelliteQE/robottelo/pull/18374
=> CloudInventory Fixes

airgun/entities/host_new.py, airgun/views/host_new.py
Adding new entity that reads tracer tab title, and fixing some tracer views.
Needed by https://github.com/SatelliteQE/robottelo/pull/18392
=> Tracer Fixes and new entity

airgun/views/cloud_inventory.py
views for minimal data collections
=> [RFE] Add functionality for minimal data collection report

airgun/views/host.py, airgun/widgets.py
Updated the locator that was broken after the PF5 changes
=> update locator due to change of pf5

airgun/entities/contentview_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1763
Updates publish entity to support multi environment promote.
Supports: https://github.com/SatelliteQE/robottelo/pull/17949
=> [6.17.z] Add multi promote support to publish/promote entity

airgun/entities/contentview_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1763
Updates publish entity to support multi environment promote.
Supports: https://github.com/SatelliteQE/robottelo/pull/17949
=> [6.16.z] Add multi promote support to publish/promote entity

airgun/views/cloud_inventory.py
tests.foreman.ui.test_rhc.test_positive_configure_cloud_connector  was failing due to use of old PF4 locator. Updating to PF5
=> Add dialog view to cloud inventory

airgun/entities/cloud_insights.py, airgun/entities/cloud_inventory.py, airgun/views/cloud_insights.py, airgun/views/cloud_inventory.py, airgun/views/host.py
=> Update insights to lightspeed select and locators

airgun/entities/host_new.py, airgun/views/host_new.py
Removes a comment added earlier to work around pagination not working, as well as fixes the pagination widget to work properly. 
Should fix a fair few tests.
=> Slightly rework pagination widget to work

setup.py
Manual cherrypick of https://github.com/SatelliteQE/airgun/pull/2050
=> [6.17.z] limit widgetastic core version

setup.py
Manual cherrypick of https://github.com/SatelliteQE/airgun/pull/2050
=> [6.16.z] limit widgetastic core version 

.pre-commit-config.yaml, airgun/entities/contentview.py, airgun/entities/contentviewfilter.py, airgun/entities/host.py, airgun/views/capsule.py, airgun/views/cloud_inventory.py, airgun/views/hostcollection.py, airgun/views/job_invocation.py, airgun/views/subscription.py, airgun/widgets.py, pyproject.toml
Manual cherrypick of https://github.com/SatelliteQE/airgun/pull/2090
=> [6.18.z] Drop Black and use just Ruff & Single Quotes Rule Added for Ruff 

.pre-commit-config.yaml, airgun/entities/contentview.py, airgun/entities/contentviewfilter.py, airgun/entities/host.py, airgun/views/acs.py, airgun/views/capsule.py, airgun/views/hostcollection.py, airgun/views/subscription.py, airgun/widgets.py, pyproject.toml
Manual cherrypick of https://github.com/SatelliteQE/airgun/pull/2090
=> [6.17.z] Drop Black and use just Ruff & Single Quotes Rule Added for Ruff 

airgun/entities/discoveryrule.py
Add fix for test_positive_list_host_based_on_rule_search_query
=> Add New changes to read hosts if new UI is available

airgun/entities/host_new.py
Make `test_positive_update_delete_package` more stable.
PRT runs in https://github.com/SatelliteQE/robottelo/pull/19788
=> more stable get_packages

airgun/views/host.py
Adding a check module for Libvirt in the OS.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/19225
=> Add_provision_method_check_for_Libvirt

airgun/entities/discoveryrule.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/2094
Add fix for test_positive_list_host_based_on_rule_search_query
=> [6.18.z] Add New changes to read hosts if new UI is available
