airgun/entities/activationkey.py, airgun/views/activationkey.py, airgun/views/common.py, airgun/widgets.py
```python
pytest -v tests/foreman/ui_airgun/test_activationkey.py -k test_negative_usage_limit
platform darwin -- Python 3.6.4, pytest-3.3.2, py-1.5.2, pluggy-0.6.0 -- /Users/andrii/workspace/py3a/bin/python3.6
cachedir: .cache
plugins: wait-for-1.0.9, xdist-1.22.0, services-1.2.1, mock-1.6.3, forked-0.2
collected 6 items
2018-03-23 15:30:47 - conftest - DEBUG - BZ deselect is disabled in settings
tests/foreman/ui_airgun/test_activationkey.py::test_negative_usage_limit PASSED [100%]
============================== 5 tests deselected ==============================
=================== 1 passed, 5 …
```
=> Introduced EditableLimitableEntry widget

airgun/views/activationkey.py, airgun/views/common.py, airgun/widgets.py
Verified with following test (from #51):
```python
def test_alex(session):
import random
ak_name = gen_string('alpha')
org = entities.Organization().create()
envs_list = ['STAGING', 'DEV', 'IT', 'UAT', 'PROD']
for name in envs_list:
entities.LifecycleEnvironment(name=name, organization=org).create()
env_name = random.choice(envs_list)
cv = entities.ContentView(organization=org).create()
cv.publish()
promote(
cv.read().version[0],
entities.LifecycleEnvironment(name=env_name).search()[0].id
)
with session:
session.organization.select(org_name=org.name)
session.activationkey.create({
'name': ak_name,
'lce': {env_name: True},
'content_view': cv.name
})
assert session.activationkey.read(name)['lce'][env_name][env_name]
```
Test results:
```python
Testing started at 3:06 PM ... …
```
=> Added LCESelectorGroup view

airgun/views/activationkey.py, airgun/views/common.py
```python
pytest -v tests/foreman/ui_airgun -k test_positive_create_with_envs
platform darwin -- Python 3.6.4, pytest-3.3.2, py-1.5.2, pluggy-0.6.0 -- /Users/andrii/workspace/py3a/bin/python3.6
cachedir: .cache
plugins: wait-for-1.0.9, xdist-1.22.0, services-1.2.1, mock-1.6.3, forked-0.2
collected 22 items
2018-04-04 15:31:45 - conftest - DEBUG - BZ deselect is disabled in settings
tests/foreman/ui_airgun/test_activationkey.py::test_positive_create_with_envs[alpha] PASSED [100%]
============================= 21 tests deselected ==============================
================== 1 passed, 21 deselected …
```
=> Fixed AK subscriptions view; introduced AddRemoveSubscriptionsView

airgun/entities/activationkey.py, airgun/entities/contentview.py, airgun/entities/hostcollection.py, airgun/entities/syncplan.py, airgun/entities/template.py, airgun/views/activationkey.py, airgun/views/contentview.py, airgun/views/syncplan.py, airgun/views/template.py, airgun/widgets.py
```python
pytest -v tests/foreman/ui_airgun/{test_activationkey.py,test_provisioningtemplate.py} -k 'test_positive_delete or test_positive_clone'
platform darwin -- Python 3.6.4, pytest-3.4.0, py-1.5.3, pluggy-0.6.0 -- /Users/andrii/workspace/py3a/bin/python3.6
plugins: wait-for-1.0.9, xdist-1.22.0, services-1.2.1, mock-1.6.3, forked-0.2
collected 27 items
2018-04-24 19:18:46 - conftest - DEBUG - BZ deselect is disabled in settings
tests/foreman/ui_airgun/test_activationkey.py::test_positive_delete PASSED [ 20%]
tests/foreman/ui_airgun/test_activationkey.py::test_positive_delete_ …
```
=> Added generic ActionsDropdown widget for actions lists

setup.py
Fixing conflicting pinning of airgun and robottelo:
```
airgun 0.0.1 has requirement pytest==3.3.2, but you'll have pytest 3.4.0 which is incompatible
```
=> Pin pytest==3.4.0 (same as robottelo)

airgun/entities/architecture.py, airgun/entities/computeprofile.py, airgun/entities/hostcollection.py, airgun/entities/os.py, airgun/entities/partitiontable.py, airgun/entities/subnet.py, airgun/entities/template.py, airgun/entities/user.py, airgun/navigation.py, airgun/views/activationkey.py, airgun/views/architecture.py, airgun/views/computeprofile.py, airgun/views/contentcredential.py, airgun/views/contentview.py, airgun/views/hostcollection.py, airgun/views/lifecycleenvironment.py, airgun/views/organization.py, airgun/views/os.py, airgun/views/partitiontable.py, airgun/views/product.py, airgun/views/subnet.py, airgun/views/syncplan.py, airgun/views/template.py, airgun/views/user.py, airgun/widgets.py, setup.py
Summary of changes:
* Used breadcrumb widget in navigate step to determine current entity
* Used breadcrumb widget in view's is_displayed for more precise view recognition
* Update for Progressbar widget to avoid default timeout when checking for page save, as it turns out in some rare cases ensure_page_save recognizes page isn't fully loaded when progress bar is active (however in most places it doesn't)
* Small fixes for numerous views, such as adding details tab, dividing 'detailsView' into separate create/edit views etc
=> Navigation overhaul; support breadcrumb widget to determine current view

airgun/browser.py
Closes #93 
Parametrized tests have suffix with square brackets `[ ]` which we should get rid off when creating docker containers named after test name.
=> Removed square brackets from docker container names

airgun/entities/domain.py, airgun/session.py, airgun/views/domain.py, airgun/views/os.py, airgun/widgets.py
* Add views, entity, navigation for Infrastructure -> Domains
* Add `set_assigned` method to `MultiSelect` widget
* Change `CustomParameter` to inherit from `Table` widget so that its easier to repeatedly add values to the param list and read from each row. Update `OperatingSystemDetailsView` to pass in `id` when invoking `CustomParameter`
* Add `wait_for` to requirements, since its now being used in the `DomainEntity` CRUD methods
=> Add domain views/entities and tweak MultiSelect/CustomParameter widgets

airgun/browser.py, airgun/entities/domain.py, airgun/entities/repository.py, airgun/settings.py, airgun/views/product.py, airgun/views/repository.py, airgun/widgets.py, docs/conf.py
Summary of changes:
* Fixed issue with taxonomies list hovering page when scrolling bottom-up (see screenshot)
* Removed flooding `selenium.webdriver.remote.remote_connection` messages from debug level which are redundant in 99% cases and were only useful on the earliest stages of development
* Fixed issue with `EditableEntry` widget when it wasn't able to fetch value of entries with similar names (e.g. 'publish via http' because of 'publish via https' present) due to `contains()` nature
* Added helpers, views and widgets for Repository's Packages and Puppet Modules
=> Fixed issue with scrolling to elements; Improved logging; Repository helpers, views and widgets

airgun/views/domain.py, airgun/views/puppet_environment.py
Per https://github.com/theforeman/foreman/pull/5712#issuecomment-409193625 request
```python
pytest tests/foreman/ui_airgun/test_domain.py -k test_positive_create_with_name
platform darwin -- Python 3.6.4, pytest-3.4.0, py-1.5.3, pluggy-0.6.0
plugins: wait-for-1.0.9, xdist-1.22.0, services-1.2.1, mock-1.6.3, forked-0.2, env-0.6.2
collected 9 items
2018-08-02 20:08:34 - conftest - DEBUG - BZ deselect is disabled in settings
tests/foreman/ui_airgun/test_domain.py .                                 [100%]
============================== 8 tests deselected ==============================
=================== 1 …
```
=> Avoid using data-id attr in locators

airgun/entities/discoveryrule.py, airgun/session.py, airgun/views/discoveryrule.py
and just creation to host group entity
I have to finish Correct Discovered Hosts redirection and Correct Hosts redirection and search. 
And I have some questions about it. Can you please help with it ? @oshtaier 
1.How to make these redirection in entity ? Can you send me some example where else it has been done in project.
And I have some another questions related to tests.  [https://github.com/SatelliteQE/robottelo/pull/6131](url)
2. I don't know how to create a Host() neither in satellite directly or in tests, so how can I create the host with specific organization in test ? Yes I saw you create the fakehost in host_test but I tried to use your fakehost method but it didn't goes well.
3. Is there a way how to make my tests shorter with using `entities.NameOfEntity().create()` instead …
=> adding basic logic to discovery rule entity

airgun/browser.py
- remote webdriver doesn't work without `desired_capabilities`;
- navigation to Insights page caused the error in  `ENSURE_PAGE_SAFE` script
=> Fixed ENSURE_PAGE_SAFE script

airgun/browser.py
It seems changes in #175 were not enough. Airgun doesn't wait for the page loading in RHAI pages. I tried the solution from https://stackoverflow.com/a/13402028 and now `ENSURE_PAGE_SAFE` works as expected on RHAI pages.
=> Fixed angular pending requests in ENSURE_PAGE_SAFE script

airgun/browser.py
Some pages (Subscriptions and Red Hat Repositories for certain, maybe some others as well) use new react-based spinner widget. Our ensure_page_safe function did not take it into account and tried to proceed with automation even if page was not ready yet.
Function looks for element with class `loading-state` inside div with id `reactRoot`. That element is on page only when content is being loaded, i.e. it is removed from source on finish (instead of merely making it invisible). `reactRoot` is not present on other pages at all, so function will always return true on them.
=> Add react spinner to ENSURE_PAGE_SAFE

airgun/browser.py
Workaround for edge was also applied on chrome browser; resulting in error:
`selenium.common.exceptions.WebDriverException: Message: unknown error: unsupported protocol`
=> Fix edge workaround applied on chrome

airgun/entities/discoveryrule.py, airgun/views/discoveryrule.py
Actions column name is not present till now and we need this implementation to work properly. 
Autocomplete list was hiding next widgets
```
(robottelo) dlezz@dlezz:~/projects/robottelo-fork$ pytest -v tests/foreman/ui_airgun/test_discoveryrule.py 
platform linux -- Python 3.6.6, pytest-3.6.1, py-1.5.4, pluggy-0.6.0 -- /home/dlezz/.pyenv/versions/3.6.6/envs/robottelo/bin/python
shared_function enabled - ON - scope: ffff - storage: file
plugins: wait-for-1.0.9, xdist-1.22.5, services-1.2.1, mock-1.10.0, forked-0.2, cov-2.5.1
collecting 9 items …
```
=> Fix Discovery Rules entity

setup.py
test hosts entity
```
(robottelo) dlezz@dlezz:~/projects/robottelo-fork$ pytest -v tests/foreman/ui_airgun/test_host.py
=========================================== test session starts ===========================================
platform linux -- Python 3.6.6, pytest-3.6.1, py-1.5.4, pluggy-0.6.0 -- /home/dlezz/.pyenv/versions/3.6.6/envs/robottelo/bin/python
shared_function enabled - ON - scope: ffff - storage: file
plugins: wait-for-1.0.9, xdist-1.22.5, services-1.2.1, mock-1.10.0, forked-0.2, cov-2.5.1
collecting 9 items                                                                                        2018-10-04 10:09:09 - conftest - DEBUG - BZ deselect is disabled in settings
collected 9 items …
```
=> change widgetastic versions

airgun/entities/subscription.py, airgun/session.py, airgun/views/subscription.py, airgun/widgets.py
I started working on Content -> Subscriptions, but it turned out to be more complex than I initially thought. Airgun side that covers adding and removing manifest is in this push request, but I would like to raise some questions before I move forward:
1. When deleting manifest, at one point there are three buttons labeled "Delete" on one page - one above the main table, one in Manage Manifest popup and one in final confirmation popup. It seems that `DeleteManifestConfirmation.delete_button` refers to some other button than the one it should, which is probably caused by my locators not being specific enough.
How can I ensure that correct button is selected? These popups don't have ids and all look about the same, with only difference being in title. My Xpath expressions start with dot, …
=> [WIP] Red Hat Subscriptions

airgun/views/common.py, airgun/views/contentviewfilter.py
Fixes regression in AddRemoveSubscriptionsView introduced by #211 (it was not refactored according to AddRemoveResourcesView changes)
Test results:
```python
pytest -v tests/foreman/ui_airgun/test_activationkey.py -k test_positive_add_rh_product
platform darwin -- Python 3.6.4, pytest-3.6.1, py-1.6.0, pluggy-0.6.0 -- /Users/andrii/workspace/py3a/bin/python3.6
plugins: xdist-1.22.0, services-1.2.1, mock-1.10.0, forked-0.2, env-0.6.2
collecting 23 items                                                            2018-10-18 14:10:28 - conftest - DEBUG - BZ deselect is disabled in …
```
=> Fix AddRemoveSubscriptionsView

.flake8
spreading max-line-length = 99 across team's repositories
See SatelliteQE/robottelo#6344
=> E501: Allow longer lines

airgun/views/common.py, airgun/widgets.py
```bash
(robottelo) dlezz@dlezz:~/projects/robottelo-fork$ pytest -v tests/foreman/ui_airgun/test_contentview.py::test_positive_end_to_end
============================================= test session starts =============================================
platform linux -- Python 3.6.6, pytest-3.6.1, py-1.5.4, pluggy-0.6.0 -- /home/dlezz/.pyenv/versions/3.6.6/envs/robottelo/bin/python
shared_function enabled - ON - scope: ffff - storage: file
plugins: wait-for-1.0.9, xdist-1.22.5, services-1.3.0, mock-1.10.0, forked-0.2, cov-2.5.1
collecting 1 item                                                                                             2018-11-08 17:51:35 - conftest - DEBUG - BZ deselect is disabled in settings …
```
=> Fix 6.5 menu Nav and alert text locators

airgun/entities/discoveryrule.py, airgun/views/discoveryrule.py
```
py.test -v /home/ashtayer/Desktop/robottelo/tests/foreman/ui_airgun/test_discoveryrule.py -k delete_rule
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.6.5, pytest-3.4.0, py-1.5.3, pluggy-0.6.0 -- /usr/bin/python3.6
rootdir: /home/ashtayer/Desktop/robottelo, inifile:
plugins: services-1.2.1, mock-1.6.3
collected 5 items                                                                                                                                                                            
2018-11-27 17:49:34 - conftest - DEBUG - BZ …
```
=> Discovery Rule column PR finally get into downstream

airgun/views/contentviewfilter.py, airgun/widgets.py, docs/conf.py, setup.py
Test results:
```python
pytest -v tests/foreman/ui_airgun/test_contentview.py -k 'test_positive_add_package_filter or test_positive_update_inclusive_filter_package_version or test_positive_update_filter_affected_repos'
============================== test session starts ===============================
platform darwin -- Python 3.6.4, pytest-3.6.1, py-1.6.0, pluggy-0.6.0 -- /Users/andrii/workspace/py3a/bin/python3.6
plugins: xdist-1.22.0, services-1.2.1, mock-1.10.0, forked-0.2, env-0.6.2
collecting 38 items                                                              2018-12-06 12:48:48 - conftest - DEBUG - BZ deselect is disabled in settings
collected 38 …
```
=> Fixed issues with content view filter rule table

airgun/views/contentviewfilter.py, airgun/widgets.py, docs/conf.py, setup.py
* Fixed issues with content view filter rule table
* added widgetastic's table reference to doc exceptions list
* resolves issues with 6.4.z content credential tests (closes SatelliteQE/robottelo#6531)
Test results:
```python
pytest tests/foreman/ui_airgun/test_contentcredential.py
============================== test session starts ===============================
platform darwin -- Python 3.6.4, pytest-3.6.1, py-1.6.0, pluggy-0.6.0
plugins: xdist-1.22.0, services-1.2.1, mock-1.10.0, forked-0.2, env-0.6.2
collecting 16 items                                                              2018-12-10 16:21:48 - conftest - DEBUG - BZ deselect is disabled in settings
collected 16 items …
```
=> [6.4.z] Fixed issues with content view filter rule table (#253)

airgun/browser.py
before change
```
(robottelo) dlezz@dlezz:~/projects/robottelo-fork$ pytest -v tests/foreman/ui_airgun/test_product.py::test_positive_end_to_end 
platform linux -- Python 3.6.6, pytest-4.0.1, py-1.5.4, pluggy-0.8.0 -- /home/dlezz/.pyenv/versions/3.6.6/envs/robottelo/bin/python
shared_function enabled - ON - scope: ffff - storage: redis
plugins: wait-for-1.0.9, xdist-1.22.5, services-1.3.1, mock-1.10.0, forked-0.2, cov-2.5.1
collecting ... 2018-12-12 12:29:38 - conftest - DEBUG - BZ deselect is disabled in settings …
```
=> Fixes chrome_options warning

airgun/views/errata.py
Affected packages were moved to a separate tab:
=> Added 'Packages' tab to Errata details view

airgun/entities/product.py, airgun/views/product.py
**Objective** 
1. Creating and checking whether sync plan create set from product create page 
2. As this really something only can check from UI only, depending test will be added soon in Robottelo   
**Test Result**
https://github.com/SatelliteQE/robottelo/pull/6556#event-2031042920
=> Adding Support to create sync plan from product page for some test

airgun/entities/contenthost.py
```python
pytest -v tests/foreman/ui_airgun/test_contenthost.py -k end_to_end
============================== test session starts ===============================
platform darwin -- Python 3.6.4, pytest-3.6.1, py-1.6.0, pluggy-0.6.0 -- /Users/andrii/workspace/py3a/bin/python3.6
plugins: xdist-1.22.0, services-1.2.1, mock-1.10.0, forked-0.2, env-0.6.2
collecting 11 items                                                              2018-12-28 19:32:41 - conftest - DEBUG - BZ deselect is disabled in settings
collected 11 items / 10 deselected
tests/foreman/ui_airgun/test_contenthost.py::test_positive_end_to_end PASSED [100%]
=================== 1 passed, 10 …
```
=> Added content host update method

airgun/entities/contentview.py, airgun/entities/host.py, airgun/utils.py, airgun/views/common.py
In order to read only the widgets that we need for an entity:
Suppose we have this tests
```python
from nailgun import entities
def test_positive_read_host_details_page(session):
host = entities.Host(id=20).read()
os = host.operatingsystem.read()
domain = host.domain.read()
org = host.organization.read()
loc = host.location.read()
env = host.environment.read()
arch = host.architecture.read()
os_name = u'{0} {1}'.format(os.name, os.major)
host_name = host.name
with session:
session.organization.select(org_name=org.name)
session.location.select(loc_name=loc.name)
assert session.host.search(host_name)[0]['Name'] == host_name
values = session.host.get_details(
host_name, ['properties.properties_table'])
print('???????????????????????')
print(values)
print('???????????????????????')
assert …
```
=> Implement read widgets by names in Base view

airgun/entities/contentview.py, airgun/entities/lifecycleenvironment.py, airgun/entities/modulestream.py, airgun/session.py, airgun/views/contentview.py, airgun/views/lifecycleenvironment.py, airgun/views/modulestream.py
**Objective** 
Adding support for elements added for module streams UI 
**Test Result:** 
```
(env) root@okhatavk robottelo (module_streams_ui_tests) $ pytest tests/foreman/ui_airgun/ -v -k 'module_stream' 
============================================================================ test session starts ============================================================================
platform linux -- Python 3.4.8, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- /home/okhatavk/Satellite/robottelo/env/bin/python3.4
rootdir: /home/okhatavk/Satellite/robottelo, inifile:
plugins: xdist-1.24.1, services-1.3.1, mock-1.10.0, forked-0.2, cov-2.6.0
collecting 189 items …
```
=> Adding support for module streams ui

airgun/views/job_invocation.py
The test was failing in automation (locally also) with
```
raise NoSuchElementException(
>                   'Failed waiting for element with {} in {}'.format(locator, parent))
E               selenium.common.exceptions.NoSuchElementException: Message: Failed waiting for element with TextInput(locator=".//input[contains(@name, '[effective_user]')]") in None
```
seems some base/framework changes was made since test creation
```
(robottelo) dlezz@dlezz:~/projects/robottelo-fork$ pytest -v tests/foreman/ui_airgun/test_hostcollection.py::test_negative_install_via_custom_remote_execution 
platform linux -- Python 3.6.6, pytest-4.0.2, py-1.5.4, pluggy-0.8.0 -- …
```
=> Fixes job invocation view

airgun/browser.py
Force the timeout for saucelabs remote connection/request, this has effect only with latest selenium 3.141.0 (as only in this version the timeout is passed to urllib3.PoolManager)
We found this working, as tested with value 10 seconds and 60 seconds with computeresource end_to_end test.
Note: This PR is also working with the selenium version currently used in robottelo (but has  no effect on  connection/request timeout).
=> Fixes saucelabs remote connection/request timeout

airgun/exceptions.py, airgun/widgets.py
test output with regular tests
```
(robottelo) dlezz@dlezz:~/projects/robottelo-fork$ pytest -v tests/foreman/ui_airgun/test_computeresource.py::test_positive_end_to_end 
platform linux -- Python 3.6.6, pytest-4.0.2, py-1.5.4, pluggy-0.8.0 -- /home/dlezz/.pyenv/versions/robottelo/bin/python3.6
shared_function enabled - ON - scope: ffff - storage: redis
plugins: xdist-1.26.0, timeout-1.3.3, services-1.3.1, mock-1.10.0, forked-0.2, cov-2.6.1
collecting ... 2019-02-21 15:29:22 - conftest - DEBUG - BZ deselect is disabled in settings
collected 2 items …
```
=> Implement Table read with pagination

airgun/entities/hostgroup.py
This reverts commit a0a95fc8b5c0b13b06925a507818e376b8063b09.
The commit has been a workaround for bz1652677 which has now been fixed.
=> Revert "In the vertical menu, "Host Groups" has been changed to "Host Group" (#244)"

setup.py
This is a hotfix version for rowspan issue https://github.com/RedHatQE/widgetastic.core/issues/143
=> Update widgetastic version

airgun/entities/host.py
given the test bellow
```python
def test_satellite_ansible_install(satellite_ansible_vm, session):
"""Install insights client from satellite by applying the ansible role on host.
Steps:
1. Ensure "RedHatInsights.insights-client" role is imported in Configure > Ansible roles
2. Ensure VM client host registered to satellite, the needed repos for installing insights
client are enabled and host accessible from satellite via ssh.
3. Goto All hosts and edit the vm client host, in Ansible roles tab
add "RedHatInsights.insights-client" and press submit.
4. in All hosts select the vm client host and select "Play Ansible roles" action
expected results:
1. insights client installed on host
2. host registered
3. host listed in insights inventory
"""
session.host.update(satellite_ansible_vm.hostname, …
```
=> Fixes host entity with Play Ansible roles action

airgun/entities/host.py, airgun/views/host.py, airgun/views/job_invocation.py
Back port of https://github.com/SatelliteQE/airgun/pull/318 to 6.4.z
```
pytest -v iqe_insights_satellite/tests/test_ansible.py::test_satellite_ansible_install 
⚠️ WARNING: Package iqe-integration-tests  is at version 0.9.3.dev9+g331d6ad, latest 0.9.8
⚠️ WARNING: Package iqe-self-service-portal-plugin  is at version 0.0.3, latest 1.0.0
⚠️ WARNING: Package iqe-insights-satellite-plugin  is at version 0.1.1.dev2+ge9acc37.d20190405, latest 0.1.2
platform linux -- Python 3.6.6, pytest-4.3.0, py-1.8.0, pluggy-0.9.0 -- /home/dlezz/.pyenv/versions/3.6.6/envs/insights/bin/python
metadata: {'Python': '3.6.6', 'Platform': …
```
=> 6.4.z Fixes Hosts Play Ansible roles

airgun/entities/contenthost.py, airgun/entities/hostcollection.py, airgun/entities/job_invocation.py, airgun/views/contenthost.py, airgun/views/hostcollection.py, airgun/views/job_invocation.py, airgun/widgets.py
UI elements and method added to support search and actions done on module streams from Host UI Page. 
```
(env) [root@okhatavk robottelo]# pytest tests/foreman/ui_airgun/test_contenthost.py -v -k "modu"
platform linux -- Python 3.4.8, pytest-4.0.2, py-1.7.0, pluggy-0.9.0 -- /home/okhatavk/Satellite/robottelo/env/bin/python3.4
rootdir: /home/okhatavk/Satellite/robottelo, inifile:
plugins: xdist-1.26.1, services-1.3.1, mock-1.10.0, forked-1.0.2, cov-2.6.1
collecting 15 items                                                                                               2019-04-18 18:32:23 - conftest …
```
=> Adding support to module streams actions on host page

airgun/views/host.py
Without this fix, Robottelo test `tests/foreman/ui/test_host.py::test_positive_inherit_puppet_env_from_host_group_when_action` fails with:
```
session = <airgun.session.Session object at 0x7f0f8d54b198>
@tier3
def test_positive_inherit_puppet_env_from_host_group_when_action(session):
"""Host group puppet environment is inherited to already created
host when corresponding action is applied to that host
:id: 3f5af54e-e259-46ad-a2af-7dc1850891f5
:customerscenario: true
:expectedresults: Expected puppet environment is inherited to the host
:BZ: 1414914
:CaseLevel: System
"""
org = entities.Organization().create()
loc = entities.Location().create()
host = entities.Host(organization=org, location=loc).create()
env = entities.Environment(
organization=[org], location=[loc]).create()
hostgroup = …
```
=> In Sat 6.6 onclick content is different

airgun/browser.py, airgun/settings.py, settings.ini.example
As discussion before, this PR will:
1). move remote from `self.browser` to `self.provider`
2). add a new function for remote provider:  `_get_remote_browser`
3). add a new function to get the capabilities for remote and sauce providers: ` _get_webdriver_capabilities`
command_executor and browser are required for remote provider, the demo configuration in robottelo.properties is:
[robottelo]
browser=remote
webdriver=firefox
command_executor=http://10.73.xxxx.xxx:4444/wd/hub
=> Enhancement for remote webdriver

airgun/browser.py, airgun/entities/login.py, airgun/settings.py, airgun/views/common.py, airgun/views/job_invocation.py, docs/conf.py, tests/conftest.py
Source code comments are not the best project management tool. Plus we need single source of truth, not ideas scattered across multiple places.
GitHub issues with references to these comments were created instead:
* #348
* #349
* #350
* #351
* #352
This, in some way, implements #10. We could argue proper fixes for these comments should be implemented to really close #10, but let's face it - at this point of project lifecycle, these comments are enhancement ideas, not bugs.
=> Remove TODO and FIXME comments (closes #10)

airgun/entities/discoveredhosts.py, airgun/entities/discoveryrule.py
Fixes UI Discovered Hosts and Discovery Rule Failed Tests:
Discovered Host:
-------------------------------------
```
2019-07-04 19:25:02 - conftest - DEBUG - Registering custom pytest_configure
2019-07-04 19:25:02 - conftest - DEBUG - Fetching BZs to deselect...
========================================== test session starts ==========================================
platform linux -- Python 3.6.8, pytest-4.6.3, py-1.7.0, pluggy-0.12.0
rootdir: /home/jitendrayejare/Desktop/RedHat/RoboTelloNew/robottelo
plugins: forked-1.0.2, services-1.3.1, xdist-1.26.1, mock-1.10.4, cov-2.6.1
collecting ... 2019-07-04 19:25:24 - conftest - DEBUG - Collected 8 test cases
collected 8 items / 7 deselected / 1 selected …
```
=> Discovered Host and Discovery Rule Menu locator Fixed

airgun/views/smart_class_parameter.py, airgun/views/smart_variable.py
Fix the smart class parameter tests. 
Currently, the select field name has changed from key_type to parameter_type   
changed the locators and updated tests as well here in this PR 
###Upstream PR 
https://github.com/theforeman/foreman/pull/5241/files#diff-6c69b0cc93d393f1605b2749fda757bfR3
```
Testing started at 6:16 PM ...
/home/okhatavk/Satellite/robottelo/env/bin/python /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pycharm/_jb_pytest_runner.py --target test_smartclassparameter.py::test_positive_end_to_end
Launching py.test with arguments test_smartclassparameter.py::test_positive_end_to_end in /home/okhatavk/Satellite/robottelo/tests/foreman/ui
2019-07-08 18:16:55 - conftest - DEBUG - Registering custom pytest_configure
2019-07-08 18:16:55 - conftest - DEBUG - Fetching …
```
=> updated locator from key_type to parameter_type

airgun/views/audit.py
Class name changes dynamically from class='list-view-pf-expand' to class='list-view-pf-expand active' when the drop-down is by default is shown. Hence it was not able to get located, I tried to fix this with using contains 
```
Testing started at 2:38 PM ...
/home/okhatavk/Satellite/robottelo/env/bin/python /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pycharm/_jb_pytest_runner.py --target test_audit.py::test_positive_update_event
Launching py.test with arguments test_audit.py::test_positive_update_event in /home/okhatavk/Satellite/robottelo/tests/foreman/ui
2019-07-16 14:38:11 - conftest - DEBUG - Registering custom pytest_configure
2019-07-16 14:38:11 - conftest - DEBUG - Fetching BZs to deselect...
2019-07-16 14:38:35 - conftest - DEBUG - Deselected tests reason: BZ …
```
=> fixed audit dynamic locator

airgun/entities/product.py
Currently, the test is waiting for the searched deleted entity,  and we are getting an empty message instead of an empty list 
Removing wait_for will not cross the for the entity and search step already has been added all tests so removing it. (i thought this best option)
We do have another option to add an empty message, I personally not like that could against airgun code standards.
```
Testing started at 8:18 PM ...
/home/okhatavk/Satellite/robottelo/env/bin/python /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pycharm/_jb_pytest_runner.py --target test_product.py::test_positive_end_to_end
Launching py.test with arguments test_product.py::test_positive_end_to_end in /home/okhatavk/Satellite/robottelo/tests/foreman/ui
2019-07-15 20:18:51 - conftest - DEBUG - Registering …
```
=> removing unwanted wait after delete operation

airgun/views/hardware_model.py
Without the fix:
```
def test_positive_end_to_end(session, module_org, module_loc):
"""Perform end to end testing for hardware model component
:id: 93663cc9-7c8f-4f43-8050-444be1313bed
:expectedresults: All expected CRUD actions finished successfully
:CaseLevel: Integration
:CaseImportance: High
"""
name = gen_string('alpha')
model = gen_string('alphanumeric')
vendor_class = gen_string('alpha')
info = gen_string('alpha')
new_name = gen_string('alpha')
host_template = entities.Host(organization=module_org, location=module_loc)
host_template.create_missing()
with session:
session.hardwaremodel.create({
'name': name,
'hardware_model': model,
'vendor_class': vendor_class,
'info': info,
})
assert session.hardwaremodel.search(name)[0]['Name'] == name
> hm_values = …
```
=> In 6.6 there is one more div in td->div->a, so lets be smarter here

airgun/browser.py
The `remote_browser` did not forward the `self.test_name` as one of the desired_capabilities, leaving the session without a name (causing random uuid to be generated for them and causing chaos in the Dashboard). This fixes it.
=> add test_name to the capabilities for `remote` browser

airgun/entities/lifecycleenvironment.py, airgun/views/lifecycleenvironment.py
CV filter by default is empty making table having empty rows and while reading puppet modules tab it is not been selected. This will read puppet modules based on CV_filter will help to fix the issue for https://github.com/SatelliteQE/robottelo/issues/7217
```
Testing started at 12:05 PM ...
/home/okhatavk/Satellite/robottelo/env/bin/python /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pycharm/_jb_pytest_runner.py --target test_lifecycleenvironment.py::test_positive_add_puppet_module
Launching py.test with arguments test_lifecycleenvironment.py::test_positive_add_puppet_module in /home/okhatavk/Satellite/robottelo/tests/foreman/ui
2019-07-23 12:05:45 - conftest - DEBUG - Registering custom pytest_configure
2019-07-23 12:05:45 - conftest - DEBUG - Fetching BZs to deselect... …
```
=> overriding read to handle cv_filter option

airgun/views/virtwho_configure.py
After deployed the virtwho configure, we need to validate the configure status, but it's difficult to get the status by Text:
<span class="virt-who-config-report-status pficon-ok status-ok" title="" data-original-title="The virt-who report arrived within the interval"></span>
This commit will support to get the status from icon color:
`rgba(63, 156, 53, 1)': 'green'` => configure is deployed successfully.
`rgba(54, 54, 54, 1)': 'gray'`  => configure is not reported yet.
=> Get virtwho configure status by icon color

airgun/widgets.py
Should fix/workaround issues stemming from #249
For ui organization tests these changes proved to fix the search field population problem.
With this PR, clear is called explicitly before filling the search field, also the clear mechanism has been changed to use the clear button instead of browser.clear() when possible
=> fix searchfield clear issues

airgun/entities/subscription.py
This will happen when user with insufficient permissions access the page. We rely on "Add subscription" button state as proxy for manifest presence, but with recent changes this button may not be displayed at all. In that case, exception would be thrown.
Also, wait a moment for button to appear. During testing it did happen that page was "loaded", but button was not present yet.
Done as alternative fix for issue described in https://github.com/SatelliteQE/robottelo/pull/7370 . Adding DO NOT MERGE until we reach consensus where fix should be applied.
```
$ pytest -v -k test_positive_access_with_non_admin_user_without_manifest tests/foreman/ui/test_subscription.py
===================================================================================== test session starts …
```
=> Don't throw exception when "Add subscription" button is not present

airgun/browser.py
Some of the actions in our testcases fail with `chromedriver v77` due to the javascript error.
according the background of the issue
https://bugs.chromium.org/p/chromedriver/issues/detail?id=3044#c1
I'm just about to silently catch and pass the exception, which is (according the above comment) pretty much what older versions of the chromedriver did.
- tested on several test cases, this didn't break anything.
Please note, that the error occurs under several circumstances, and in our case it wasn't exactly the dropdown.
=> Pass the chromedriver v76+ undefined method 'left' js error

airgun/browser.py
Automation failure correction of test_positive_export 
https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_host.py#L814
export automatically goes to browser where `files[0]` were empty and this cause an error later on. 
https://github.com/SatelliteQE/airgun/blob/master/airgun/browser.py#L756
I looked into the JavaScript and it seems there can be also another option fileUrl. 
```
collected 28 items / 27 deselected / 1 selected
============ 1 passed, 27 deselected, 2 warnings in 165.83 seconds =============
```
=> javascript fix on listing downloaded files via selenium

airgun/entities/virtwho_configure.py
As dicsussion :https://github.com/SatelliteQE/robottelo/pull/7405#discussion_r334514188
We need to add actions as below:
1.can_view(self)
2.can_create(self)
3.can_delete(self, entity_name)
4.can_edit(self, entity_name)
to support [the roles testcases for virtwho](https://github.com/SatelliteQE/robottelo/pull/7405)
=> Add actions to assert if the virtwho config can view/create/edit/delete

airgun/views/login.py
After the new Login page was introduced to Foreman,
the button is no longer an 'input' and currently doesn't have the name attribute,
old implementation:
```
<input type="submit" name="commit" value="Log In" class="btn btn-primary" data-disable-with="Log In">
```
new:
```
<button type="submit" disabled="" class="login-pf-submit-button btn btn-lg btn-primary btn-block">Log In</button>
```
I didn't test this change, but if you would like this to work I guess a small modification like this PR could be made.
also, if you would like to add something more specific, I have added this PR in foreman: https://github.com/theforeman/foreman/pull/6971
so we could wait and than change it into something with an ID or name,
this is how the Login Page button will look like after that PR will get merged: …
=>  Fix LoginView submit button selector

airgun/entities/contenthost.py, airgun/views/contenthost.py
This is PR is to support errata details page from content host
https://github.com/SatelliteQE/robottelo/pull/7471
```
Testing started at 11:47 AM ...
/home/okhatavk/okhatavk/Satellite/robottelo/env/bin/python /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pycharm/_jb_pytest_runner.py --target test_errata.py::test_positive_content_host_errata_details
Launching py.test with arguments test_errata.py::test_positive_content_host_errata_details in /home/okhatavk/Satellite/robottelo/tests/foreman/ui
platform linux -- Python 3.7.2, pytest-4.6.3, py-1.8.0, pluggy-0.13.0
rootdir: /home/okhatavk/Satellite/robottelo
plugins: cov-2.8.1, xdist-1.30.0, …
```
=> added support for read errata details

airgun/views/contenthost.py
Update the 'subscriptions' tab on ContentHostDetailsView as missing 'Events ' in Sat6.7 (different with Sat6.6)
Some cases failed due to this.
Error info:
`selenium.common.exceptions.NoSuchElementException: Message: Could not find an element './ul/li[normalize-space(.)="Subscriptions"]'`
Such as :
Satellite:
tests.foreman.ui.test_subscription.test_positive_view_vdc_subscription_products 
Virt-who:
tests.foreman.virtwho.test_ui_virtwho.test_positive_deploy_configure_by_id
tests.foreman.virtwho.test_ui_virtwho.test_positive_deploy_configure_by_script
=> Update subscriptions tab on ContentHostDetailsView

airgun/entities/os.py
The table has a filter mechanism that is causing problems with selecting an element in the row and drilling into the link or selecting the deletion action in the table.  This is causing failures to several test cases in ```test_operatingsystem.py```. I'm not sure of the correct syntax so that I can pass in the value for ```view.table.row()``` and ```self.parent.table.row()``` so it can navigate correctly.  This current implementation seems to work, but is not ideal.
=> Fix item selections on os table

airgun/views/task.py
required by test_positive_bulk_delete_host
```
test tests/foreman/ui/test_host.py -k test_positive_bulk_delete_host
=================================================== test session starts ====================================================
tests/foreman/ui/test_host.py .                                                                                      [100%]
================================== 1 passed, 28 deselected, 3 warnings in 118.70 seconds ===================================
```
=> updated xpath for task details check

airgun/entities/host.py, airgun/views/host.py
fixes #435
Previously, airgun selected host one by one in the table based on the entity list. This PR adds an option to select all hosts via the table header checkbox
Confirmation run:
```
pytest tests/foreman/ui/test_host.py -k test_positive_bulk_delete_host
collected 29 items / 28 deselected / 1 selected                                                                                  
tests/foreman/ui/test_host.py .                                                                                            [100%]
===================================== 1 passed, 28 deselected, 3 warnings in 106.81 seconds ======================================
```
=> selecting all hosts using checkbox from table header

airgun/widgets.py
- Multiple tests are false failed due to a slight delay to load dialog window/related element and `self.confirm_dialog.click()` action failed.
- Added a `wait_for` to avoid false fail and check `is_displayed`.
- Tests results:
```
PASSED2020-01-22 13:15:31 - robottelo - DEBUG - Finished Test: test_repository.py/test_positive_resynchronize_rpm_repo
tests/foreman/ui/test_repository.py::test_positive_resynchronize_puppet_repo PASSED                                                                                   [100%]
tests/foreman/ui/test_repository.py::test_positive_end_to_end_custom_module_streams_crud PASSED                                                                       [100%]
```
=> Added is_displayed for confirm_dialog click

airgun/views/redhat_repository.py
- Added support to clear the old search if exists.
- some tests failing because of it.
- test results:
```
tests/foreman/ui/test_repository.py::test_positive_reposet_disable_after_manifest_deleted PASSED                                                                      [100%]
```
=> Added support to clear the old searach if exists in RH repos

airgun/browser.py
There's no header menu in Satellite anymore, and this was source of consistent failures on one test.
Test results and more context in https://github.com/SatelliteQE/robottelo/pull/7603
=> Remove move_to_element override

airgun/navigation.py, airgun/session.py
This should fix the basic session navigator copy exception and NavigateStep with newer version of navmazing as newer versions need logger in __init__ to work as expected that is called from navigator 
in earlier version navigator created navigation step without logger, but in newer version it require NavigationStep with logger. 
This should be tested with robottelo, but with navmazing version >=  1.1.6
in insight project created a work-arround for this , and seems working as expected, but robottelo use all the feature of widgetastic and navmazing and need an intensify testing as maybe other areas may be affected.
=> Fixes session navigator and NavigateStep.

airgun/entities/contenthost.py
Hello
While using test automation server to run this:
tests/foreman/ui/test_contenthost.py::test_positive_end_to_end_bulk_update
I saw this error:
>           session.contenthost.delete(vm.hostname)
tests/foreman/ui/test_contenthost.py:280: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../shiningpanda/jobs/ad0ef6b5/virtualenvs/d41d8cd9/lib/python3.6/site-packages/airgun/entities/contenthost.py:23: in delete
view.actions.fill('Remove Hosts')
../../shiningpanda/jobs/ad0ef6b5/virtualenvs/d41d8cd9/lib/python3.6/site-packages/widgetastic/log.py:115: in wrapped
result = f(self, *args, **kwargs)
../../shiningpanda/jobs/ad0ef6b5/virtualenvs/d41d8cd9/lib/python3.6/site-packages/widgetastic/widget/base.py:30: in wrapped
return method(self, …
=> Change Remove Hosts to Delete Hosts

airgun/views/task.py
I already talk to @mirekdlugosz and I appreciate Mireks help a lot. I would be happy to if he can take a look once again:
4 types of progressbar are used: 
1. views.common.py  - TaskDetailsView  - entities. (contenthost, errata, hostcollection, product, repository)
2. views.task - TaskDetailsView - entities. (host, task)
3. views.contentview - PublishPromoteProgressBar - inherits from Progressbar - entities.contentview
4. views.subscription - SubscriptionListView - entities.subscription
Mirek has a point that everything it is going to change to react. 
So my idea now is, maybe we can change default locator inside `ProgressBar` 
But as most of the locators are still using views.common which do not change. **So I think, for now just change the locator in TaskDetailsView.** 
a) Should I use …
=> host bulk delete change in path

airgun/entities/host.py
Moving cockpit test more into airgun. 
I was also thinking to use view
`webconsole_view = WebConsoleView(self.browser)`
```
class WebConsoleView(View):
ROOT = "//iframe"
hostname = Text("//a[@id='system_information_hostname_button']")
@property
def is_displayed(self):
return self.browser.wait_for_element(
self.hostname, exception=False) is not None
```
I was unable to get into the frame for hostname. 
I thought, first view to get me into frame second view to get me inside the frame. I was unable to create that. 
I also find issue on widgetastic not sure if the frame I mean is the same as they mentioned in the [issue](https://github.com/RedHatQE/widgetastic.core/issues/98).
I think this approach, not all logic in the test and not all in the airgun is somewhere in the middle and I think …
=> cockpit test changes

airgun/browser.py
On Chrome 80 and above, opening Satellite results in `NET::ERR_CERT_AUTHORITY_INVALID` error page displayed ("Your connection is not private"). Starting Chrome with `--ignore-certificate-errors` makes this error go away and allows UI test to work.
`--ignore-certificate-errors` has been available in Chrome for at least 10 years, and Chrome team has been trying to get rid of it since at least 2014. It's not publicly advertised and is probable to stop working sometime soon, but it does get the job done now.
[This StackOverflow question](https://stackoverflow.com/q/7580508/3552063) deals with similar issue and provides multiple solutions applied at various levels. I'm open to discussion about better approach than one in this PR.
Verified on Chrome 80 and Chrome 81 (beta, to be released …
=> Add --ignore-certificate-errors flag for Chrome 80+

airgun/entities/contenthost.py, airgun/views/contenthost.py, airgun/widgets.py
Thanks to @mirekdlugosz for help with this. In particular, for pointing out that `total_items` line in widgets.py had to change:
"now has two classes:
\<span class="pagination-pf-items-total ng-binding">1\</span>
As fix, change `total_items` line in airgun/widgets.py to:
total_items = Text(".//span[contains(@class, 'pagination-pf-items-total')]")"
=> Add pagination support for chost

airgun/entities/login.py, airgun/session.py, airgun/views/login.py
Raised this PR by taking the reference of #397 to fix one of the required login page footer text validation after logout https://github.com/SatelliteQE/robottelo/pull/7710
Test Result
```
$ pytest tests/foreman/ui/test_settings.py::test_positive_update_login_page_footer_text_with_long_string
platform linux -- Python 3.6.6, pytest-4.6.3, py-1.8.1, pluggy-0.13.1
collecting ... 2020-04-02 12:59:37 - conftest - DEBUG - Collected 1 test cases
2020-04-02 18:29:40 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f3f7b3695c0 …
```
=> Fixes 349 Added browser logout method

airgun/entities/host.py
Out automation is too fast. Zalenium record shows, that automation clicks on the right place, and also upgrades automation passes, just normal automation don't. I was unable to reproduce it, but this should solve the problem. 
Please let me try this, I know it is unusual approach, but if it will not work i can remove it after one snap. 
This is maybe a bug in satellite, but no one ever will be that fast, or will not mind to click submit once more.
Note and quetion: 
Not sure if I should use sleep ? 
And if this should go to z-stream ? I think if this patch will work it should
=> submit is too fast, causing bug in automation

airgun/views/common.py, airgun/widgets.py
widgetastic.patternfly 1.3.0 broke backwards compatibility in flash messages. See #456 and https://github.com/SatelliteQE/robottelo/pull/7646#pullrequestreview-361973923 .
Main changes in widgetastic.patternfly:
* Class to use when instantiating single message is stored as `FlashMessages` class variable, which means we can drop override for `messages`. It also requires us to define `SatFlashMessage` before `SatFlashMessages`.
* `SatFlashMessages.messages` is no longer a property, but a method - must be called
* `SatFlashMessages.messages()` is a generator instead of returning list
* `SatFlashMessages` no longer takes locator as argument during instantiation
We will have to merge https://github.com/SatelliteQE/robottelo/pull/7678 around the same time as this one, as Airgun will no longer …
=> Add support for widgetastic.patternfly >=1.3.0 (fixes #456)

airgun/entities/host.py
That was renamed during 6.7 cycle, but went unnoticed, as apparently nothing in Robottelo actually uses that. But IQE/Satellite integration does.
I will be cherry-picking that to 6.7.z after merge.
```
$ iqe tests plugin insights_satellite  -k test_satellite_ansible_install --critical
===================================================================================== test session starts =====================================================================================
platform linux -- Python 3.6.3, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /home/mzalewsk/sources/iqe-satellite-plugin, testpaths: /home/mzalewsk/sources/iqe-satellite-plugin/iqe_insights_satellite
plugins: cov-2.8.1, hypothesis-5.8.0, subtests-0.2.1, iqe-red-hat-internal-envs-plugin-0.7.7, polarion-collect-0.23.1, …
```
=> Rename "Play Ansible roles" action on hosts page

airgun/views/job_invocation.py
On Job page, Cancel and Abort were converted from `<a>` to `<input>` back in 6.6. This change is needed to fix non-critical error in tests calling `.read()` on `JobInvocationStatusView` or any of derived classes.
I will be backporting that to 6.7.z and 6.6.z after merge.
Before:
```
2020-05-22 13:06:48 ERROR [HostsJobInvocationStatusView/cancel_job]: An exception happened during read call (elapsed 498 ms)
2020-05-22 13:06:48 ERROR [HostsJobInvocationStatusView/cancel_job]: Message: Could not find an element Locator(by='xpath', locator="//a[text()='Cancel Job']")
Traceback (most recent call last):
File "/home/mzalewsk/.virtualenvs/iqe-tests/lib64/python3.6/site-packages/widgetastic/log.py", line 115, in wrapped
result = f(self, *args, **kwargs)
File …
```
=> Convert <a> to <input> on Job page

airgun/views/hostcollection.py
Hello
This test was failing:
`tests/foreman/ui/test_hostcollection.py -k test_positive_install_modular_errata`
with:
`>               'Could not find an element {}'.format(repr(locator))) from None
E           selenium.common.exceptions.NoSuchElementException: Message: Could not find an element ".//input[@type='text' and @ng-model='errataFilter']"`
Change came from here:
katello]$ git show 555699b37f9d779af4c1f81c966c8f9ca257a2dc
commit 555699b37f9d779af4c1f81c966c8f9ca257a2dc
Author: Walden Raines <walden@redhat.com>
Date:   Fri Jul 19 14:44:01 2019 -0400
Fixes #26318: add scoped search to CH errata page.
Add missing scoped search to the content host errata page.
https://projects.theforeman.org/issues/26318
```
<div ng-show="showTable()" …
```
=> Fix errata search box locator

airgun/widgets.py
Hello
This change caused test[1] to fail:
In 6.7: `style=""><span class="ng-scope">Save</span></button>`
In 6.8: `style="">Save</button>`
Example of faliure:
`> 'Could not find an element {}'.format(repr(locator))) from None
E selenium.common.exceptions.NoSuchElementException: Message: Could not find an element       Locator(by='xpath', locator=".//button[span[text()='Save']]")
.env/lib64/python3.7/site-packages/widgetastic/browser.py:352: NoSuchElementException`
[1] tests/foreman/ui/test_contenthost.py::test_positive_end_to_end
=> Fix locator for save button on Content Host description text field.

.pre-commit-config.yaml
Our pre-commit config used unpinned flake8 dependency. flake8 recently introduced new version with updated style guide that reports syntax that used to pass without problems.
We could fix that error, but our strategy is to freeze older branches in time, so it makes more sense for me to pin flake8 dependency to known version.
Test results - see travis
=> [6.7.z] Pin older flake8 to avoid travis failures

airgun/views/modulestream.py
See https://github.com/SatelliteQE/robottelo/pull/7927
```bash
pytest tests/foreman/ui/test_modulestreams.py::test_positive_module_stream_details_search_in_repo
===================================================================================== test session starts =====================================================================================
platform linux -- Python 3.8.5, pytest-4.6.3, py-1.8.1, pluggy-0.13.1
rootdir: /home/mzalewsk/sources/robottelo
plugins: cov-2.10.0, mock-1.10.4, forked-1.2.0, services-1.3.1, xdist-1.32.0
collecting ... 2020-08-11 09:58:52 - conftest - DEBUG - Collected 1 test cases …
```
=> [POC] Fix search clear on Module Streams page

airgun/entities/contenthost.py
- When we install the package using Katello-Agent then Conte Host Task Details page populated, this view needs to be associated with action function. 
- Remove not required logic 
Please see the PR https://github.com/SatelliteQE/robottelo/pull/7947
=> update the logic for install package using katello-agent

airgun/entities/rhsso_login.py, airgun/views/rhsso_login.py
1. We need to have this url after taking hammer auth login --two- factor  
```
[root@dhcp-2-190 ~]# echo 'df64bf48-453f-4755-8eb1-ba4d5a6a13c7.f89cccec-f022-4ef5-b06b-c2eaa15f799e.77bad924-e252-4daa-a7c9-9697d05339eb' | hammer auth login oauth --oidc-token-endpoint https://rhss.example.com/auth/realms/satqe/protocol/openid-connect/token --oidc-authorization-endpoint https://rhssoexample.com/auth/realms/satqe/protocol/openid-connect/auth --oidc-client-id satelliteexample.com-foreman-openidc --oidc-redirect-uri 'urn:ietf:wg:oauth:2.0:oob' --two-factor 
Enter URL in browser: https://satellite.example.com/auth/realms/satqe/protocol/openid-connect/auth?response_type=code&client_id=satellite.example.com-foreman-openidc&redirect_uri=urn:ietf:wg:oauth:2.0:oob&scope=openid
```
2. This is the view …
=> added support for two-factor rh-sso auth login

airgun/entities/sync_status.py
Hello
For 6.7 branch
this fixes issue :
Sync Status page does not display correctly unless refreshed #507
=> Fix Sync Status page partial loading (#507)

airgun/entities/user.py
Test User UI automation occasionally failed on expecting to see the user creation dialog before the create user button was actually clicked
=> wait until user create button is clicked

airgun/entities/host.py
Cockpit test is now opening in new tab by default. This PR implement that. 
I am open to different ideas how to implement this. This is first time I am switching the tabs. 
I've hit an logging error in test result (you can find at at the bottom of test result) 
Test results with loggs:
```
/automation/tests/foreman/ui/test_host.py -- -k test_positive_cockpit
collected 30 items / 29 deselected / 1 selected
test_host.py::test_positive_cockpit 
=================== 1 passed, 29 deselected in 75.07 seconds ===================
=> fix cockpit test, cockpit now opens in new tab

airgun/views/discoveryrule.py, airgun/widgets.py
Since this is a react element, the browser.clear() doesn't work. We need to access the 'x' button and click it.
```
$ py.test test_discoveryrule.py::test_positive_end_to_end
=== test session starts ===
platform linux -- Python 3.7.8, pytest-4.6.3, py-1.9.0, pluggy-0.13.1
rootdir: /home/rplevka/work/rplevka/robottelo
plugins: xdist-1.33.0, services-1.3.1, forked-1.2.0, repeat-0.8.0, cov-2.10.1, mock-1.10.4
collecting ... 2020-09-18 12:23:25 - conftest - DEBUG - Collected 1 test cases
collected 1 item                                                                                                                                                             
test_discoveryrule.py . 
=== 1 passed, 4 warnings in 166.85 seconds ===
```
=> Implementing custom clear() method for the AutoCompleteTextInput

airgun/entities/host.py
#517 
I requested the same reviewers for ACK thanks.
Test result: 
```
test_host.py::test_positive_cockpit 
=================== 1 passed, 29 deselected in 81.73 seconds ===================
```
=> cp #517 - fix cockpit test, cockpit now opens in new tab

airgun/entities/rhai/plan.py, airgun/views/rhai.py
New actions supported:
* run Ansible playbook
* run Ansible playbook with REX customizations
* download Ansible playbook
* download plan CSV
Needed for https://github.com/SatelliteQE/robottelo/pull/8102 ; see it for test results.
=> Extend Insights plan entity to support more actions

airgun/views/ldapauthentication.py, airgun/widgets.py
```
Testing started at 8:00 PM ...
/home/okhatavk/okhatavk/Satellite/robottelo/env/bin/python /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pycharm/_jb_pytest_runner.py --target test_ldap_authentication.py::test_positive_end_to_end_ad
Launching py.test with arguments test_ldap_authentication.py::test_positive_end_to_end_ad in /home/okhatavk/Satellite/robottelo/tests/foreman/ui
platform linux -- Python 3.6.8, pytest-5.4.3, py-1.8.1, pluggy-0.13.1
rootdir: /home/okhatavk/Satellite/robottelo
plugins: forked-1.1.3, cov-2.8.1, cagoule-0.4.0, mock-1.10.4, xdist-1.34.0, lazy-fixture-0.6.3, services-1.3.1, instafail-0.4.2, ibutsu-1.1.12020-10-28 …
```
=> fixing the authsource locator issue in satellite 6.9

airgun/widgets.py
This PR fixes https://github.com/SatelliteQE/airgun/issues/536 by making the `Pagination` class' `ROOT` locator relative instead of absolute.
=> Fix Pagination ROOT locator issue

airgun/views/virtwho_configure.py
**Description**
Fix #539 
**Test Result**
```
(venv) [hkx303@kuhuang ui]$ pytest test_esx.py -k test_positive_overview_label_name -s
==================================== test session starts =====================================
platform linux -- Python 3.7.3, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /home/hkx303/Documents/CI/robottelo/robottelo, inifile: pytest.ini
plugins: metadata-1.10.0, html-2.1.1, cov-2.10.1, services-1.3.1, xdist-1.34.0, mock-1.10.4, forked-1.3.0, ibutsu-1.1.1
collecting ... 2020-11-27 11:47:35 - conftest - DEBUG - Collected 15 test cases
collected 15 items / 14 deselected / 1 selected       
================== 1 passed, 14 deselected, 5 warnings in 117.31s (0:01:57) ==================
```
=> Update the virt-who view as the http proxy option has been updated

airgun/browser.py, airgun/session.py
This change allows a user to pass in a different hostname than
what is currently in airgun's settings.
Example:
with Session('test', hostname='my.other.sat.com') as session:
session.do_something()
=> Add the ability to create a session for a different satellite

airgun/entities/host.py, airgun/views/host.py
Add "Register Host" page, introduced in Satellite 6.9.
So far no test depends on it, but I tested it with following one:
```python
def test_positive_generate_command(session):
with session:
cmd = session.host.get_register_command({
'setup_insights': 'Yes',
'remote_execution': 'Yes',
'activation_keys': 'non-existing-key,random-key'
})
print(f"\n{cmd}\n")
```
```
$ pytest -sv tests/foreman/ui/test_host.py::test_positive_generate_command
===================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.0, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /home/mzalewsk/.virtualenvs/robottelo/bin/python3
shared_function …
```
=> Implement "Register Host" page

airgun/widgets.py
Some robottelo tests are failing because the `search_field` subwidget cannot be found. This is happening because there are two hidden search fields higher up in the page, associated with the Organization and Location context dropdowns. The `search_field` locator matches those, and because they are not visible, any attempts to interact with `search_field` fail.
This PR fixes the issue by adding a `ROOT` locator to `Search`:
`ROOT = '//div[@id="search-bar" or contains(@class, "toolbar-pf-filter")]'`
The two locators are necessary because there are two distinct search bar implementations. Some pages (e.g., `Administer > Locations`) use the `search-bar` version, whereas others (e.g., `Content > Products`), use `toolbar-pf-filter`.
=> Add ROOT for Search widget

airgun/session.py
This PR makes a small fix to the logging in `session`, where an f-string was not properly defined. Log mesages of the form
`INFO     airgun.session:session.py:264 Setting initial URL to {url}`
are now properly formatted:
`INFO     airgun.session:session.py:264 Setting initial URL to https://satellite.example.com/settings`
=> Fix logger text

airgun/views/common.py
fixes #551 
The drop-down style changed for input selector in 6.9. 
Successfully tested using  tests/foreman/ui/test_jobtemplate.py::test_positive_end_to_end
=> fixed TemplateInputItem

airgun/views/host.py
Id didn't match the reality, PR brings the fix plus matches the var name to the id
=> fixed hostgroup locator for global registration

airgun/entities/contenthost.py, airgun/views/contenthost.py
Airgun prerequisite for testing system purpose bulk actions, new feature in 6.9
Robottelo PR will come soon, successfully tested with:
```
values = {
'service_level': 'Standard',
'usage_type': 'Production',
'role': 'Red Hat Enterprise Linux Server'
}
with session:
session.contenthost.bulk_set_syspurpose(hosts, values)
```
=> syspurpose bulk action 

airgun/views/modulestream.py
The `CustomSearch` widget used in `ModuleStreamsDetailsView` was failing because the locator for the `search_field` sub-widget doesn't exist (anymore?). This PR fixes the issue by updating the locator to match on `id`. I've also removed the `clear_button` sub-widget, which doesn't exist on this particular page's search bar. Any calls to the `clear()` method should still work, because it falls back on clearing the text in `search_field` input field if `clear_button` isn't available. In `airgun/widgets.py`:
```
class Search(Widget):
[...]
def clear(self):
"""Clears search field value and re-trigger search to remove all
filters.
"""
if self.clear_button.is_displayed:
self.clear_button.click()
else:
self.browser.clear(self.search_field)
if self.search_button.is_displayed: …
```
=> Fix CustomSearch widget used in ModuleStreamsDetailsView

airgun/session.py
This PR fixes an issue where if the `Session` instance is initialized with a name containing the `/` character, then `take_screenshot()` fails to save the screenshot file. This happens because the necessary subdirectories of `settings.selenium.screenshots_path` don't get created before `open(filename)` is called.
The fix is to replace any `/` with `_` in the name.
=> Replace any '/' with '_' in session name.

airgun/views/modulestream.py
This PR fixes an issue with viewing the table on a module stream's Repositories tab. The table was implemented using `SatTable`, but as mentioned in the class definition, `SatTable` is deprecated in favor of widgetastic's `Table` class. Using this class instead fixes the issue.
Before:
```
[...]
tests/foreman/ui/test_modulestreams.py F [100%]
=== FAILURES ===
[...]
with session:
session.organization.select(org_name=module_org.name)
assert session.modulestream.search('name = duck')[0]['Name'].startswith('duck')
>           walrus_details = session.modulestream.read('walrus', '5.21')
tests/foreman/ui/test_modulestreams.py:66: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
=> Fix Table widget on ModuleStreamsDetailsView.repositories

airgun/session.py
Airgun's session context manager tries to capture a screenshot of the browser if an exception has been raised, and then log any exception that `take_screenshot()` itself might raise. But there are also cases in which `take_screenshot()` fails, returning `False` without raising an exception. In particular, the underlying selenium webdriver method `get_screenshot_as_file()` that ends up getting called will catch any exceptions from the OS while trying to save the screenshot to file: 
```
try:
with open(filename, 'wb') as f:
f.write(png)
except IOError:
return False
```
I've added a check on the return value of `take_screenshot()`, and some error logging in case of failure.
=> Fix logging if screenshot save failed

airgun/entities/repository.py
This PR fixes the behavior of `RepositoryEntity.global_default_http_proxy`. When a global default http proxy has been configured under `Administer > Settings > Content`, the setting is displayed as:
`proxy_name (proxy_url)`
and `RepositoryEntity.global_default_http_proxy` should return a string matching what the corresponding value will be in the `HTTP Proxy Policy` dropdown when creating a new custom repository:
`Global Default (proxy_name)`
Previously, the method was using the full setting value, like this:
`Global Default (proxy_name (proxy_url))`
Now it uses a regular expression to extract `proxy_name` from the setting and return the correct string.
=> Fix default http proxy name value

airgun/widgets.py
This PR creates a new subclass of `Pagination` called `SatTablePagination`, which has a new `ROOT` locator suitable for use with `SatTable`. Fixes https://github.com/SatelliteQE/airgun/issues/570
=> Create SatTablePagination class for use within SatTable

airgun/widgets.py
With the `FlashMessages` fixes introduced in widgetastic.patternfly,
Wrap FlashMessages methods with new retry_element decorator #129 
https://github.com/RedHatQE/widgetastic.patternfly/pull/129
airgun's partial implementation of those fixes can be removed.
=> Don't overwrite FlashMessages methods

airgun/entities/subscription.py
Fixes https://github.com/SatelliteQE/airgun/issues/511
Taking over from https://github.com/SatelliteQE/airgun/pull/512
`has_manifest` now checks whether the `Delete` button is enabled on the `Manage Manifest` modal window, in order to determine whether a manifest has been imported.
Test results:
```
[...]
collected 9 items / 8 deselected / 1 selected
tests/foreman/ui/test_subscription.py .          [100%]
[...]
=== 1 passed, 8 deselected, 1 warning in 277.50s (0:04:37) ===
```
=> Fix has_manifest

airgun/browser.py
The script in `get_downloads_list` doesn't work for chrome < 79, so added this workaround.
=> Fix browser issue for get_file_content

airgun/widgets.py
In Satellite 6.10, the organization / location selector element has been refactored. This PR changes the widget to use `widgetastic_patternfly4.ouia.ContextSelector`.
Before fix:
```
$ pytest tests/foreman/ui/test_contentview.py::test_positive_add_custom_content
[...]
tests/foreman/ui/test_contentview.py F [100%]
[...]
>           raise NoSuchElementException(
"Could not find an element {}".format(repr(locator))
) from None
E           selenium.common.exceptions.NoSuchElementException: Message: Could not find an element '//li[@id="organization-dropdown"]/a'
venv/lib64/python3.8/site-packages/widgetastic/browser.py:406: NoSuchElementException
[...]
[...]
>           raise NavigationTriesExceeded(self._name)
E           navmazing.NavigationTriesExceeded: Navigation failed …
```
=> Use patternfly4 context selector for org/location dropdown

airgun/entities/cloud_inventory.py, airgun/views/cloud_inventory.py
This PR adds support for `configure_cloud_connector`, `sync_inventory_status` and tries to address sleep issue #578
=> Add support for configure_cloud_connector and sync_inventory_status

airgun/views/computeprofile.py, airgun/views/computeresource.py, airgun/views/domain.py, airgun/views/http_proxy.py, airgun/views/subnet.py
Some of locators for landing page of Satellite 6.10 components have changed because of PF4 change. This PR fixes the landing page locators for those pages.
=> Fix Infrastructure component locators for 6.10

airgun/views/common.py
Hello
I have updated `current_user = Dropdown('OUIA-Generated-Dropdown-1')` but also changed `select_logout` function to use `current_user` as target rather then `account_menu` because both `current_user` and `account_menu` had the same value.
Refs:
https://github.com/RedHatQE/widgetastic.patternfly4/blob/f999f66840df54fd1665d43decfb5691dfc806f6/src/widgetastic_patternfly4/ouia.py#L43
https://github.com/RedHatQE/widgetastic.patternfly4/blob/f999f66840df54fd1665d43decfb5691dfc806f6/src/widgetastic_patternfly4/dropdown.py#L24
=> Update current_user to OUIA Dropdown

airgun/entities/computeresource.py, airgun/views/computeresource.py, airgun/widgets.py
This PR is a result of my investigation into the failed tests of `test_computeresource_vmware.py`. I managed to fix most of it (but not all). The test results:
```
pytest tests/foreman/ui/test_computeresource_vmware.py 
platform linux -- Python 3.9.5, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/petrpochop/Work/robottelo, configfile: pyproject.toml
plugins: forked-1.3.0, xdist-2.2.1, services-2.2.1, reportportal-5.0.8, ibutsu-1.14.1, cov-2.11.1, mock-3.6.0
collected 6 items / 6 deselected                                               
tests/foreman/ui/test_computeresource_vmware.py .....F                   [100%]
=========================== …
```
=> Fixes for some UI CR VMware tests

airgun/entities/login.py, airgun/views/login.py
There is a cache cleanup problem observed with logout due to the recent pattern fly update, Earlier the cache cleanup didn't impact if we ran it after logout, but now cache cleanup is pre-requirement for logout, if we do not use it then logout will not work.
In this PR, I have added two fixes.
1. flash data cleanup before logout
2. Updated the x-path of login_text
**Test Result:**
```
pytest tests/foreman/ui/test_settings.py::test_positive_update_login_page_footer_text_with_long_string
platform linux -- Python 3.8.0, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 …
```
=> Added flash data cleanup before logout

airgun/entities/report_template.py, airgun/views/report_template.py
A test that tries to generate a report and download it couldn't pass because of the way `generating` was located. I found a workaround for that and because of the different nature of the element I used, I renamed it to `generated`.
```
pytest tests/foreman/ui/test_reporttemplates.py::test_positive_generate_registered_hosts_report
collected 1 item                                                               
tests/foreman/ui/test_reporttemplates.py .                               [100%]
================== 1 passed, 3 warnings in 307.62s (0:05:07) ===================
```
=> Fix for a report template test

airgun/views/common.py, airgun/views/computeresource.py, airgun/views/contentview.py
- remove force puppet
- `pre-commit run --all-files` fixes, import reordered and filterbox as one-liner
why we do not run pre commit  by default ?
@latran - Import-only option is missing, but I think if there is no test no need to implement it
=> Remove force puppet attribute

airgun/entities/host.py, airgun/views/common.py, airgun/views/host.py, airgun/widgets.py
This is pr updates the global registration form that is used for registering the Content Host. Currently the form uses the Patternfly4 UI widgets. Added some custom widgets based on the requirement for Satellite. Once these changes are approved we can update the WT.PF4 repos with same changes in case of need. I'm trying to limit the scope here for now with this PR. 
```
Testing started at 7:12 PM ...
/home/okhatavk/okhatavk/Satellite/robottelo/env/bin/python /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pycharm/_jb_pytest_runner.py --path /home/okhatavk/okhatavk/Satellite/robottelo/tests/foreman/ui/test_host.py -- -k test_positive_global_registration_form
Launching py.test with arguments -k test_positive_global_registration_form …
```
=> updated the global registration form w.r.t PF4

airgun/views/repository.py
For testing ansible collections repo type 6.10 feature, tested with a wip test on a robottelo side:
```
pytest tests/foreman/ui/test_repository.py -k test_positive_ansible_collection_repo_end_to_end
=================================================================== test session starts ====================================================================
platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/pondrejk/Documents/robottelo, configfile: pyproject.toml
plugins: forked-1.3.0, services-2.2.1, reportportal-5.0.8, mock-3.6.1, cov-2.12.1, xdist-2.3.0, ibutsu-1.16
collected 29 items / 28 deselected / 1 selected …
```
=> add views for ansible collection repo

airgun/entities/provisioning_template.py, airgun/views/provisioning_template.py, airgun/views/sync_templates.py
`tests/foreman/ui/test_templatesync.py::test_positive_import_templates` now passes after https://github.com/SatelliteQE/robottelo/pull/8777 
`tests/foreman/ui/test_templatesync.py::test_positive_export_templates` unfortunately doesn't on 6.10 due to an automation-unrelated bug (but passes on 6.9)
=> Changes needed to fix templatesync tests

airgun/entities/usergroup.py, airgun/views/usergroup.py
Currently the create new button exist at two location 
1. On blank page when there is no usergroups exists 
2. On all page when usergroups are previously exists 
Both places are containing the different locator's hence adding small path to fix this.
=> updated the usergroup create button locator

airgun/entities/hostgroup.py, airgun/views/hostgroup.py
Currently Satellite 6.10, some of the entity create button has changed to PF4 elements causing failures in tests which has blank All view 
```
raise NoSuchElementException(
E   selenium.common.exceptions.NoSuchElementException: Message: Could not find an element Locator(by='xpath', locator="//a[contains(@href, '/hostgroups/new')]")   
```
```
platform linux -- Python 3.8.6, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/okhatavk/okhatavk/Satellite/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, cov-2.10.1, xdist-2.2.1, reportportal-5.0.8, mock-3.5.1, forked-1.3.0, ibutsu-1.14.1, picked-0.4.6collected 71 items / 70 deselected / 1 …
```
=> fixing the host-group create button locator mix-up

airgun/entities/base.py, airgun/views/common.py
If submit is not enabled click cancel and raise error. This will be used in my upcoming PR for [robottelo](https://github.com/SatelliteQE/robottelo/pull/8843).
=> Bookmarks: check if submit button is enabled

airgun/entities/contenthost.py, airgun/views/contenthost.py
its no longer used in the web UI
I think we need this for 6.9 too.
=> Remove SyspurposeBulkActionView confirm step

airgun/entities/contenthost.py, airgun/views/contenthost.py
its no longer used in the web UI
cherry-pick from https://github.com/SatelliteQE/airgun/pull/606
=> [cherry-pick] Remove SyspurposeBulkActionView confirm step (#606)

airgun/entities/contenthost.py, airgun/entities/errata.py
Hello airgunners
As REX is default in 6.10 I had to add support for the Job Invocation page which is used when applying errata, to track task progress, rather than CHost Details Task view.
Used by tests in `tests/foreman/ui/test_contenthost.py` and `tests/foreman/ui/test_hostcollection.py`.
Thank you
[Update test ui test_contenthost to use REX #8817](https://github.com/SatelliteQE/robottelo/pull/8817)
[Convert test hostcollection to use REX #8847](https://github.com/SatelliteQE/robottelo/pull/8847)
=> Add REX support to chost and errata tests

airgun/entities/cloud_insights.py, airgun/views/cloud_insights.py
In snap 12 some new UI changes were made to Configure > Insights page.
This PR fixes airgun support for searchbox and sync recommendation button on Insights page.
I am using `Keys.ENTER` from `selenium.webdriver.common.keys` because new searchbox doesn't have search button and user need to use enter key to perform search operation.
I have tested the code change with test written in https://github.com/SatelliteQE/robottelo/pull/8767
=> Fix searchbox and sync recommendation button of Insights page.

airgun/views/virtwho_configure.py
**Description**
The UI testing for virt-who plugin testing failed due to the error messages:
```
>           raise TimedOutError(timeout_msg)
E           wait_for.TimedOutError: Could not do 'function other_div_displayed()' at /root/plugin/venv/lib/python3.8/site-packages/widgetastic_patternfly/__init__.py:583 in time
```
Some of the cases failed as the UI cannot identify if it is at the right view, the view of virt-who configure has been changed...
**Test Result**
```
(venv) [root@vw-test robottelo]#  pytest tests/foreman/virtwho/ui/test_esx.py -k test_positive_deploy_configure_by_id -s
================== 1 passed, 14 deselected, 9 warnings in 672.63s (0:11:12) ==================
```
=> Update the Virtwho configure Edit and Detail view

airgun/widgets.py
We were missing to pass the `component id` which was started failing the test for the with **`'NoneType' object has no attribute 'replace'`**   
This is a experiment PR to see if this actually fix on CI, seems to be working locally fine.
=> fixing error 'NoneType' object has no attribute 'replace'

airgun/widgets.py
wt.core removed it, and airgun didn't have it as a direct dependency.
instead of including it, since the project is unmaintained, remove it
Cherry-picking to 6.9.z branch
=> [6.9.z cherry-pick] Remove jsmin dependency (#616)

airgun/views/host.py
using the TextInput instead of Text to get the value attribute
TextInput.read uses the value attribute :smile:  so it was implemented there, I was just not able to identify it :)
=> test fix, Text element changed to TextInput

airgun/entities/repository.py
Failure in some test cases that relies on this entity
results:
```
pytest tests/foreman/ui/test_repository.py::test_positive_delete_random_docker_repo
===== 1 passed, 3 warnings in 224.62s (0:03:44) ======
pytest tests/foreman/ui/test_repository.py::test_positive_end_to_end_custom_yum_crud
======== 1 passed, 3 warnings in 632.45s (0:10:32) ===============
pytest tests/foreman/ui/test_repository.py::test_positive_end_to_end_custom_module_streams_crud
======== 1 passed, 3 warnings in 781.31s (0:13:01) ================
```
=> Fix deleting a repo entity

airgun/browser.py
No need for the code to set the idleTimeout as it set directly handled by webkaifuku 
For Test Result : git lab satelliteqe-jenkins - 448 PR
=> removing the idle-timeout, webkaifuku takes care!

airgun/views/common.py
False Conditioning in `is_displayed()` returns a wrong boolean value making tests to search entity even though the search field is not available on the page.
=> Incorrect is_searchable return value | Incorrect condition

airgun/entities/errata.py
The entities previouslyhad the jobinvocationpage for display of the applying errata progress which is incorrect.  I'm rewriting it to be in the `ErrataTaskDetailsView`.
results can be found with https://github.com/SatelliteQE/robottelo/pull/9156
=> Fix applying errata progress page

airgun/exceptions.py
Added `NoSuchElementException` selenium exception to the exceptions of airgun and to be imported from airgun insted of direct dependency in Robottelo!
Refer discussion: https://github.com/SatelliteQE/robottelo/pull/9177 !
=> Added selenium exceptions to airgun

airgun/entities/http_proxy.py, airgun/entities/oscapcontent.py, airgun/entities/oscappolicy.py, airgun/entities/oscaptailoringfile.py, airgun/views/http_proxy.py, airgun/views/oscapcontent.py, airgun/views/oscappolicy.py, airgun/views/oscaptailoringfile.py
Use `Pf4ConfirmationDialog` widget for Http Proxy and Openscap entities and fix locator of `title` for scap content.
Tried:
```
(Pdb) session.http_proxy.delete('env-proxy-01')
(Pdb) session.oscapcontent.delete('abc')
(Pdb) session.oscappolicy.delete('jkdsa')
(Pdb) session.oscaptailoringfile.delete('xyz')
```
Refer https://github.com/SatelliteQE/airgun/issues/651 and https://github.com/SatelliteQE/airgun/pull/649 for more info.
=> Use Pf4ConfirmationDialog for Http Proxy and Openscap

airgun/entities/hostcollection.py, airgun/views/hostcollection.py
Hello
this update is to support a test for applicable host search URI in Host Collection errata bulk update dialog.
Ref:
[BZ#1838800 – Manage Errata from Content Host Page does not provide link to view list of content hosts affected by an Errata.](https://bugzilla.redhat.com/show_bug.cgi?id=1838800)
=> Add search_applicable_hosts

airgun/entities/host.py, airgun/views/host.py
This PR adds support for reading host status.
Host status is the one you see when you hover over icon before hostname on "All Hosts" page.
=> Add support for reading host status

setup.py
$subject
> pip list | grep selenium
selenium                4.1.0
selenium-smart-locator  0.2.0
> pip list | grep pattern
widgetastic.patternfly  1.3.4
widgetastic.patternfly4 0.23.2.dev2+gcb3bf05
=> Upgrading to selenium grid 4 needs upgrade in the version 

airgun/entities/contentview.py
As ContentView has been changed to new UI, we are still running tests to legacy ui. To support testing legacy UI, some refactor in code was required. This PR helps to fix that.
=> legacy content view test support added

airgun/exceptions.py
Allows for import of wt.exceptions classes/module attrs directly through
airgun
=> Add generic wt exceptions import to airgun.exceptions

airgun/browser.py, airgun/exceptions.py, setup.py
This is a series of cherry-picks (most of which look to have already been included) that should hopefully bring our 6.9.z branch up-to-date with what is needed to run against Selenium Grid 4. Let me know if there is anything else needed.
=> 6.9.z backports 

airgun/entities/host.py, airgun/views/host.py, airgun/views/host_new.py
this branch is build up on #673 
before you review, please look at  #673 
the old UI host details tests are now using new UI -> dropdown -> legacy UI 
dialog = Pf4ConfirmationDialog()
this is introducing 
Robottelo [PR](https://github.com/SatelliteQE/robottelo/pull/9401)
=> 70 UI host test fix

airgun/entities/location.py, airgun/views/common.py, airgun/views/http_proxy.py, airgun/views/organization.py, airgun/views/oscapcontent.py, airgun/views/oscappolicy.py, airgun/views/oscaptailoringfile.py
PF4 confirmation dialog is common across the components so moving confirmation dialog to common.py 
Components impacted:
1. Organization
2. Http proxy
3. Oscatailoringfile
4. oscapcontent
5. oscappolicy
=> Moved delete confirmation dialog to common.py

airgun/views/dashboard.py
Changed Table to SatTable to be able to read the table in the widget.
Associated robottelo PR: SatelliteQE/robottelo#9537
=> Use SatTable instead of Table for the LatestErrata widget

airgun/entities/virtwho_configure.py, airgun/views/virtwho_configure.py
Hey,
Add nutanix support on airgun.
Nutanix cases: PASS
```
(robottelo_vv) [yanpliu@yanpliu robottelo]$ pytest ./tests/foreman/virtwho/ui/test_nutanix.py -k test_positive_deploy_configure_by_id
platform linux -- Python 3.8.12, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/yanpliu/gitrepo/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, ibutsu-2.0.2, forked-1.4.0, xdist-2.5.0, cov-3.0.0, metadata-1.11.0, html-3.1.1, mock-3.7.0, reportportal-5.0.12
collected 3 items / 5 deselected / -2 selected …
```
=> nutanix support on airgun

airgun/entities/host.py, airgun/entities/host_new.py
Adressed #695.
in 6.11 the new host details are disabled by default, this PR should be re-added for 6.12
I can manually change it in 6.11 for all host modules so the change without this PR fix would work, but I want to have a 1:1 setup with customers. 
I run two tests from this [PR](https://github.com/SatelliteQE/robottelo/pull/9553 ) one using old and one that is using new host details 
```
tests/foreman/ui/test_host.py::test_positive_read_from_details_page
tests/foreman/ui/test_host.py::test_positive_read_details_page_from_new_ui[host_details_ui]
=========== 2 passed, 40 deselected, 5 warnings in 262.28s (0:04:22) ===========
```
=> disable new host ui details by default

airgun/browser.py
fixing #703 
```
Launching pytest with arguments -k test_positive_end_to_end /Users/okhatavk/satellite/robottelo/tests/foreman/ui/test_hostgroup.py --no-header --no-summary -q in /Users/okhatavk/satellite/robottelo
/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pycharm/_jb_pytest_runner.py:33: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
elif version.LooseVersion(pytest.__version__) >= version.LooseVersion("6.0"):
collecting ... collected 6 items / 5 deselected / 1 selected
tests/foreman/ui/test_hostgroup.py::test_positive_end_to_end 
=========== 1 passed, 5 deselected, 14 warnings in 162.06s (0:02:42) ===========
```
=> fixed the squash issue in handling the alerts

airgun/widgets.py
This will fix the `session.host.create_bookmark({'name': name, 'query': query, 'public': True})`, As there are mixture of the PF4 search and PF3 Search. We were failing this part. This will fix both conditions. 
@jaryn Can you please test with this PR? it worked for me over Satellite 6.11 and 6.10
=> fixed the bookmark search in airgun

airgun/entities/discoveredhosts.py, airgun/entities/discoveryrule.py, airgun/views/discoveredhosts.py, airgun/views/discoveryrule.py
In the new UI, the Discovery Rules page has a different Create button depending on if there are any rules yet or not. My updates made a simple change to address this. I also added a `wait_for` during an Auto Provision dialog step in Discovered Hosts, since one of my tests was failing due to the dialog not submitting properly.
=> Fixing DiscoveryPlugin failures

airgun/widgets.py
- Remove the redundant `self.open` as `self.items` has that step
- Fixed the correct locator here (https://github.com/SatelliteQE/airgun/pull/711/files#diff-b6d36691d2c9b246c1a2f7fff90473fe0098b4a6846694417e9acc246e35ea30R569) because of this line commit  
@vsedmik Can you please test your changes as well as 1 bookmark test passes with this change.  (from my side it looks okay)
=> fix the locator issue in action drop down

airgun/widgets.py
The `foreman_autocomplete` component has different behavior in 6.11 where once you finish typing the search, the dropdown stays open even if you run `<element>.blur()`. Replacing this with a tab makes sure the element is out of focus. Tested on 6.10 and 6.11 and it seems to work. Waiting for https://github.com/SatelliteQE/airgun/pull/716 to be merged and I will test this change on the DiscoveryPlugin pipeline.
=> Fixing AutoCompleteTextInput blur

airgun/entities/ansible_role.py, airgun/entities/ansible_variable.py, airgun/session.py, airgun/views/ansible_role.py, airgun/views/ansible_variable.py, airgun/widgets.py
This PR adds views and entities for the Ansible Roles page (located in the webUI at Configure > Roles) and the Ansible Variables page (located in the webUI at Configured > Variables).
This is my first Airgun PR, so I would appreciate any feedback.
Note that there are two widgets in the `NewAnsibleVariableView` view that are not currently functioning properly; I have marked these with comments. However, in the interest of getting these changes merged ahead of 6.10 branching next week, I thought it best to get this up for review in its current state.
=> Add ansible roles view and entity

airgun/entities/product.py, airgun/views/product.py
Not pretty sure why selenium fails to click on the ng (angular) checkbox object, I even check the class with another widget checkbox which is still similar and selenium works ok there. With this PR added just a small hack that will fix this issue.
@latran  This might need to check with UI dev why such behavior would happen.
=> updated the checkbox checking using javascript

airgun/entities/ansible_role.py
The preimport_check function in the Ansible Role view was ambiguously
named based on what it returned and how it was used. This commit 
removes that function and incorporates its functionality into the 
imported_roles_count property.
=> Remove preimport_check and move functionality

airgun/entities/webhook.py, airgun/session.py, airgun/views/webhook.py, airgun/widgets.py
Basic Create, Update, Read, and Delete functions added for Administer > Webhooks. There are no unique ids for the AutoCompleteTextInputs on the Create page, so I am searching for them based on their neighboring `<label>` elements right now. I will reach out to UX to get some unique ids for these, so we don't have to worry about new updates to the DOM. Because the Webhook create, update, and read is based on a popup window (there's no separate page for these actions), we have to do some waiting for elements to be loaded in the popup which is handled by `wait_for_popup`. There are two checks because the popup and it's child elements all load asynchronously of each other.
=> Adding Webhooks CRUD

airgun/entities/cloud_inventory.py, airgun/views/cloud_inventory.py
```
pytest tests/foreman/ui/test_rhcloud_inventory.py 
platform linux -- Python 3.8.6, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/addubey/work/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, mock-3.7.0, forked-1.3.0, cov-3.0.0, xdist-2.5.0, ibutsu-2.2.2, reportportal-5.1.2
collected 8 items / 3 deselected / 5 selected …
```
=> [UI] -Test fixes for rh_cloud inventory

airgun/browser.py, airgun/entities/computeresource.py
1) Click method is called still on the same page as fill so it's affected by the same issue (the linked bug). Call it also in the block with ignored timeout.
2) Point for discussion. When the bug manifests, it affects the page until it is reloaded. `ensure_page_safe` is called many times, always waiting half a minute to timeout. In case of this test, filling the page took so long (more than an hour) that the user got logged out of satellite meanwhile, causing the test to fail. I experimentally tested that for this test, `2s` is a value where the page manages to load while also not waiting to the point of timeout. (`5s` is too much)
There are definitely multiple solutions for 2):
a) This one. When we expect timeout, don't wait for it that long, by default.
b) Create another property, …
=> Click in ignored ensuresafepage. Set low timeout.

.github/workflows/auto_cherry_pick.yml, .github/workflows/required_labels.yml
This PR adds the AutoCherryPick Github Actions for enforcing CherryPick labels and the cherrypick labeled PRs has been autocherrypicked to previous branches!
The parent PR to master should cherrypick PRs in n-2 branches , n-1 parent PR should open in n-1 branch and n-2 doesnt opens a cherrypick PR !
=> AutoCherrypick GHAs

airgun/widgets.py
Was seeing some errors in 6.12 since these PF4 Buttons were changed in the DOM a little (might be worth getting static ids for these?). Switched out the type of widget here so we could locate with locators and button text. I used `aria-label` for the close button so that it could be used in 6.11 also. Although I think most people will be using the cancel button instead.
=> Fixing PF4ConfirmationDialog

airgun/entities/host.py
Fixes #695
After resolving BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2106691 we are using the new host UI by default. This would allow all tests that were using the old UI to run without any test changes.
Test result:
=> use new host UI by default

airgun/widgets.py
Starting Selenium 4.3.0 all of `find_element_by_*` was removed and replaced by `find_element(by=*)`
https://stackoverflow.com/questions/72754651/attributeerror-webdriver-object-has-no-attribute-find-element-by-xpath
=> Replace find_element_by_xpath with find_element

airgun/views/product.py
This PR adds missing support for container type repo discovery.
Required for https://github.com/SatelliteQE/robottelo/pull/10012
=> Add support for container repo discovery

airgun/views/host_new.py
As [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2121739) was resolved, we can use the table element for recent audits and jobs. 
PR for robotello will follow, including tests.
=> Recent audits and jobs as table

airgun/entities/webhook.py, airgun/views/webhook.py
Webhook page in 6.12 was updated. No longer need `new_on_blank`.
Results:
```
platform linux -- Python 3.9.13, pytest-7.1.3, pluggy-0.13.1
rootdir: /home/gsulliva/Programming/robottelo, configfile: pyproject.toml
plugins: forked-1.3.0, services-2.2.1, cov-2.12.1, xdist-2.5.0, reportportal-5.1.2, mock-3.8.2, ibutsu-2.2.4
tests/foreman/ui/test_webhook.py .                                       [100%]
================== 1 passed, 7 warnings in 329.15s (0:05:29) ===================
```
=> Fixing new Webhook button

airgun/entities/lifecycleenvironment.py
The confirmation dialogue page to remove lce was missing.  Adding that in so lce can be deleted.
Test result
```
pytest tests/foreman/ui/test_lifecycleenvironment.py -k test_positive_end_to_end
=========== 1 passed, 5 deselected, 3 warnings in 189.68s (0:03:09) ============
```
=> Missing delete confirmation function

airgun/widgets.py
Since there are multiple search bars in some pages (like CR detail, where one filter is empty but still matches [0]), search fields should be searched within the active tab (or active element, more generally). Only when there are still multiple, the first one is selected, which is usually topmost, which is usually what you intended. So far, always the first one on the page was selected.
I'll think about why that empty filter exists and perhaps file a BZ but this fix is semantically correct anyway, I suppose.
I'm not sure if some tests don't rely on this IMO incorrect behavior so think about it for a minute.
Also, I love this comment of one (1) dot that took me ~2 hours so please accept it! :D
[0]
```
(//div[contains(@class, "toolbar-pf-filter") or contains(@class, "title_filter") or …
```
=> Only search search bar in the active element, not from DOM root

.github/workflows/auto_cherry_pick.yml
Cherrypicking of Robottelo PR https://github.com/SatelliteQE/robottelo/pull/10436 that says:
```
By default the AutoCherrypicked PRs to labeled branches need not to again decide for auto-cherrypicking. The decision has should have already been made in parent PR itself as to what branch the PR will be cherrypicked and assigned branch labels.
```
=> No Cherrypick by default

.github/workflows/auto_cherry_pick.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/797
Cherrypicking of Robottelo PR https://github.com/SatelliteQE/robottelo/pull/10436 that says:
```
By default the AutoCherrypicked PRs to labeled branches need not to again decide for auto-cherrypicking. The decision has should have already been made in parent PR itself as to what branch the PR will be cherrypicked and assigned branch labels.
```
=> [6.13.z] No Cherrypick by default

.github/workflows/auto_cherry_pick.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/797
Cherrypicking of Robottelo PR https://github.com/SatelliteQE/robottelo/pull/10436 that says:
```
By default the AutoCherrypicked PRs to labeled branches need not to again decide for auto-cherrypicking. The decision has should have already been made in parent PR itself as to what branch the PR will be cherrypicked and assigned branch labels.
```
=> [6.12.z] No Cherrypick by default

.github/workflows/auto_cherry_pick.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/797
Cherrypicking of Robottelo PR https://github.com/SatelliteQE/robottelo/pull/10436 that says:
```
By default the AutoCherrypicked PRs to labeled branches need not to again decide for auto-cherrypicking. The decision has should have already been made in parent PR itself as to what branch the PR will be cherrypicked and assigned branch labels.
```
=> [6.11.z] No Cherrypick by default

airgun/entities/cloud_inventory.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/808
The test is failing because of a missing confirmation dialog click.
Fixes https://github.com/SatelliteQE/robottelo/pull/10660
=> [6.13.z] Fix configure_cloud_connector method

airgun/views/host.py
Activation keys field location on Global registration page has been moved to general tab from advanced tab hence updated the location.
Changes caused by [BZ 2059829](https://bugzilla.redhat.com/show_bug.cgi?id=2059829)
=> Updated Activation keys field location on global registration page

airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/802
Activation keys field location on Global registration page has been moved to general tab from advanced tab hence updated the location.
Changes caused by [BZ 2059829](https://bugzilla.redhat.com/show_bug.cgi?id=2059829)
=> [6.13.z] Updated Activation keys field location on global registration page

airgun/views/host.py
Test `test_positive_read_details_page_from_new_ui` is failing in the 6.13 automation.
The test was trying to click hostname in the  Hosts table but it was actually clicking on the Actions dropdown in the same row.
Locator change fixes the test failure.
Tested locally.
=> Fix locator for hosts table

airgun/views/virtwho_configure.py
Description of changes
ahv_internal_debug option support for virt-who configuration
Functional demonstration
Can create and update this option virt-who configuration
ahv_internal_debug = Checkbox(id='foreman_virt_who_configure_config_ahv_internal_debug')
Example:
Test cases :PASS
```
(robottelo_vv) [yanpliu@yanpliu robottelo]$ pytest ./tests/foreman/virtwho/ui/test_nutanix.py -k test_positive_ahv_internal_debug_option 
2023-02-02 09:40:13 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
subscription.rhn_password is required in env main
2023-02-02 09:40:13 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
subscription.rhn_password is required in env main …
```
=> ahv_internal_debug virt-who config support

airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/811
Test `test_positive_read_details_page_from_new_ui` is failing in the 6.13 automation.
The test was trying to click hostname in the  Hosts table but it was actually clicking on the Actions dropdown in the same row.
Locator change fixes the test failure.
Tested locally.
=> [6.13.z] Fix locator for hosts table

airgun/views/contenthost.py
Test `test_positive_view_hosts_with_non_admin_user` is failing in the 6.13 automation.
Locator change fixes the test failure.
=> Fix locator for content host table

airgun/views/contenthost.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/814
Test `test_positive_view_hosts_with_non_admin_user` is failing in the 6.13 automation.
Locator change fixes the test failure.
=> [6.13.z] Fix locator for content host table

airgun/entities/host_new.py, airgun/views/host_new.py
Updates to the traces tab, as well as some support for the new Enable Traces modal. I didn't bother supporting all the possible uses of this modal, as it's not relevant for the current test. This can be added later if more traces tests are desired.
=> Updates to New Host UI Traces tab

airgun/entities/host_new.py, airgun/views/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/821
Updates to the traces tab, as well as some support for the new Enable Traces modal. I didn't bother supporting all the possible uses of this modal, as it's not relevant for the current test. This can be added later if more traces tests are desired.
=> [6.13.z] Updates to New Host UI Traces tab

airgun/entities/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/826
Added `view.wait_displayed()` to `NewHostEntity::get_details()`
so it is ensured the host detail page is fully loaded.
=> [6.13.z] NewHostEntity::get_details() wait check added

airgun/entities/host.py, airgun/views/host.py, airgun/views/host_new.py
This adds few functions to the HostEntity to work
with the Manage columns dialog and the hosts table:
- `manage_table_columns`
- `get_displayed_table_headers`
[SOLVED] ~~*Note:* for some reason, when using `manage_table_columns()` (which then reloads the page)
and then calling `get_table_headers()`, `StaleElementReferenceException` is always thrown.
It may do something that the widget `widgetastic.widget.table.Table` implements `headers`
as a `@cached_property`.
I've tried to use `Table().clear_cache()` (and other hacks) but to no avail.~~
=> New Host UI - Manage columns functions

airgun/entities/host.py, airgun/views/host.py, airgun/views/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/820
This adds few functions to the HostEntity to work
with the Manage columns dialog and the hosts table:
- `manage_table_columns`
- `get_displayed_table_headers`
[SOLVED] ~~*Note:* for some reason, when using `manage_table_columns()` (which then reloads the page)
and then calling `get_table_headers()`, `StaleElementReferenceException` is always thrown.
It may do something that the widget `widgetastic.widget.table.Table` implements `headers`
as a `@cached_property`.
I've tried to use `Table().clear_cache()` (and other hacks) but to no avail.~~
=> [6.13.z] New Host UI - Manage columns functions

airgun/views/host.py
Changed locator for `Name` in `views/host.py/HostsView`. Before, the locator was matching incorrectly to the value in Reccommendations column instead of Name because of similar values.
Fixed by adding condition that Name's locator should not include `'Insights'`, which is the Reccomendations locator.
In Hosts, Reccomendations value points to `'(hostname)/#Insights'` and Name value points to `'(hostname)'`.
=> change locator for `Name` in `HostsView`

airgun/views/contenthost.py
Pagination wasn't working for Content Hosts, so this replaces the non functional Pagination widget with some more specific locators. Necessary for https://github.com/SatelliteQE/robottelo/pull/11193
=> Fix Pagination for Content Hosts

airgun/entities/cloud_inventory.py
The test `test_positive_configure_cloud_connector` is failing because of a missing confirmation dialog click.
Cherry-pick from https://github.com/SatelliteQE/airgun/pull/808
=> [cherry-pick] Fix configure_cloud_connector method

airgun/views/redhat_repository.py
Quick fix for the Search box on the Red Hat Repositories page. Makes the box itself, and the search button operational.
=> Fix locators for RHRepo Search box and Search button

airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/828
Changed locator for `Name` in `views/host.py/HostsView`. Before, the locator was matching incorrectly to the value in Reccommendations column instead of Name because of similar values.
Fixed by adding condition that Name's locator should not include `'Insights'`, which is the Reccomendations locator.
In Hosts, Reccomendations value points to `'(hostname)/#Insights'` and Name value points to `'(hostname)'`.
=> [6.13.z] change locator for `Name` in `HostsView`

airgun/views/redhat_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/844
Quick fix for the Search box on the Red Hat Repositories page. Makes the box itself, and the search button operational.
=> [6.12.z] Fix locators for RHRepo Search box and Search button

airgun/views/redhat_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/844
Quick fix for the Search box on the Red Hat Repositories page. Makes the box itself, and the search button operational.
=> [6.13.z] Fix locators for RHRepo Search box and Search button

airgun/entities/host_new.py, airgun/views/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/833
I have implemented new entities that allow us to do several actions on the new host details page: 
* Edit system purpose
* Add host to host collection
* Remove host from host collection
* Add new parameter
* Edit parameter
* Delete parameter
* Remediate with insights
I have also made some view extension that was needed, to create those entities.
=> [6.13.z] Extension of NewHostUI entities

.github/workflows/dispatch_release.yml
Now, the release for changelogs will be tagged in this repo from the SatQE CI job.
How?
--------
1. Upon receiving UMB message for the new snap for a major downstream release in development, the CI job triggers.
2. The CI job sends an HTTP dispatch request to the `auto release` workflow in this repo (created in this PR)
3. Upon receiving the HTTP request, the workflow runs with new tag name and creates a new tag in the repo.
4. The same tag is then used to create a new release with automatic release notes.
So all the releases here would now be automatically created.
=> Auto Release Airgun

airgun/views/contenthost.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/830
Pagination wasn't working for Content Hosts, so this replaces the non functional Pagination widget with some more specific locators. Necessary for https://github.com/SatelliteQE/robottelo/pull/11193
=> [6.13.z] Fix Pagination for Content Hosts

airgun/entities/contenthost.py
Add content host Legacy content host UI details support.
Test Cases PASS:
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py  -k test_positive_deploy_configure_by_id_script --disable-warnings -q
2 passed, 32 deselected, 9 warnings in 887.60s (0:14:47)
```
=> Add Legacy content host UI support

airgun/entities/computeresource.py, airgun/entities/host_new.py, airgun/views/host_new.py
Adds support for the new Virtualization card added in 6.14. This view will only work for the version of the the card that's returned when the Virtualization platform of the host is RHV, as when other Virtualization platforms are used (vmware, etc) the card will have different fields, since it just displays the info that it recieves from the hypervisor. Not ideal, but I don't have a good way to automatically generate virtualized hosts of other types, so this should cover the basic functionality at least.
=> Add Virtcard entity

.github/workflows/pull_request.yml, setup.py
=> Bump GHA python version check to 3.10 and 3.11

.github/workflows/pull_request.yml, setup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/877
=> [6.14.z] Bump GHA python version check to 3.10 and 3.11

.github/workflows/pull_request.yml, setup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/877
=> [6.13.z] Bump GHA python version check to 3.10 and 3.11

.github/workflows/pull_request.yml, setup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/877
=> [6.12.z] Bump GHA python version check to 3.10 and 3.11

.github/workflows/pull_request.yml, setup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/877
=> [6.11.z] Bump GHA python version check to 3.10 and 3.11

airgun/views/virtwho_configure.py
when create a virt-who config without chose the organization, the organization option will display on the virt-who configuration UI page
Case PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py -k test_positive_organization_id_option --disable-pytest-warnings -q
1 passed, 35 deselected, 5 warnings in 128.66s (0:02:08)
```
=> add orgnization option for virt-who configuration UI page

airgun/views/virtwho_configure.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/863
when create a virt-who config without chose the organization, the organization option will display on the virt-who configuration UI page
Case PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py -k test_positive_organization_id_option --disable-pytest-warnings -q
1 passed, 35 deselected, 5 warnings in 128.66s (0:02:08)
```
=> [6.13.z] add orgnization option for virt-who configuration UI page

airgun/views/virtwho_configure.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/863
when create a virt-who config without chose the organization, the organization option will display on the virt-who configuration UI page
Case PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py -k test_positive_organization_id_option --disable-pytest-warnings -q
1 passed, 35 deselected, 5 warnings in 128.66s (0:02:08)
```
=> [6.12.z] add orgnization option for virt-who configuration UI page

airgun/views/virtwho_configure.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/863
when create a virt-who config without chose the organization, the organization option will display on the virt-who configuration UI page
Case PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py -k test_positive_organization_id_option --disable-pytest-warnings -q
1 passed, 35 deselected, 5 warnings in 128.66s (0:02:08)
```
=> [6.14.z] add orgnization option for virt-who configuration UI page

airgun/entities/host_new.py
It seems like the tests I wrote are failing when get_repos_set is run. Adding a sleep timer allows for the table to load and return the correct value. 
https://github.com/SatelliteQE/robottelo/pull/11380
https://github.com/SatelliteQE/robottelo/pull/11717/files
=> Added sleep to get_repos_set

airgun/views/host.py
OUIA IDs of Global Registration are updated and it is causing failures in stream. This change only impacts stream.
=> Update Global Registration OUIA IDs

airgun/views/audit.py
The problem is that with 6.14, the suggestions dropdown stays open even after the search is submitted, so we need to change focus from the search field to be able to expand the result. I didn't find a smarter way to do it other than clicking on the title. All audit log UI tests were failing due to this, with this change:
```
pytest tests/foreman/ui/test_audit.py -k test_positive_add_event
============================================================ test session starts ============================================================
collected 6 items / 5 deselected / 1 selected                                                                                               
tests/foreman/ui/test_audit.py . …
```
=> fix in audit log search

airgun/entities/computeresource.py, airgun/entities/host_new.py, airgun/views/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/869
Adds support for the new Virtualization card added in 6.14. This view will only work for the version of the the card that's returned when the Virtualization platform of the host is RHV, as when other Virtualization platforms are used (vmware, etc) the card will have different fields, since it just displays the info that it recieves from the hypervisor. Not ideal, but I don't have a good way to automatically generate virtualized hosts of other types, so this should cover the basic functionality at least.
=> [6.14.z] Add Virtcard entity

airgun/views/audit.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/887
The problem is that with 6.14, the suggestions dropdown stays open even after the search is submitted, so we need to change focus from the search field to be able to expand the result. I didn't find a smarter way to do it other than clicking on the title. All audit log UI tests were failing due to this, with this change:
```
pytest tests/foreman/ui/test_audit.py -k test_positive_add_event
============================================================ test session starts ============================================================
collected 6 items / 5 deselected / 1 selected                                                                                               
tests/foreman/ui/test_audit.py . …
```
=> [6.14.z] fix in audit log search

airgun/entities/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/874
It seems like the tests I wrote are failing when get_repos_set is run. Adding a sleep timer allows for the table to load and return the correct value. 
https://github.com/SatelliteQE/robottelo/pull/11380
https://github.com/SatelliteQE/robottelo/pull/11717/files
=> [6.13.z] Added sleep to get_repos_set

airgun/entities/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/874
It seems like the tests I wrote are failing when get_repos_set is run. Adding a sleep timer allows for the table to load and return the correct value. 
https://github.com/SatelliteQE/robottelo/pull/11380
https://github.com/SatelliteQE/robottelo/pull/11717/files
=> [6.14.z] Added sleep to get_repos_set

.github/workflows/auto_cherry_pick.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/895
null
=> [6.14.z] remove g-chat notification for failed auto cherrypick, handled in slack

.github/workflows/auto_cherry_pick.yml
=> [6.12.z] - remove g-chat notification for failed auto-cherrypick, handled in slack

.github/workflows/auto_cherry_pick.yml
=> [6.11.z] - remove g-chat notification for failed auto-cherrypick, handled in slack

.github/workflows/trigger_robottelo_workflow.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/843
Problem statement: Currently, the Robottelo image is only updated when a Robottelo PR is merged, which means that it won't be updated if there are any changes merged in Airgun/Nailgun. This can cause issues when running automation as it might not have the latest code changes from these repositories.
Solution: We can add a new [repository_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch) trigger that [listens for any changes](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event) in the Airgun/Nailgun repositories. When any PR is merged in those repos, the trigger will run the workflow that updates the Robottelo image. …
=> [6.14.z] Add trigger-robottelo-workflow for updating robottelo image on quay

.github/workflows/trigger_robottelo_workflow.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/843
Problem statement: Currently, the Robottelo image is only updated when a Robottelo PR is merged, which means that it won't be updated if there are any changes merged in Airgun/Nailgun. This can cause issues when running automation as it might not have the latest code changes from these repositories.
Solution: We can add a new [repository_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch) trigger that [listens for any changes](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event) in the Airgun/Nailgun repositories. When any PR is merged in those repos, the trigger will run the workflow that updates the Robottelo image. …
=> [6.13.z] Add trigger-robottelo-workflow for updating robottelo image on quay

.github/workflows/trigger_robottelo_workflow.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/843
Problem statement: Currently, the Robottelo image is only updated when a Robottelo PR is merged, which means that it won't be updated if there are any changes merged in Airgun/Nailgun. This can cause issues when running automation as it might not have the latest code changes from these repositories.
Solution: We can add a new [repository_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch) trigger that [listens for any changes](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event) in the Airgun/Nailgun repositories. When any PR is merged in those repos, the trigger will run the workflow that updates the Robottelo image. …
=> [6.12.z] Add trigger-robottelo-workflow for updating robottelo image on quay

airgun/browser.py, airgun/entities/acs.py, airgun/session.py, airgun/views/acs.py, airgun/views/host_new.py, airgun/widgets.py
Assingment `SAT-17105`
In this PR I have created new files `views/acs.py` and `entities/acs.py` to support new page in the Satellite called `Alternate Content Sources`.
The `views/acs.py` file contains the whole description of the new ACS page in the Satellite including the creation wizard.
The `entities/acs.py` file contains a wide spectrum of functions that enables users to perform actions over this ACS page.
i.e.:
- Create a new ACS
- Delete ACS
- Refresh ACS
- Get info on existing ACS
- Edit all parts of existing ACS
-  ...
=> Implementation of views and entities for new "Alternate Content Sources" page

airgun/browser.py, airgun/entities/acs.py, airgun/session.py, airgun/views/acs.py, airgun/views/host_new.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/876
Assingment `SAT-17105`
In this PR I have created new files `views/acs.py` and `entities/acs.py` to support new page in the Satellite called `Alternate Content Sources`.
The `views/acs.py` file contains the whole description of the new ACS page in the Satellite including the creation wizard.
The `entities/acs.py` file contains a wide spectrum of functions that enables users to perform actions over this ACS page.
i.e.:
- Create a new ACS
- Delete ACS
- Refresh ACS
- Get info on existing ACS
- Edit all parts of existing ACS
-  ...
=> [6.14.z] Implementation of views and entities for new "Alternate Content Sources" page

airgun/views/common.py
- test `test_positive_update_login_page_footer_text` was failing due to **NoSuchElementException**
- Error details
> selenium.common.exceptions.NoSuchElementException: Message: Could not find an element Locator(by='xpath', locator='.//*[@data-ouia-component-type="PF4/Dropdown" and @data-ouia-component-id="OUIA-Generated-Dropdown-1"]'); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
- Provided id will fix the issue
=> account_menu dropdown 'data-ouia-component-id' is changed now

airgun/views/common.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/917
- test `test_positive_update_login_page_footer_text` was failing due to **NoSuchElementException**
- Error details
> selenium.common.exceptions.NoSuchElementException: Message: Could not find an element Locator(by='xpath', locator='.//*[@data-ouia-component-type="PF4/Dropdown" and @data-ouia-component-id="OUIA-Generated-Dropdown-1"]'); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
- Provided id will fix the issue
=> [6.14.z] account_menu dropdown 'data-ouia-component-id' is changed now

airgun/entities/activationkey.py, airgun/entities/ansible_role.py, airgun/entities/ansible_variable.py, airgun/entities/architecture.py, airgun/entities/cloud_insights.py, airgun/entities/cloud_inventory.py, airgun/entities/config_report.py, airgun/entities/containerimagetag.py, airgun/entities/contentview_new.py, airgun/entities/errata.py, airgun/entities/hardware_model.py, airgun/entities/job_template.py, airgun/entities/lifecycleenvironment.py, airgun/entities/media.py, airgun/entities/modulestream.py, airgun/entities/os.py, airgun/entities/oscapcontent.py, airgun/entities/oscappolicy.py, airgun/entities/oscaptailoringfile.py, airgun/entities/package.py, airgun/entities/partitiontable.py, airgun/entities/provisioning_template.py, airgun/entities/report_template.py, airgun/entities/sync_templates.py, airgun/entities/task.py, airgun/entities/webhook.py
In the old navigation, all items were visible and clickable after selecting first navigation level. In the new implementation of the PF4 Navigation, two levels must be clicked to see the destination.
This PR updates the routes so the Navigation works.
=> Change entity routes to accomodate PF4 navigation with multiple levels

airgun/views/hardware_model.py
`test_hardwaremodel` fails because of wrong locator for page's title, changed the capitalization to `Hardware models` which fixes the test.
=> Change Hardware Model typo

airgun/views/ansible_variable.py, airgun/views/architecture.py, airgun/views/audit.py, airgun/views/bookmark.py, airgun/views/cloud_insights.py, airgun/views/common.py, airgun/views/computeprofile.py, airgun/views/domain.py, airgun/views/hardware_model.py, airgun/views/host.py, airgun/views/hostgroup.py, airgun/views/job_template.py, airgun/views/location.py, airgun/views/media.py, airgun/views/modulestream.py, airgun/views/organization.py, airgun/views/os.py, airgun/views/oscapcontent.py, airgun/views/partitiontable.py, airgun/views/provisioning_template.py, airgun/views/report_template.py, airgun/views/role.py, airgun/views/settings.py, airgun/views/task.py, airgun/views/user.py, airgun/views/usergroup.py, airgun/widgets.py
This PR updates views to use the common `SearchableViewMixinPF4` which uses the new `PF4Search` widget. Should help simplify the Search locators across different views.
**Changed files:**
- `airgun/`
- `widgets.py`
- `airgun/views/`
- `common.py`
- `ansible_variable.py`
- `architecture.py`
- `audit.py`
- `bookmark.py`
- `cloud_insights.py`
- `computeprofile.py`
- `domain.py`
- `hardware_model.py`
- `host.py`
- `hostgroup.py`
- `job_template.py`
- `location.py`
- `media.py`
- `modulestream.py`
- `organization.py`
- `os.py`
- `oscapcontent.py`
- `partitiontable.py`
- `provisioning_template.py`
- `report_template.py`
- `role.py`
- `settings.py`
- `task.py`
- `user.py`
- `usergroup.py`
=> update Search widgets to PF4 class

airgun/views/hardware_model.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/920
`test_hardwaremodel` fails because of wrong locator for page's title, changed the capitalization to `Hardware models` which fixes the test.
=> [6.13.z] Change Hardware Model typo

airgun/views/ansible_variable.py, airgun/views/architecture.py, airgun/views/audit.py, airgun/views/bookmark.py, airgun/views/cloud_insights.py, airgun/views/common.py, airgun/views/computeprofile.py, airgun/views/domain.py, airgun/views/hardware_model.py, airgun/views/host.py, airgun/views/hostgroup.py, airgun/views/job_template.py, airgun/views/location.py, airgun/views/media.py, airgun/views/modulestream.py, airgun/views/organization.py, airgun/views/os.py, airgun/views/oscapcontent.py, airgun/views/partitiontable.py, airgun/views/provisioning_template.py, airgun/views/report_template.py, airgun/views/role.py, airgun/views/settings.py, airgun/views/task.py, airgun/views/user.py, airgun/views/usergroup.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/913
This PR updates views to use the common `SearchableViewMixinPF4` which uses the new `PF4Search` widget. Should help simplify the Search locators across different views.
**Changed files:**
- `airgun/`
- `widgets.py`
- `airgun/views/`
- `common.py`
- `ansible_variable.py`
- `architecture.py`
- `audit.py`
- `bookmark.py`
- `cloud_insights.py`
- `computeprofile.py`
- `domain.py`
- `hardware_model.py`
- `host.py`
- `hostgroup.py`
- `job_template.py`
- `location.py`
- `media.py`
- `modulestream.py`
- `organization.py`
- `os.py`
- `oscapcontent.py`
- `partitiontable.py`
- `provisioning_template.py`
- `report_template.py`
- `role.py`
- `settings.py`
- `task.py`
- `user.py`
- `usergroup.py`
=> [6.14.z] update Search widgets to PF4 class

airgun/views/webhook.py
Switches Webhooks search to PF4. Now, the search doesn't work. It will work after this PR and https://github.com/SatelliteQE/airgun/pull/913 are merged.
=> Use PF4 Search in Webhooks

airgun/views/webhook.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/914
Switches Webhooks search to PF4. Now, the search doesn't work. It will work after this PR and https://github.com/SatelliteQE/airgun/pull/913 are merged.
=> [6.13.z] Use PF4 Search in Webhooks

airgun/views/webhook.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/914
Switches Webhooks search to PF4. Now, the search doesn't work. It will work after this PR and https://github.com/SatelliteQE/airgun/pull/913 are merged.
=> [6.12.z] Use PF4 Search in Webhooks

airgun/views/ansible_variable.py, airgun/views/architecture.py, airgun/views/audit.py, airgun/views/bookmark.py, airgun/views/cloud_insights.py, airgun/views/common.py, airgun/views/computeprofile.py, airgun/views/domain.py, airgun/views/hardware_model.py, airgun/views/host.py, airgun/views/hostgroup.py, airgun/views/job_template.py, airgun/views/location.py, airgun/views/media.py, airgun/views/modulestream.py, airgun/views/organization.py, airgun/views/os.py, airgun/views/oscapcontent.py, airgun/views/partitiontable.py, airgun/views/provisioning_template.py, airgun/views/report_template.py, airgun/views/role.py, airgun/views/settings.py, airgun/views/task.py, airgun/views/user.py, airgun/views/usergroup.py, airgun/widgets.py
Cherrypick of #913 to 6.13.z, fixes #924
This PR updates views to use the common `SearchableViewMixinPF4` which uses the new `PF4Search` widget. Should help simplify the Search locators across different views.
**Changed files:**
- `airgun/`
- `widgets.py`
- `airgun/views/`
- `common.py`
- `ansible_variable.py`
- `architecture.py`
- `audit.py`
- `bookmark.py`
- `cloud_insights.py`
- `computeprofile.py`
- `domain.py`
- `hardware_model.py`
- `host.py`
- `hostgroup.py`
- `job_template.py`
- `location.py`
- `media.py`
- `modulestream.py`
- `organization.py`
- `os.py`
- `oscapcontent.py`
- `partitiontable.py`
- `provisioning_template.py`
- `report_template.py`
- `role.py`
- `settings.py`
- `task.py`
- `user.py`
- `usergroup.py`
=> [6.13.z] update Search widgets to PF4 class (#913)

airgun/views/ansible_variable.py, airgun/views/architecture.py, airgun/views/audit.py, airgun/views/bookmark.py, airgun/views/cloud_insights.py, airgun/views/common.py, airgun/views/computeprofile.py, airgun/views/domain.py, airgun/views/hardware_model.py, airgun/views/host.py, airgun/views/hostgroup.py, airgun/views/job_template.py, airgun/views/location.py, airgun/views/media.py, airgun/views/modulestream.py, airgun/views/organization.py, airgun/views/os.py, airgun/views/oscapcontent.py, airgun/views/partitiontable.py, airgun/views/provisioning_template.py, airgun/views/report_template.py, airgun/views/role.py, airgun/views/settings.py, airgun/views/task.py, airgun/views/user.py, airgun/views/usergroup.py, airgun/widgets.py
Cherrypick of #913 to 6.12.z, fixes #925 
This PR updates views to use the common `SearchableViewMixinPF4` which uses the new `PF4Search` widget. Should help simplify the Search locators across different views.
**Changed files:**
- `airgun/`
- `widgets.py`
- `airgun/views/`
- `common.py`
- `ansible_variable.py`
- `architecture.py`
- `audit.py`
- `bookmark.py`
- `cloud_insights.py`
- `computeprofile.py`
- `domain.py`
- `hardware_model.py`
- `host.py`
- `hostgroup.py`
- `job_template.py`
- `location.py`
- `media.py`
- `modulestream.py`
- `organization.py`
- `os.py`
- `oscapcontent.py`
- `partitiontable.py`
- `provisioning_template.py`
- `report_template.py`
- `role.py`
- `settings.py`
- `task.py`
- `user.py`
- `usergroup.py`
=> [6.12.z] update Search widgets to PF4 class (#913)

airgun/entities/host_new.py, airgun/views/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/933
Adding a small clause here to allow pages that don't have a title attribute to continue using search. Only one I know of for sure that's this way, are the vm_import tests within computeresources, but there might be others. 
This seems like a no op for most pages, and allows others to continue to use search.
=> [6.14.z] Rework of virt card

setup.py
After upgrading to selenium `4.12.0`, it caused the issue. Everything works fine with `4.11.2  `
=> pining the selenium version to 4.11.2

setup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/951
After upgrading to selenium `4.12.0`, it caused the issue. Everything works fine with `4.11.2  `
=> [6.14.z] pining the selenium version to 4.11.2

setup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/951
After upgrading to selenium `4.12.0`, it caused the issue. Everything works fine with `4.11.2  `
=> [6.13.z] pining the selenium version to 4.11.2

airgun/entities/contenthost.py
Add content host Legacy content host UI details support.
Test Cases PASS:
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py  -k test_positive_deploy_configure_by_id_script --disable-warnings -q
2 passed, 32 deselected, 9 warnings in 887.60s (0:14:47)
```
#850
=> [6.14.z]: Add Legacy content host UI support #850

airgun/entities/contenthost.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/950
Add content host Legacy content host UI details support.
Test Cases PASS:
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py  -k test_positive_deploy_configure_by_id_script --disable-warnings -q
2 passed, 32 deselected, 9 warnings in 887.60s (0:14:47)
```
#850
=> [6.13.z]: Add Legacy content host UI support #850

airgun/views/oscapcontent.py
small fix in the heading of page
=> Scap contentview title fixed

airgun/views/oscapcontent.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/967
small fix in the heading of page
=> [6.13.z] Scap contentview title fixed

airgun/widgets.py
As it was, we were getting an error when searching for the element, getting False for is_displayed. Consequently, the clear button was not clicked and a generic browser clear was called instead. The text disappeared for a bit and then it got re-filled to the search field.
It caused failures in tests such as
tests/foreman/ui/test_dashboard.py::test_positive_task_status
Changing type and locator fixes the issue.
=> Fix clean button locator in PF4 search.

airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/965
As it was, we were getting an error when searching for the element, getting False for is_displayed. Consequently, the clear button was not clicked and a generic browser clear was called instead. The text disappeared for a bit and then it got re-filled to the search field.
It caused failures in tests such as
tests/foreman/ui/test_dashboard.py::test_positive_task_status
Changing type and locator fixes the issue.
=> [6.14.z] Fix clean button locator in PF4 search.

airgun/entities/redhat_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/977
In this small PR, I have added an option to search for RedHat repository via custom query which was not available in the current implementation of the `enable` function.
=> [6.14.z] Enabling RedHat repositories enhanced

airgun/entities/host_new.py, airgun/views/host_new.py
Adds support for reading the `Manage host statuses` modal in the new Host page.
Calling `session.host_new.get_host_statuses(entity_name)` returns a dictionary of the values:
```
{
'Execution': {'Status': 'Last execution failed', 'Reported at': '8 minutes ago', 3: ''},
'Configuration': {'Status': 'N/A', 'Reported at': 'N/A', 3: ''}, 
'Build': {'Status': 'N/A', 'Reported at': 'N/A', 3: ''}, 
...
}
```
I will update https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_rhcloud_insights.py to use this instead of the old page, then PRT can be ran, see here https://github.com/SatelliteQE/robottelo/pull/12582
=> add Host statues modal support

airgun/entities/host_new.py, airgun/views/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/966
Adds support for reading the `Manage host statuses` modal in the new Host page.
Calling `session.host_new.get_host_statuses(entity_name)` returns a dictionary of the values:
```
{
'Execution': {'Status': 'Last execution failed', 'Reported at': '8 minutes ago', 3: ''},
'Configuration': {'Status': 'N/A', 'Reported at': 'N/A', 3: ''}, 
'Build': {'Status': 'N/A', 'Reported at': 'N/A', 3: ''}, 
...
}
```
I will update https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_rhcloud_insights.py to use this instead of the old page, then PRT can be ran, see here https://github.com/SatelliteQE/robottelo/pull/12582
=> [6.13.z] add Host statues modal support

airgun/browser.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/964
=> [6.14.z] adding the test name as metadata for searching in grid sessions

airgun/browser.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/964
=> [6.13.z] adding the test name as metadata for searching in grid sessions

airgun/entities/subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/992
Airgun support added because `tests>foreman>ui>test_subscription.py::test_positive_end_to_end` was failing due to flash message, Also uploaded manifest has sca enabled for orgnization and because of that test couldn't read subscription status from dashboard page, So added support to read subscription table.
Note: These are dependable changes for `test_subscription.py::test_positive_end_to_end` to get execute successfully. Dependant [PR #12781](https://github.com/SatelliteQE/robottelo/pull/12781)
=> [6.14.z] subscription page failure fix

airgun/entities/subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/992
Airgun support added because `tests>foreman>ui>test_subscription.py::test_positive_end_to_end` was failing due to flash message, Also uploaded manifest has sca enabled for orgnization and because of that test couldn't read subscription status from dashboard page, So added support to read subscription table.
Note: These are dependable changes for `test_subscription.py::test_positive_end_to_end` to get execute successfully. Dependant [PR #12781](https://github.com/SatelliteQE/robottelo/pull/12781)
=> [6.13.z] subscription page failure fix

airgun/views/activationkey.py
This looks like a troll fix, but it should get the 'test_positive_end_to_end_crud' passing.
=> Fix bad table row locator

airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1003
Missed during https://github.com/SatelliteQE/airgun/pull/866
Changes from https://github.com/Katello/katello/pull/10590
=> [6.14.z] Update Activation Keys helper OUIA ID

airgun/entities/contenthost.py, airgun/entities/hostcollection.py, airgun/views/contenthost.py, airgun/views/hostcollection.py
Katello agent was deprecated and is being removed from 6.15, the functionality will be replaced by REX.
This PR removes references from entities and views.
=> Remove katello-agent from entities and views

airgun/views/containerimagetag.py
In 6.14 and later the structure of the `Container Image Tags` page has been changed - repository was removed from the `Details` tab and a new `Repositories` tab was added.
For reference: https://github.com/Katello/katello/pull/10533
This PR updates the view accordingly.
=> Update the Container Image Tags page view

airgun/views/containerimagetag.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/999
In 6.14 and later the structure of the `Container Image Tags` page has been changed - repository was removed from the `Details` tab and a new `Repositories` tab was added.
For reference: https://github.com/Katello/katello/pull/10533
This PR updates the view accordingly.
=> [6.14.z] Update the Container Image Tags page view

airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1006
null
=> [6.13.z] Add read() method for BaseMultiSelect widget

.github/workflows/pull_request.yml, .pre-commit-config.yaml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1016
Doing similar in Airgun what we did here in https://github.com/SatelliteQE/nailgun/pull/997 nailgun
=> [6.14.z] enabled the pre-commit CI and remove pre-commit GH action

.github/workflows/pull_request.yml, .pre-commit-config.yaml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1016
Doing similar in Airgun what we did here in https://github.com/SatelliteQE/nailgun/pull/997 nailgun
=> [6.12.z] enabled the pre-commit CI and remove pre-commit GH action

airgun/views/host_new.py
Minor change, to fix Navigation error looking for searchbar in the new Host > errata tab.
Part of https://github.com/SatelliteQE/robottelo/pull/12978, update e2e testing.
=> New Host-Errata tab search fix

.pre-commit-config.yaml, airgun/session.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1017
updates:
- [github.com/psf/black: 23.3.0 → 23.10.1](https://github.com/psf/black/compare/23.3.0...23.10.1)
- [github.com/astral-sh/ruff-pre-commit: v0.0.277 → v0.1.3](https://github.com/astral-sh/ruff-pre-commit/compare/v0.0.277...v0.1.3)
- [github.com/pre-commit/pre-commit-hooks: v4.2.0 → v4.5.0](https://github.com/pre-commit/pre-commit-hooks/compare/v4.2.0...v4.5.0)
=> [6.14.z] [pre-commit.ci] pre-commit autoupdate

.pre-commit-config.yaml, airgun/session.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1017
updates:
- [github.com/psf/black: 23.3.0 → 23.10.1](https://github.com/psf/black/compare/23.3.0...23.10.1)
- [github.com/astral-sh/ruff-pre-commit: v0.0.277 → v0.1.3](https://github.com/astral-sh/ruff-pre-commit/compare/v0.0.277...v0.1.3)
- [github.com/pre-commit/pre-commit-hooks: v4.2.0 → v4.5.0](https://github.com/pre-commit/pre-commit-hooks/compare/v4.2.0...v4.5.0)
=> [6.13.z] [pre-commit.ci] pre-commit autoupdate

.pre-commit-config.yaml, airgun/session.py
Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
(cherry picked from commit db70820a28b5f289210a4d39a6291c71607fa3e5)
cherry-pick of #1017
=> [6.12.z] [pre-commit.ci] pre-commit autoupdate 

airgun/views/acs.py, airgun/views/ansible_role.py, airgun/views/ansible_variable.py, airgun/views/cloud_insights.py, airgun/views/filter.py, airgun/views/host_new.py, airgun/views/location.py, airgun/views/task.py, airgun/widgets.py
This PR aims to refactor Pagination in Airgun.
First step with this commit is to change Pagination in individual views to Widgetastic's implementation. It's methods should be compatible with Airgun's existing Pagination widget, so no need to change code that uses it.
Next step is to look into `SatTable` and it's Pagination.
=> Pagination refactor

airgun/views/acs.py, airgun/views/ansible_role.py, airgun/views/ansible_variable.py, airgun/views/cloud_insights.py, airgun/views/filter.py, airgun/views/host_new.py, airgun/views/location.py, airgun/views/task.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/947
This PR aims to refactor Pagination in Airgun.
First step with this commit is to change Pagination in individual views to Widgetastic's implementation. It's methods should be compatible with Airgun's existing Pagination widget, so no need to change code that uses it.
Next step is to look into `SatTable` and it's Pagination.
=> [6.14.z] Pagination refactor

airgun/views/ansible_role.py, airgun/views/ansible_variable.py, airgun/views/cloud_insights.py, airgun/views/filter.py, airgun/views/host_new.py, airgun/views/location.py, airgun/views/task.py, airgun/widgets.py
Cherrypick from https://github.com/SatelliteQE/airgun/pull/947 to 6.12.z
=> [6.12.z] Pagination refactor

airgun/session.py
Added the `ui_session_id` attribute for the holding video session id, later can be used in robottelo for video rp-logging  
https://github.com/SatelliteQE/robottelo/pull/13055
=> added the ui_sesion_id attribute for video-session

airgun/session.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1038
Added the `ui_session_id` attribute for the holding video session id, later can be used in robottelo for video rp-logging  
https://github.com/SatelliteQE/robottelo/pull/13055
=> [6.15.z] - added the ui_sesion_id attribute for video-session (#1038)

airgun/session.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1038
Added the `ui_session_id` attribute for the holding video session id, later can be used in robottelo for video rp-logging  
https://github.com/SatelliteQE/robottelo/pull/13055
=> [6.12.z] added the ui_sesion_id attribute for video-session

airgun/views/host.py
Fix UI navigation, for not finding `'Manage Columns'` button by existing locator,
--- Reproduced locally and in recent CI runs (Stream, 6.15, 6.14) ---
```
from: tests/foreman/ui/test_host.py :: test_positive_manage_table_columns(ln203):
E   session.host.manage_table_columns(columns)
navmazing_null - ERROR - NAVIGATE: Got an error Message: Could not find an element 
Locator(by='xpath', locator='.//*[contains(@data-ouia-component-type,"PF4/Button") and @data-ouia-component-id="OUIA-Generated-Button-link-1"]');
navmazing.NavigationTriesExceeded: Navigation failed to reach [ManageColumns] in the specificed tries
```
=> Fix navigation: All Hosts>Manage Columns

airgun/entities/eol_banner.py, airgun/session.py, airgun/views/eol_banner.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1049
end of life banner view and entity
=> [6.13.z] eol banner

airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1064
null
=> [6.13.z] Add error-msg class in ValidationErrors for settings

airgun/entities/provisioning_template.py, airgun/views/provisioning_template.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1059
=> [6.14.z] Add check to verify supported provisioning templates

airgun/entities/capsule.py, airgun/session.py, airgun/views/capsule.py, airgun/widgets.py
In this PR I have added views and entities for Satellite page coverage.
=> Added Satellite Capsule page coverage

airgun/entities/subscription.py, airgun/views/activationkey.py, airgun/views/contenthost.py, airgun/views/organization.py, airgun/views/subscription.py
These additions are for getting the sca-alerts for the latest 6.15 Feature.
Jira: SAT-20200
Robottelo: https://github.com/SatelliteQE/robottelo/pull/13004
=> branching off 6.15.z for sca only

airgun/__init__.py, airgun/entities/errata.py, airgun/views/errata.py
=> Added possibility to search for debian errata

airgun/entities/host_new.py, airgun/views/host_new.py
Replace individual locators with HostDetailsCard widget, and remove unnecessary and unused entity methods.
These cards can easily be accessed through the get_details method instead. 
Probably also worth stating that these cards aren't currently under test, and this PR doesn't remedy that, it just cleans up the locators and entities that were written when the new Host Details UI was made originally.
=> Host Details Locator Cleanup

airgun/views/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1015
Replace individual locators with HostDetailsCard widget, and remove unnecessary and unused entity methods.
These cards can easily be accessed through the get_details method instead. 
Probably also worth stating that these cards aren't currently under test, and this PR doesn't remedy that, it just cleans up the locators and entities that were written when the new Host Details UI was made originally.
=> [6.14.z] Host Details Locator Cleanup

airgun/views/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1015
Replace individual locators with HostDetailsCard widget, and remove unnecessary and unused entity methods.
These cards can easily be accessed through the get_details method instead. 
Probably also worth stating that these cards aren't currently under test, and this PR doesn't remedy that, it just cleans up the locators and entities that were written when the new Host Details UI was made originally.
=> [6.13.z] Host Details Locator Cleanup

airgun/entities/base.py, airgun/views/common.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1076
Adding new widgets and function for new search feature in the vertical navigation menu.
You can use the menu search functionality in any entity via `BaseEntity.search_menu()`.
=> [6.15.z] Search functionality for vertical navigation menu

airgun/entities/host.py, airgun/views/host.py
**Description**
- Update get_register_command to reflect new mandatory fields i.e ActivationKey, which was previously operating systems.
- Make get_register_command work when no values are passed, required for default values validation and few negative tests.
- Add locator for new_activation_key_link, which appears when no AK available in organization, and when there's single AK in organization, AK will be auto-selected in 6.15+
=> Update get_register_command to reflect new mandatory fields

airgun/entities/host.py, airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1087
**Description**
- Update get_register_command to reflect new mandatory fields i.e ActivationKey, which was previously operating systems.
- Make get_register_command work when no values are passed, required for default values validation and few negative tests.
- Add locator for new_activation_key_link, which appears when no AK available in organization, and when there's single AK in organization, AK will be auto-selected in 6.15+
=> [6.15.z] Update get_register_command to reflect new mandatory fields

airgun/browser.py
Fix get_downloads_list which is causing save_downloaded_file to fail. Fixed issue and removed some unnecessary code.
```
tests/foreman/ui/test_rhcloud_inventory.py:209: in test_rh_cloud_inventory_settings
report_path = session.cloudinventory.download_report(org.name)
../../lib64/python3.11/site-packages/airgun/entities/cloud_inventory.py:43: in download_report
return self.browser.save_downloaded_file()
../../lib64/python3.11/site-packages/airgun/browser.py:430: in save_downloaded_file
file_uri = files[0]
E   IndexError: list index out of range
```
=> Fix get_downloads_list which is causing save_downloaded_file to fail

airgun/entities/virtwho_configure.py
When update the virt-who config name to another name, the edit message has been updated to check the new virt-who config, but the previous code still check the old non-exist virt-who config.
Cases :PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py  -k test_positive_virtwho_manager_role --disable-pytest-warnings -q
1 passed, 33 deselected, 15 warnings in 307.44s (0:05:07)
2023-12-20 03:10:48 - robottelo - WARNING - missing grid_url or session_id. unable to clean video files.
```
=> virtwho config edit name message check update

airgun/browser.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1098
Fix get_downloads_list which is causing save_downloaded_file to fail. Fixed issue and removed some unnecessary code.
```
tests/foreman/ui/test_rhcloud_inventory.py:209: in test_rh_cloud_inventory_settings
report_path = session.cloudinventory.download_report(org.name)
../../lib64/python3.11/site-packages/airgun/entities/cloud_inventory.py:43: in download_report
return self.browser.save_downloaded_file()
../../lib64/python3.11/site-packages/airgun/browser.py:430: in save_downloaded_file
file_uri = files[0]
E   IndexError: list index out of range
```
=> [6.15.z] Fix get_downloads_list which is causing save_downloaded_file to fail

airgun/browser.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1098
Fix get_downloads_list which is causing save_downloaded_file to fail. Fixed issue and removed some unnecessary code.
```
tests/foreman/ui/test_rhcloud_inventory.py:209: in test_rh_cloud_inventory_settings
report_path = session.cloudinventory.download_report(org.name)
../../lib64/python3.11/site-packages/airgun/entities/cloud_inventory.py:43: in download_report
return self.browser.save_downloaded_file()
../../lib64/python3.11/site-packages/airgun/browser.py:430: in save_downloaded_file
file_uri = files[0]
E   IndexError: list index out of range
```
=> [6.14.z] Fix get_downloads_list which is causing save_downloaded_file to fail

airgun/browser.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1098
Fix get_downloads_list which is causing save_downloaded_file to fail. Fixed issue and removed some unnecessary code.
```
tests/foreman/ui/test_rhcloud_inventory.py:209: in test_rh_cloud_inventory_settings
report_path = session.cloudinventory.download_report(org.name)
../../lib64/python3.11/site-packages/airgun/entities/cloud_inventory.py:43: in download_report
return self.browser.save_downloaded_file()
../../lib64/python3.11/site-packages/airgun/browser.py:430: in save_downloaded_file
file_uri = files[0]
E   IndexError: list index out of range
```
=> [6.13.z] Fix get_downloads_list which is causing save_downloaded_file to fail

airgun/entities/virtwho_configure.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1096
When update the virt-who config name to another name, the edit message has been updated to check the new virt-who config, but the previous code still check the old non-exist virt-who config.
Cases :PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py  -k test_positive_virtwho_manager_role --disable-pytest-warnings -q
1 passed, 33 deselected, 15 warnings in 307.44s (0:05:07)
2023-12-20 03:10:48 - robottelo - WARNING - missing grid_url or session_id. unable to …
```
=> [6.14.z] virtwho config edit name message check update

airgun/entities/virtwho_configure.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1096
When update the virt-who config name to another name, the edit message has been updated to check the new virt-who config, but the previous code still check the old non-exist virt-who config.
Cases :PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py  -k test_positive_virtwho_manager_role --disable-pytest-warnings -q
1 passed, 33 deselected, 15 warnings in 307.44s (0:05:07)
2023-12-20 03:10:48 - robottelo - WARNING - missing grid_url or session_id. unable to …
```
=> [6.15.z] virtwho config edit name message check update

airgun/entities/all_hosts.py, airgun/session.py, airgun/views/all_hosts.py
This missed the cutover for 6.15.z, so this is a manual cherrypick to get these changes in. Supports another manual Cherrypick of the tests over to 6.15.z as well.
Original PR: https://github.com/SatelliteQE/airgun/pull/1039
=> Manual Cherrypick All Hosts UI to 6.15.z

airgun/entities/host_new.py
This new addition is for SAT-22193
A customer scenario came up where we need to individually check each repository and then use the new override functionality for all repos selected. We cannot use the "select all" method to reporoduce. 
Robottelo:https://github.com/SatelliteQE/robottelo/pull/13596
=> Adding new functionality for multi repo override

airgun/entities/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1120
This new addition is for SAT-22193
A customer scenario came up where we need to individually check each repository and then use the new override functionality for all repos selected. We cannot use the "select all" method to reporoduce. 
Robottelo:https://github.com/SatelliteQE/robottelo/pull/13596
=> [6.15.z] Adding new functionality for multi repo override

airgun/entities/virtwho_configure.py
Coverage [Bug 2158702](https://bugzilla.redhat.com/show_bug.cgi?id=2158702), realize read virt-who config Edit view page info support
Test Cases: PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest  ./tests/foreman/virtwho/ui/test_esx_sca.py -k test_positive_hypervisor_password_option --disable-pytest-warnings -q
2024-01-11 02:00:13 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
certs.cert_file is required in env main
============================================================================ 1 passed, 35 deselected, …
```
=> Bug 2158702:read virt-who config Edit view page info support

.github/workflows/auto_cherry_pick.yml
This PR backports changes from #1132.
Bumps [actions/github-script](https://github.com/actions/github-script) from 6 to 7.
- [Release notes](https://github.com/actions/github-script/releases)
- [Commits](https://github.com/actions/github-script/compare/v6...v7)
---
- dependency-name: actions/github-script dependency-type: direct:production update-type: version-update:semver-major ...
(cherry picked from commit da1bc3619f3f6917a268863a9dbc0540988f6409)
=> [6.12.z] Bump actions/github-script from 6 to 7

.github/workflows/auto_cherry_pick.yml
This PR backports changes from #1132.
Bumps [actions/github-script](https://github.com/actions/github-script) from 6 to 7.
- [Release notes](https://github.com/actions/github-script/releases)
- [Commits](https://github.com/actions/github-script/compare/v6...v7)
---
- dependency-name: actions/github-script dependency-type: direct:production update-type: version-update:semver-major ...
(cherry picked from commit da1bc3619f3f6917a268863a9dbc0540988f6409)
=> [6.13.z] Bump actions/github-script from 6 to 7

.github/workflows/auto_cherry_pick.yml
This PR backports changes from #1132.
Bumps [actions/github-script](https://github.com/actions/github-script) from 6 to 7.
- [Release notes](https://github.com/actions/github-script/releases)
- [Commits](https://github.com/actions/github-script/compare/v6...v7)
---
- dependency-name: actions/github-script dependency-type: direct:production update-type: version-update:semver-major ...
(cherry picked from commit da1bc3619f3f6917a268863a9dbc0540988f6409)
=> [6.14.z] Bump actions/github-script from 6 to 7

.github/workflows/auto_cherry_pick.yml
This PR backports changes from #1132.
Bumps [actions/github-script](https://github.com/actions/github-script) from 6 to 7.
- [Release notes](https://github.com/actions/github-script/releases)
- [Commits](https://github.com/actions/github-script/compare/v6...v7)
---
- dependency-name: actions/github-script dependency-type: direct:production update-type: version-update:semver-major ...
(cherry picked from commit da1bc3619f3f6917a268863a9dbc0540988f6409)
=> [6.15.z] Bump actions/github-script from 6 to 7

airgun/entities/virtwho_configure.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1136
Coverage [Bug 2158702](https://bugzilla.redhat.com/show_bug.cgi?id=2158702), realize read virt-who config Edit view page info support
Test Cases: PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest  ./tests/foreman/virtwho/ui/test_esx_sca.py -k test_positive_hypervisor_password_option --disable-pytest-warnings -q
2024-01-11 02:00:13 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
certs.cert_file is required in env main …
```
=> [6.13.z] Bug 2158702:read virt-who config Edit view page info support

airgun/entities/virtwho_configure.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1136
Coverage [Bug 2158702](https://bugzilla.redhat.com/show_bug.cgi?id=2158702), realize read virt-who config Edit view page info support
Test Cases: PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest  ./tests/foreman/virtwho/ui/test_esx_sca.py -k test_positive_hypervisor_password_option --disable-pytest-warnings -q
2024-01-11 02:00:13 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
certs.cert_file is required in env main …
```
=> [6.15.z] Bug 2158702:read virt-who config Edit view page info support

airgun/entities/virtwho_configure.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1136
Coverage [Bug 2158702](https://bugzilla.redhat.com/show_bug.cgi?id=2158702), realize read virt-who config Edit view page info support
Test Cases: PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest  ./tests/foreman/virtwho/ui/test_esx_sca.py -k test_positive_hypervisor_password_option --disable-pytest-warnings -q
2024-01-11 02:00:13 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
certs.cert_file is required in env main …
```
=> [6.14.z] Bug 2158702:read virt-who config Edit view page info support

.github/workflows/auto_cherry_pick.yml, .github/workflows/pull_request.yml
Failed cherry-pick of #1153
Fixes #1154
Bumps [actions/checkout](https://github.com/actions/checkout) from 2 to 4.
- [Release notes](https://github.com/actions/checkout/releases)
- [Changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- [Commits](https://github.com/actions/checkout/compare/v2...v4)
---
- dependency-name: actions/checkout dependency-type: direct:production update-type: version-update:semver-major ...
=> [6.15.z] Bump actions/checkout from 2 to 4

.github/workflows/auto_cherry_pick.yml, .github/workflows/pull_request.yml
Failed cherry-pick of https://github.com/SatelliteQE/airgun/pull/1153
Fixes https://github.com/SatelliteQE/airgun/issues/1156
Bumps [actions/checkout](https://github.com/actions/checkout) from 2 to 4.
- [Release notes](https://github.com/actions/checkout/releases)
- [Changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- [Commits](https://github.com/actions/checkout/compare/v2...v4)
---
- dependency-name: actions/checkout dependency-type: direct:production update-type: version-update:semver-major ...
=> [6.12.z] Bump actions/checkout from 2 to 4

.github/workflows/auto_cherry_pick_merge.yaml
This PR backports changes from #1135.
Bumps [pascalgn/automerge-action](https://github.com/pascalgn/automerge-action) from 0.15.6 to 0.16.2.
- [Release notes](https://github.com/pascalgn/automerge-action/releases)
- [Commits](https://github.com/pascalgn/automerge-action/compare/v0.15.6...v0.16.2)
---
- dependency-name: pascalgn/automerge-action dependency-type: direct:production update-type: version-update:semver-minor ...
(cherry picked from commit 318a029b29a583d291569bfde11223344194fe8d)
=> [6.15.z] Bump pascalgn/automerge-action from 0.15.6 to 0.16.2

.github/workflows/auto_cherry_pick_merge.yaml
This PR backports changes from #1135.
Bumps [pascalgn/automerge-action](https://github.com/pascalgn/automerge-action) from 0.15.6 to 0.16.2.
- [Release notes](https://github.com/pascalgn/automerge-action/releases)
- [Commits](https://github.com/pascalgn/automerge-action/compare/v0.15.6...v0.16.2)
---
- dependency-name: pascalgn/automerge-action dependency-type: direct:production update-type: version-update:semver-minor ...
(cherry picked from commit 318a029b29a583d291569bfde11223344194fe8d)
=> [6.14.z] Bump pascalgn/automerge-action from 0.15.6 to 0.16.2

airgun/__init__.py, airgun/entities/errata.py, airgun/views/errata.py
Manual cherry-pick of https://github.com/SatelliteQE/airgun/pull/1013
=> [6.13.z] Added possibility to search for debian errata

airgun/entities/host_new.py, airgun/views/host_new.py, airgun/widgets.py
- supports [robottelo #13767](https://github.com/SatelliteQE/robottelo/pull/13767)
- Add new host UI support for reading errata tab pagination.
- method could be extended to any content>{tab with pagination} in New Host UI page once working.
-Added new method `clear()` to `SearchInput` class (aigun/widgets.py)
-usage in the airgun view like so`view.content.errata.searchbar.clear()`
-Now using this in `apply_erratas()` method (entities/host_new.py), to clear the searchbar of any possible value present, when no search passed to` apply_erratas()`, meaning show and apply all errata with a blank searchbar.
-We also `clear` the searchbar in `apply_erratas()` after installing, that way any search value passed does not persist in the searchbar.
- ~When reading info from PF4Pagination object in …
=> host_new>content>errata tab pagination

airgun/entities/host_new.py, airgun/views/host_new.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1152
- supports [robottelo #13767](https://github.com/SatelliteQE/robottelo/pull/13767)
- Add new host UI support for reading errata tab pagination.
- method could be extended to any content>{tab with pagination} in New Host UI page once working.
-Added new method `clear()` to `SearchInput` class (aigun/widgets.py)
-usage in the airgun view like so`view.content.errata.searchbar.clear()`
-Now using this in `apply_erratas()` method (entities/host_new.py), to clear the searchbar of any possible value present, when no search passed to` apply_erratas()`, meaning show and apply all errata with a blank searchbar.
-We also `clear` the searchbar in `apply_erratas()` after installing, that way any search value passed does not persist in …
=> [6.15.z] host_new>content>errata tab pagination

airgun/views/task.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1204
Seems it was accidentally removed in https://github.com/SatelliteQE/airgun/pull/947
Result with changes:
```
pytest tests/foreman/ui/test_dashboard.py -k task_status
collected 5 items / 4 deselected / 1 selected                                                                     
tests/foreman/ui/test_dashboard.py .
```
=> [6.15.z] brought back task pagination

airgun/views/task.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1204
Seems it was accidentally removed in https://github.com/SatelliteQE/airgun/pull/947
Result with changes:
```
pytest tests/foreman/ui/test_dashboard.py -k task_status
collected 5 items / 4 deselected / 1 selected                                                                     
tests/foreman/ui/test_dashboard.py .
```
=> [6.14.z] brought back task pagination

airgun/views/task.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1204
Seems it was accidentally removed in https://github.com/SatelliteQE/airgun/pull/947
Result with changes:
```
pytest tests/foreman/ui/test_dashboard.py -k task_status
collected 5 items / 4 deselected / 1 selected                                                                     
tests/foreman/ui/test_dashboard.py .
```
=> [6.13.z] brought back task pagination

airgun/views/task.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1204
Seems it was accidentally removed in https://github.com/SatelliteQE/airgun/pull/947
Result with changes:
```
pytest tests/foreman/ui/test_dashboard.py -k task_status
collected 5 items / 4 deselected / 1 selected                                                                     
tests/foreman/ui/test_dashboard.py .
```
=> [6.12.z] brought back task pagination

.github/workflows/auto_cherry_pick_merge.yaml
The context of PRT was not correct, now after passing context it will work as expected.  I also found that the statuses api is not working with branch name which is `head_ref` so applying the head commit sha to make thing work. 
https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#list-commit-statuses-for-a-reference--parameters
=> Updated the correct context runner for Airgun

airgun/views/capsule.py, airgun/views/computeresource.py, airgun/views/dashboard.py, airgun/views/discoveryrule.py, airgun/views/package.py, airgun/views/repository.py, airgun/views/subnet.py, airgun/widgets.py
This change fixes around 90 tests in the bookmark component. The locator for bookmarks dropdown was not accurate for pf4 searchboxes, plus views were not updated to use pf4 search. The remaining legacy searchboxes continue to work.
Test result for component with pf4 searcbox:
```
pytest tests/foreman/ui/test_bookmarks.py -k  test_positive_end_to_end[Architecture]
=============================================== test session starts ===============================================                                                               
tests/foreman/ui/test_bookmarks.py .
```
Page with legacy searchbox:
```
pytest tests/foreman/ui/test_bookmarks.py -k  test_positive_end_to_end[product]
=============================================== test session starts …
```
=> pf4 bookmarks dropdown

airgun/views/host.py
An additional div was added in [foreman 3.9](https://github.com/theforeman/foreman/blame/84f33a3322be21da99d6ce3a8c33803f68ba5000/app/views/layouts/_application_content.html.erb#L11) (6.15.z)
So the form locator has to be adapted.
before
```
<div class="modal-body">
<div id="content">
<form class="form-horizontal well">
```
after
```
<div class="modal-body">
<div id="content">
<div class="pf-c-page__main-section pf-m-light rails-table-toolbar">
<form class="form-horizontal well">
```
=> Adapt to additional div in taxonomy mismatch locator

airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1206
An additional div was added in [foreman 3.9](https://github.com/theforeman/foreman/blame/84f33a3322be21da99d6ce3a8c33803f68ba5000/app/views/layouts/_application_content.html.erb#L11) (6.15.z)
So the form locator has to be adapted.
before
```
<div class="modal-body">
<div id="content">
<form class="form-horizontal well">
```
after
```
<div class="modal-body">
<div id="content">
<div class="pf-c-page__main-section pf-m-light rails-table-toolbar">
<form class="form-horizontal well">
```
=> [6.15.z] Adapt to additional div in taxonomy mismatch locator

airgun/entities/host.py, airgun/entities/job_invocation.py, airgun/views/host.py, airgun/views/job_invocation.py
In this PR I have added coverage for the Change Content Source option that is available to run on the hosts.
I have also fixed some broken locators in the job_invocation file and also extended it for some useful entities.
This PR is necessary for [Robottelo#14004](https://github.com/SatelliteQE/robottelo/pull/14004).
=> Added coverage for ChangeContentSource action on hosts

airgun/views/capsule.py, airgun/views/computeresource.py, airgun/views/dashboard.py, airgun/views/discoveryrule.py, airgun/views/package.py, airgun/views/repository.py, airgun/views/subnet.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1200
This change fixes around 90 tests in the bookmark component. The locator for bookmarks dropdown was not accurate for pf4 searchboxes, plus views were not updated to use pf4 search. The remaining legacy searchboxes continue to work.
Test result for component with pf4 searcbox:
```
pytest tests/foreman/ui/test_bookmarks.py -k  test_positive_end_to_end[Architecture]
=============================================== test session starts ===============================================                                                               
tests/foreman/ui/test_bookmarks.py .
```
Page with legacy searchbox:
```
pytest tests/foreman/ui/test_bookmarks.py -k  test_positive_end_to_end[product] …
```
=> [6.15.z] pf4 bookmarks dropdown

airgun/entities/host.py, airgun/entities/job_invocation.py, airgun/views/host.py, airgun/views/job_invocation.py
Manual cherry-pick of https://github.com/SatelliteQE/airgun/pull/1226
=> [6.14.z] Change content source cherry-pick

airgun/entities/hardware_model.py, airgun/views/hardware_model.py
For foreman 3.9 (6.15.z) the 'Actions' header string was removed (see picture):
The delete action is now accessible via an svg.
This should fix https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_hardwaremodel.py
=> Fix hardware model delete functionality (6.15.z)

airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1233
More sophisticated approach for clearing the search input.
Sometimes the previous value still remained in the search input,
even when `clear()` was called several times in a row.
This was probably a timing issue when running on a rel. fast browser machine.
=> [6.15.z] Navigation search: input clear fix

airgun/widgets.py
Vertical menu search buttons should use the correct PF4 button widgets.
This fixes the search clearing issue, when a search text value pops back
after clearing the search input via browser.clear()
The original PF4Button import alias was renamed to OUIAButton.
=> Navigation menu search: use proper PF4 button widget

.github/workflows/prt_labels.yml, .github/workflows/prt_result.yml
https://github.com/SatelliteQE/robottelo/pull/13979
https://github.com/SatelliteQE/robottelo/pull/14093
1. Currently, the labels PRT-Passed and PRT-Failed are added based on the results of the Pull Request Testing (PRT). However, when contributors update the pull request with new commits, these labels might remain, leading to potential confusion. There is a need to automatically remove these labels when new commits are added to the pull request.
2. Currently, the PRT result gets clean after a new commit and there is no way for PR to know what happened with the result. PRT passed/failed labels also need to be added automatically this helps in reviewing the PR quickly and merging them
1. Add the dispatch workflow that takes care of this thing from the Jenkins CI update the GitHub comment …
=> adding the PRT result and labels on github comment

airgun/views/repository.py
to enable debian repo testing for orcharhino.
=> Add debian repository to views

.github/workflows/prt_labels.yml, .github/workflows/prt_result.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1239
https://github.com/SatelliteQE/robottelo/pull/13979
https://github.com/SatelliteQE/robottelo/pull/14093
1. Currently, the labels PRT-Passed and PRT-Failed are added based on the results of the Pull Request Testing (PRT). However, when contributors update the pull request with new commits, these labels might remain, leading to potential confusion. There is a need to automatically remove these labels when new commits are added to the pull request.
2. Currently, the PRT result gets clean after a new commit and there is no way for PR to know what happened with the result. PRT passed/failed labels also need to be added automatically this helps in reviewing the PR quickly and merging them
1. Add the dispatch workflow that takes …
=> [6.13.z] adding the PRT result and labels on github comment

.github/workflows/prt_labels.yml
some more updated on PRT label checks, adding conditional statements.
=> some more updated on PRT label checks

airgun/views/host.py
Adding this sleep ensures, that before_fill behaves correctly and detects disabled components correctly.
=> Improve stability of before_fill function

airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1266
Adding this sleep ensures, that before_fill behaves correctly and detects disabled components correctly.
=> [6.14.z] Improve stability of before_fill function

airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1266
Adding this sleep ensures, that before_fill behaves correctly and detects disabled components correctly.
=> [6.15.z] Improve stability of before_fill function

airgun/entities/contenthost.py
Labels: master, 6.15.z  
See also: https://github.com/SatelliteQE/airgun/pull/1281#issuecomment-2019926059
relevant test:
tests/foreman/ui/test_repository.py::test_positive_create_as_non_admin_user
=> Rework is_displayed logic for contenthost

airgun/entities/host_new.py, airgun/views/host_new.py
=> add/update host_new entities & views

airgun/entities/host_new.py, airgun/views/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1300
=> [6.15.z] add/update host_new entities & views

airgun/entities/redhat_repository.py, airgun/views/redhat_repository.py
**Problem:** `Search box` and `search button` for `Content > Red Hat Repositories` page were not found, rather script was selecting left pannel search box. Apart from this, test was not waiting for page to load before searching on `Red Hat Repositories` page.
**Solution:** The updated `XPaths` and added `wait_for` method before searching any rh repositories.
**Note:** 
Correspondig Robottelo PR https://github.com/SatelliteQE/robottelo/pull/14673
=> redhat_repositories search box & button xpath, add wait_for in search

airgun/views/product.py, airgun/views/repository.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1311
While fixing some HTTP Proxy UI failures I discovered that in 6.15 and stream/6.16 the `Discover` button is not hit since it collides with the vertical nav menu search. Narrowing down the locator helps.
Also, `session.repository.search(product_name, repo_name)` now returns `None` since #1200 was merged. It does not feel like a PF4 searchbox in 6.15 and stream 
Turning it back helped locally.
=> [6.15.z] Fixes in repo discovery and search

airgun/views/product.py, airgun/views/repository.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1311
While fixing some HTTP Proxy UI failures I discovered that in 6.15 and stream/6.16 the `Discover` button is not hit since it collides with the vertical nav menu search. Narrowing down the locator helps.
Also, `session.repository.search(product_name, repo_name)` now returns `None` since #1200 was merged. It does not feel like a PF4 searchbox in 6.15 and stream 
Turning it back helped locally.
=> [6.14.z] Fixes in repo discovery and search

airgun/views/product.py, airgun/views/repository.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1311
While fixing some HTTP Proxy UI failures I discovered that in 6.15 and stream/6.16 the `Discover` button is not hit since it collides with the vertical nav menu search. Narrowing down the locator helps.
Also, `session.repository.search(product_name, repo_name)` now returns `None` since #1200 was merged. It does not feel like a PF4 searchbox in 6.15 and stream 
Turning it back helped locally.
=> [6.13.z] Fixes in repo discovery and search

airgun/entities/host_new.py
=> added properties for airgun

airgun/entities/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1325
=> [6.14.z] added properties for airgun

airgun/entities/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1347
changes added which will help to remove single ansible role from host.
=> [6.14.z] added changes in host_new entities

airgun/entities/host_new.py
I have extended host_new entity for a function that returns a dictionary with counts of the errata types 
['Security', 'Bugfix', 'Enhancement'].
=> Added entity that returns counts of the errata types

.pre-commit-config.yaml, airgun/browser.py, airgun/exceptions.py, airgun/fixtures.py, airgun/navigation.py, airgun/session.py, docs/conf.py
updates:
- [github.com/psf/black: 24.3.0 → 24.4.0](https://github.com/psf/black/compare/24.3.0...24.4.0)
- [github.com/astral-sh/ruff-pre-commit: v0.3.5 → v0.3.7](https://github.com/astral-sh/ruff-pre-commit/compare/v0.3.5...v0.3.7)
fixes #1353
=> [6.15.z] [pre-commit.ci] pre-commit autoupdate

airgun/entities/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1337
I have extended host_new entity for a function that returns a dictionary with counts of the errata types 
['Security', 'Bugfix', 'Enhancement'].
=> [6.15.z] Added entity that returns counts of the errata types

airgun/entities/host.py
`EditHost` navigation step now waits for the view to be displayed.
This is needed for an edge case, when editing a host with empty values, i.e.,
`host.update(client.hostname, {})`,
is too fast and the view is not yet fully loaded.
=> edit host view wait until displayed

airgun/entities/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1362
`EditHost` navigation step now waits for the view to be displayed.
This is needed for an edge case, when editing a host with empty values, i.e.,
`host.update(client.hostname, {})`,
is too fast and the view is not yet fully loaded.
=> [6.14.z] edit host view wait until displayed

airgun/entities/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1362
`EditHost` navigation step now waits for the view to be displayed.
This is needed for an edge case, when editing a host with empty values, i.e.,
`host.update(client.hostname, {})`,
is too fast and the view is not yet fully loaded.
=> [6.13.z] edit host view wait until displayed

airgun/entities/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1362
`EditHost` navigation step now waits for the view to be displayed.
This is needed for an edge case, when editing a host with empty values, i.e.,
`host.update(client.hostname, {})`,
is too fast and the view is not yet fully loaded.
=> [6.15.z] edit host view wait until displayed

airgun/entities/contenthost.py, airgun/entities/host_new.py
- Update `search_errata` on contenthost, to correctly navigate to 'LegacyDetails' for chost.
- `get_errata_table`: Add support to New Host > content > errata tab:
Return all errata entries displayed in the table.
can search and filter by optional params, otherwise display all errata present on host.
- Supports [Robottelo#14926](https://github.com/SatelliteQE/robottelo/pull/14926) <- PRT Demonstration
=> Add fetching of all errata entries from new host page, fix search of errata on legacy chost page

airgun/entities/contenthost.py, airgun/entities/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1374
- Update `search_errata` on contenthost, to correctly navigate to 'LegacyDetails' for chost.
- `get_errata_table`: Add support to New Host > content > errata tab:
Return all errata entries displayed in the table.
can search and filter by optional params, otherwise display all errata present on host.
=> [6.15.z] Add fetching of all errata entries from new host page, fix search of errata on legacy chost page

airgun/entities/subscription.py, airgun/helpers/base.py, airgun/widgets.py
=> fixing make-docs issue with some update in code

airgun/entities/subscription.py, airgun/helpers/base.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1391
=> [6.15.z] fixing make-docs issue with some update in code

airgun/entities/subscription.py, airgun/helpers/base.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1391
=> [6.14.z] fixing make-docs issue with some update in code

airgun/entities/subscription.py, airgun/helpers/base.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1391
=> [6.13.z] fixing make-docs issue with some update in code

airgun/entities/subscription.py, airgun/helpers/base.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1391
=> [6.12.z] fixing make-docs issue with some update in code

airgun/entities/subscription.py, airgun/views/subscription.py
REF - Notification when manifest is expiring soon
https://bugzilla.redhat.com/show_bug.cgi?id=2075163#c23
Add functionality in entities and view to read mafifest expiring soon message.
Robottelo PR-https://github.com/SatelliteQE/robottelo/pull/15003
=> added new support for feature  manifest expires soon

airgun/session.py
=> browser teardown fix at session exit

airgun/session.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1390
=> [6.12.z] browser teardown fix at session exit

airgun/entities/contentview_new.py, airgun/views/contentview_new.py
Airgun Support for the Versions screen of CV UI - supports reading/searching all tables. 
Robottelo PR exercising this: https://github.com/SatelliteQE/robottelo/pull/13478
=> CV  UI - Add versions screen, and capability to search/read all tables

airgun/entities/subscription.py, airgun/views/subscription.py
**Problem**
Content - Subscription page search box xpath unable to locate due to wrong xpath
**Solution**
This updated xpath will work as expected.
**Note**
Robottelo changes from the PR [[Link]](https://github.com/SatelliteQE/robottelo/pull/15237) are not dependant these changes as I have updated some part of test case ( `test_positive_access_with_non_admin_user_with_manifest`) which won't search for any Subscription
=> 6.15.z-fix subscription search box xpath

airgun/entities/subscription.py, airgun/views/subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1405
**Problem**
Content - Subscription page search box xpath unable to locate due to wrong xpath
**Solution**
This updated xpath will work as expected.
**Note**
Robottelo changes from the PR [[Link]](https://github.com/SatelliteQE/robottelo/pull/15237) are not dependant these changes as I have updated some part of test case ( `test_positive_access_with_non_admin_user_with_manifest`) which won't search for any Subscription
=> [6.14.z] 6.15.z-fix subscription search box xpath

airgun/session.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1390
=> [6.15.z] browser teardown fix at session exit

airgun/session.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1413
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1390
=> [6.14.z] browser teardown fix at session exit

airgun/session.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1413
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1390
=> [6.13.z] browser teardown fix at session exit

.github/dependabot.yml
New 6.16.z downstream and master points to stream that is 6.17
- Dependabot.yaml cherrypicks to 6.16.z
=> [master]: Changes for 6.16.z new branch

airgun/entities/host.py, airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1384
For PR https://github.com/SatelliteQE/robottelo/pull/15110
=> [6.15.z] Basic host statuses page

airgun/views/contenthost.py
contenthost legacy ui get virtual host support
This PR influence the PR https://github.com/SatelliteQE/robottelo/pull/15064
Cases Run:  PASS
```
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/foreman/virtwho/ui/test_esx_sca.py -k test_positive_deploy_configure_by_id_script --disable-pytest-warnings -q
2 passed, 34 deselected, 29 warnings in 539.09s (0:08:59)
2024-05-21 00:27:04 - robottelo - WARNING - missing grid_url or session_id. unable to clean video files.
```
=> contenthost legacy ui get virtual host support

airgun/entities/subscription.py, airgun/views/subscription.py
Sub-task of **6.14.z Airgun PR https://github.com/SatelliteQE/airgun/pull/1412** *
**Problem**
PRT is failing for 6.14.z CP PR https://github.com/SatelliteQE/robottelo/pull/15276 (Original 6.15.z robottelo PR https://github.com/SatelliteQE/robottelo/pull/15237)
**Actual issue**
Subscription table is not loading within existing 10s of timeout
**Solution**
Increasing timeout value would help to fix this issue
**Related PR**
6.15.z Airgun PR https://github.com/SatelliteQE/airgun/pull/1405
**6.14.z Airgun PR https://github.com/SatelliteQE/airgun/pull/1412** *
**PRT Comment**
```
pytest: tests/foreman/ui/test_subscription.py -k 'test_positive_access_with_non_admin_user_with_manifest'
robottelo: 15276
```
=> 6.14.z changes - increse timeout for read subscription

airgun/views/contenthost.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1389
contenthost legacy ui get virtual host support
This PR influence the PR https://github.com/SatelliteQE/robottelo/pull/15064
Cases Run:  PASS
```
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/foreman/virtwho/ui/test_esx_sca.py -k test_positive_deploy_configure_by_id_script --disable-pytest-warnings -q
2 passed, 34 deselected, 29 warnings in 539.09s (0:08:59)
2024-05-21 00:27:04 - robottelo - WARNING - missing grid_url or session_id. unable to clean video files.
```
=> [6.14.z] contenthost legacy ui get virtual host support

airgun/views/contenthost.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1389
contenthost legacy ui get virtual host support
This PR influence the PR https://github.com/SatelliteQE/robottelo/pull/15064
Cases Run:  PASS
```
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/foreman/virtwho/ui/test_esx_sca.py -k test_positive_deploy_configure_by_id_script --disable-pytest-warnings -q
2 passed, 34 deselected, 29 warnings in 539.09s (0:08:59)
2024-05-21 00:27:04 - robottelo - WARNING - missing grid_url or session_id. unable to clean video files.
```
=> [6.15.z] contenthost legacy ui get virtual host support

airgun/entities/all_hosts.py, airgun/views/all_hosts.py
Adds support for All Hosts page Manage Columns functionality. Leverages heavily the work done for the similar functionality on the older Hosts page. 
Tested by: https://github.com/SatelliteQE/robottelo/pull/15383
=> Manage columns support for All Hosts

airgun/entities/contenthost.py, airgun/entities/errata.py, airgun/entities/host_new.py, airgun/views/errata.py, airgun/views/host_new.py
Supports robottelo [#15085](https://github.com/SatelliteQE/robottelo/pull/15085)
- Add option to install errata to multiple/all hosts listed, in ContentTypes > Errata > details > ContentHosts tab
- Fix legacy chost errata install and package search methods, to use `LegacyDetails` page
- Some locators updated
=> Errata install, and legacy chost methods

airgun/views/contenthost.py
Subscription info and System Purpose Status have been removed in stream. Removing them in views so they no longer cause issues with invalid locators 
Also removed "show_all" no longer an option... and updated the logic in the .read() method
=> Removing outdating views for hostcontent sca tests

.pre-commit-config.yaml, airgun/entities/hostgroup.py, airgun/views/hostgroup.py, airgun/widgets.py
Add and remove functionality for ansible roles in hostgroup
:steps:
1. Import all roles available by default.
2. Assign ansible role while create a hostgroup
3. Assign ansible role after create a hostgroup
4. Remove previously added ansible roles from the hostgroup
:expectedresults: The Ansible Role is successfully add and remove to the hostgroup.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/14672
=> adding and removing ansible role

airgun/entities/hostgroup.py, airgun/views/hostgroup.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1424
Add and remove functionality for ansible roles in hostgroup
:steps:
1. Import all roles available by default.
2. Assign ansible role while create a hostgroup
3. Assign ansible role after create a hostgroup
4. Remove previously added ansible roles from the hostgroup
:expectedresults: The Ansible Role is successfully add and remove to the hostgroup.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/14672
=> [6.15.z] adding and removing ansible role

airgun/entities/contenthost.py, airgun/entities/errata.py, airgun/entities/host_new.py, airgun/views/errata.py, airgun/views/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1387
Supports robottelo [#15483](https://github.com/SatelliteQE/robottelo/pull/15483) << 6.15.z CP of original PR
- Add option to install errata to multiple/all hosts listed, in ContentTypes > Errata > details > ContentHosts tab
- Fix legacy chost errata install and package search methods, to use `LegacyDetails` page
- Some locators updated
=> [6.15.z] Errata install, and legacy chost methods

airgun/entities/subscription.py
- Considering newly implemented 6.16.0 feature/RFE "Notification when manifest is going to expire" and reported bug "Manifest expiration date (year) shows older for all manifest" it is neccessary to check manifest expiration message is disappearing when manifest upload very first time into organization.
- It was left behind because related https://github.com/SatelliteQE/airgun/pull/1385 merged very early phase of testing.
- During phoenix qe team discussion, we have decided to open new robottelo PR and airgun PR to validate manifest expiration header message functionality before updating settings value (expire_soon_days)
Implemented function will return True or False base on availability of header message on manage manifest modal box.
Robottelo …
=> Manifest expiration date appearance of header and message

airgun/views/host.py
The `HostsView` `Name` table column XPath was missing leading '.' character,
which caused that all host rows that were returned, had the same Name value,
equal to the first table row host Name.
=> hosts table: Name locator fix

airgun/views/hostgroup.py
Ansible test was failing due to `no widget name Pagination` error while editing the hostgroup, hence adding pagination for ansible_roles in HostGroupEditView
=> Add pagination for ansible_roles in HostGroupEditView

airgun/views/hostgroup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1455
Ansible test was failing due to `no widget name Pagination` error while editing the hostgroup, hence adding pagination for ansible_roles in HostGroupEditView
=> [6.15.z] Add pagination for ansible_roles in HostGroupEditView

airgun/views/hostgroup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1455
Ansible test was failing due to `no widget name Pagination` error while editing the hostgroup, hence adding pagination for ansible_roles in HostGroupEditView
=> [6.14.z] Add pagination for ansible_roles in HostGroupEditView

airgun/views/host.py
A dot (.) was added before the locator, causing the host not to navigate on the UI page and resulting in a JavaScript error. I removed this dot (.), and now the navigation to the given host works correctly.
Dependent PR - https://github.com/SatelliteQE/robottelo/pull/15489
=> removed (.) which fails to navigate to host

airgun/entities/virtwho_configure.py
As navigator name has been changed from  'Virt-who configurations' to  'Virt-who Configurations'. so update it to resolve NavSelectionNotFound: ('Infrastructure', 'Virt-who configurations') not found in navigation tree issue on Satellite6.16 stream.
Test Case: PASS
```
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/foreman/virtwho/ui/test_hyperv_sca.py -k test_positive_hypervisor_id_option --disable-pytest-warnings -q
1 passed, 2 deselected, 7 warnings in 390.24s (0:06:30)
```
=> Update Infrastructure-Virt-who Configurations navigator name

airgun/widgets.py
The Hosts table HTML contains multiple duplicate columns that are hidden, like *Name, Model, Operating system*, etc.
On the eye, the rendered result looks and behaves correctly,
however these hidden columns are causing the widget `airgun.widgets.SatTable` to behave not fully correctly.
This flaw started to fully manifest by merging PR https://github.com/SatelliteQE/airgun/pull/1453
where the `SatTable` widget interacted with the hidden columns instead of the visible ones (and sometimes vice versa).
The `SatTable` widget is modified to ignore all hidden headers and columns in the table.
=> ignore all hidden columns in SatTable widget

airgun/widgets.py
when the progress bar disappears between the
is_displayed query and the current_progress query
a NoSuchElement exception is raised
=> Fix race condition in PF4 progressbar

airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1465
The Hosts table HTML contains multiple duplicate columns that are hidden, like *Name, Model, Operating system*, etc.
On the eye, the rendered result looks and behaves correctly,
however these hidden columns are causing the widget `airgun.widgets.SatTable` to behave not fully correctly.
This flaw started to fully manifest by merging PR https://github.com/SatelliteQE/airgun/pull/1453
where the `SatTable` widget interacted with the hidden columns instead of the visible ones (and sometimes vice versa).
The `SatTable` widget is modified to ignore all hidden headers and columns in the table.
=> [6.15.z] ignore all hidden columns in SatTable widget

airgun/views/host.py
Reverted removal of taxonomy in views.host.py. 
The issue with CI check failing because of bug in sphinx-autoapi which was fixed in v3.2.1
=> Revert removal of taxonomy from host module

airgun/entities/all_hosts.py, airgun/views/all_hosts.py
Adds support for Build Management in All Hosts page, as well as updates the dropdown to a Menu, matching recent changes from the dev side.
Note: Not all of these changes appear to have made it into stream, so there will likely need to be more work with this component.
=> [6.16] Adjust all hosts to use menu, add support for Build Management

airgun/entities/file.py, airgun/session.py, airgun/views/file.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1426
Adds Views/Entities for the Content -> Content Types -> File screen. 
Supporting this robottelo PR:
=> [6.15.z] Add support for File page in Content section of UI

airgun/views/provisioning_template.py
This small fix ensures that the table and its values are correctly located and function as expected. Previously, the locator was not properly configured, resulting in only the table being fetched without retrieving its values.
=> Table locator updated to get value from "Provisioning Templates" table

airgun/views/provisioning_template.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1494
This small fix ensures that the table and its values are correctly located and function as expected. Previously, the locator was not properly configured, resulting in only the table being fetched without retrieving its values.
=> [6.15.z] Table locator updated to get value from "Provisioning Templates" table

airgun/views/provisioning_template.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1494
This small fix ensures that the table and its values are correctly located and function as expected. Previously, the locator was not properly configured, resulting in only the table being fetched without retrieving its values.
=> [6.14.z] Table locator updated to get value from "Provisioning Templates" table

airgun/views/job_invocation.py
Dependant PR https://github.com/SatelliteQE/robottelo/pull/15595
=> Add ansible_collections_path in job invocation advanced_fields

airgun/widgets.py
Backport of 1661b6ce61639d4465bdbd24b37f4bde889d5ce0
=> Cherry pick 6.15.z 1661b6ce61639d4465bdbd24b37f4bde889d5ce0

pyproject.toml
Fixing:
```
$ ruff check .
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'fixable' -> 'lint.fixable'
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
- 'flake8-pytest-style' -> 'lint.flake8-pytest-style'
- 'isort' -> 'lint.isort'
- 'mccabe' -> 'lint.mccabe'
- 'per-file-ignores' -> 'lint.per-file-ignores'
warning: `PGH001` has been remapped to `S307`.
warning: `TRY200` has been remapped to `B904`.
```
I removed `PGH001` as `S307` is in the `select` section already
=> Fix ruff deprecation warnings

pyproject.toml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1500
Fixing:
```
$ ruff check .
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'fixable' -> 'lint.fixable'
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
- 'flake8-pytest-style' -> 'lint.flake8-pytest-style'
- 'isort' -> 'lint.isort'
- 'mccabe' -> 'lint.mccabe'
- 'per-file-ignores' -> 'lint.per-file-ignores'
warning: `PGH001` has been remapped to `S307`.
warning: `TRY200` has been remapped to `B904`.
```
I removed `PGH001` as `S307` is in the `select` section already
=> [6.15.z] Fix ruff deprecation warnings

pyproject.toml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1500
Fixing:
```
$ ruff check .
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'fixable' -> 'lint.fixable'
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
- 'flake8-pytest-style' -> 'lint.flake8-pytest-style'
- 'isort' -> 'lint.isort'
- 'mccabe' -> 'lint.mccabe'
- 'per-file-ignores' -> 'lint.per-file-ignores'
warning: `PGH001` has been remapped to `S307`.
warning: `TRY200` has been remapped to `B904`.
```
I removed `PGH001` as `S307` is in the `select` section already
=> [6.14.z] Fix ruff deprecation warnings

pyproject.toml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1500
Fixing:
```
$ ruff check .
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'fixable' -> 'lint.fixable'
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
- 'flake8-pytest-style' -> 'lint.flake8-pytest-style'
- 'isort' -> 'lint.isort'
- 'mccabe' -> 'lint.mccabe'
- 'per-file-ignores' -> 'lint.per-file-ignores'
warning: `PGH001` has been remapped to `S307`.
warning: `TRY200` has been remapped to `B904`.
```
I removed `PGH001` as `S307` is in the `select` section already
=> [6.13.z] Fix ruff deprecation warnings

airgun/entities/all_hosts.py, airgun/views/all_hosts.py, airgun/views/common.py, airgun/widgets.py
Adds support for the Bulk CVE Assignment action on the All Hosts page, as well as implements a PF4 version of the Lifecycle Environment and Bulk LCE selector widgets. Should be 100% usable on any React page going forward with that functionality. 
Supports: https://github.com/SatelliteQE/robottelo/pull/15976
=> [6.16]Add support for CVE modal and PF4 version of LCE Selector

airgun/entities/job_invocation.py, airgun/views/job_invocation.py
New view and navigation was added for the first part of the new job invocation details page.
This feature is still an experimantal feature/tech preview and it is not yet fully completed.
Other content will be added in later phases.
=> New job invocation details page

airgun/views/provisioning_template.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1494
This small fix ensures that the table and its values are correctly located and function as expected. Previously, the locator was not properly configured, resulting in only the table being fetched without retrieving its values.
=> [6.13z cp] Table locator updated to get value from "Provisioning Templates" table

airgun/entities/discoveryrule.py, airgun/views/discoveryrule.py
- Updated the views with Table() widget instead SatTable(), to read all the table values.
- Added entities to read the page after deleting discovery rules table.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/15783
=> fixed in method for discovery rule and updated it's entities

airgun/entities/discoveryrule.py, airgun/views/discoveryrule.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1480
- Updated the views with Table() widget instead SatTable(), to read all the table values.
- Added entities to read the page after deleting discovery rules table.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/15783
=> [6.16.z] fixed in method for discovery rule and updated it's entities

airgun/entities/oscapreport.py, airgun/session.py, airgun/views/common.py, airgun/views/oscapreport.py, airgun/widgets.py
Required by https://github.com/SatelliteQE/robottelo/pull/15491
Also, added limit of rows to read because sometimes you don't need them all and it takes a while to read.
=> SCAP report and remediation

airgun/entities/all_hosts.py, airgun/views/all_hosts.py, airgun/views/common.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1514
Adds support for the Bulk CVE Assignment action on the All Hosts page, as well as implements a PF4 version of the Lifecycle Environment and Bulk LCE selector widgets. Should be 100% usable on any React page going forward with that functionality. 
Supports: https://github.com/SatelliteQE/robottelo/pull/15976
=> [6.16.z] [6.16]Add support for CVE modal and PF4 version of LCE Selector

airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1544
null
=> [6.16.z] Fix sattable locators

airgun/views/sync_templates.py, airgun/widgets.py
fixing submit button definition for templates, also adding warning alert to the list of registered validations. The test failed for non-airgun related reason, but airgun did not stop on validation as UI shows only a warning-level box, so the test timed out without a meaningful message.
=> validations with warnings too

airgun/views/sync_templates.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1543
fixing submit button definition for templates, also adding warning alert to the list of registered validations. The test failed for non-airgun related reason, but airgun did not stop on validation as UI shows only a warning-level box, so the test timed out without a meaningful message.
=> [6.16.z] validations with warnings too

airgun/views/sync_templates.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1543
fixing submit button definition for templates, also adding warning alert to the list of registered validations. The test failed for non-airgun related reason, but airgun did not stop on validation as UI shows only a warning-level box, so the test timed out without a meaningful message.
=> [6.15.z] validations with warnings too

airgun/entities/task.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1555
in automation, the task details consistently take a bit of time to load, the read action then fails. It's not really reproducible locally, adding a bit of wait in hope to improve the situation
=> [6.16.z] wait for task details to appear

airgun/entities/task.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1555
in automation, the task details consistently take a bit of time to load, the read action then fails. It's not really reproducible locally, adding a bit of wait in hope to improve the situation
=> [6.14.z] wait for task details to appear

airgun/entities/dashboard.py
similar to https://github.com/SatelliteQE/airgun/pull/1555
=> wait for a dashboard card to load

airgun/entities/hostcollection.py
This PR is part of the fix that is made in https://github.com/SatelliteQE/robottelo/pull/16379
It is 6.15.z specific because in 6.15 when running the install package action via customized REX there is a difference between 6.15 and 6.16 because it uses an old job invocation page that has not been cherry-picked in airgun, so little hacky solution is to hardcode the submit button which can't be found to the entity and submit the prefilled form afterwards. This little fix makes the test work.
=> [6.15.z] Fix hostCollection entities

airgun/entities/job_invocation.py, airgun/views/dynflowconsole.py, airgun/views/job_invocation.py, airgun/views/task.py
- When enabling debug mode on Satellite, the task is generating an output log for all hosts present on the Job.
- The host execution log is showing the debug log for all hosts present on the inventory instead of just the expected host.
Solution : -
- Below automation check the host execution log should show the debug log for expected host instead of the all host present in the inventory.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/15918
=> Check dynflow console output for host

airgun/entities/discoveryrule.py, airgun/views/discoveryrule.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1480
- Updated the views with Table() widget instead SatTable(), to read all the table values.
- Added entities to read the page after deleting discovery rules table.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/15783
=> [6.15.z] fixed in method for discovery rule and updated it's entities

airgun/entities/job_invocation.py, airgun/views/dynflowconsole.py, airgun/views/job_invocation.py, airgun/views/task.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1522
- When enabling debug mode on Satellite, the task is generating an output log for all hosts present on the Job.
- The host execution log is showing the debug log for all hosts present on the inventory instead of just the expected host.
Solution : -
- Below automation check the host execution log should show the debug log for expected host instead of the all host present in the inventory.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/15918
=> [6.16.z] Check dynflow console output for host

airgun/entities/job_invocation.py, airgun/views/dynflowconsole.py, airgun/views/job_invocation.py, airgun/views/task.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1522
When enabling debug mode on Satellite, the task is generating an output log for all hosts present on the Job.
The host execution log is showing the debug log for all hosts present on the inventory instead of just the expected host.
Solution : -
Below automation check the host execution log should show the debug log for expected host instead of the all host present in the inventory.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/16529
Fixes: https://github.com/SatelliteQE/airgun/issues/1573
=> [6.14z CP] Check dynflow console output for host

airgun/entities/job_invocation.py, airgun/views/dynflowconsole.py, airgun/views/job_invocation.py, airgun/views/task.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1522
When enabling debug mode on Satellite, the task is generating an output log for all hosts present on the Job.
The host execution log is showing the debug log for all hosts present on the inventory instead of just the expected host.
Solution : -
Below automation check the host execution log should show the debug log for expected host instead of the all host present in the inventory.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/16527
Fixes: https://github.com/SatelliteQE/airgun/issues/1572
=> [6.15.z] Check dynflow console output for host

airgun/views/report_template.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1539
Adding Installability views to the ReportTemplateGenerateView Class
=> [6.16.z] [Comp Eval] Add installability to generate views

.pre-commit-config.yaml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1532
updates:
- [github.com/astral-sh/ruff-pre-commit: v0.6.1 → v0.6.8](https://github.com/astral-sh/ruff-pre-commit/compare/v0.6.1...v0.6.8)
=> [6.16.z] [pre-commit.ci] pre-commit autoupdate

.github/workflows/auto_cherry_pick_merge.yaml
This PR backport changes from #1575
=> [6.15.z] Bump pascalgn/automerge-action from 0.16.3 to 0.16.4 (#1575)

.github/workflows/auto_cherry_pick_merge.yaml
This PR backports changes from #1575
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
(cherry picked from commit 1728a06be2d1e198d2c203a2e65d12cf21247ef6)
=> [6.13.z] Bump pascalgn/automerge-action from 0.16.3 to 0.16.4 (#1575)

airgun/entities/all_hosts.py, airgun/entities/host.py
Add an entity `read_filled_searchbox` to the `host.py` (old hosts UI) and `all_hosts.py` (new hosts UI) so that it can be used in the automation.
Usage:
- Old UI
```python
with target_sat.ui_session() as session:
session.host.search('some_search_string')
read_searchbox_value = session.host.read_filled_searchbox()
print(read_searchbox_value)
```
- New UI
```python
with target_sat.ui_session() as session:
session.all_hosts.search('some_search_string')
read_searchbox_value = session.all_hosts.read_filled_searchbox()
print(read_searchbox_value)
```
=> Add entity that reads filled searchbox on new and old hosts pages

airgun/entities/contentview_new.py, airgun/views/common.py, airgun/views/contentview_new.py, airgun/widgets.py
This PR is adding support for Publishing CVs, Promoting CVs, Adding Content to CVs, among other changes that are required to bring this work up to current formatting standards, as well as function properly. 
Testing of various methods added here in this PR: https://github.com/SatelliteQE/robottelo/pull/16238
=> CV UI - Promote, Publish, Add Content 

airgun/entities/contentview_new.py, airgun/views/common.py, airgun/views/contentview_new.py, airgun/widgets.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/939
This PR is adding support for Publishing CVs, Promoting CVs, Adding Content to CVs, among other changes that are required to bring this work up to current formatting standards, as well as function properly. 
Testing of various methods added here in this PR: https://github.com/SatelliteQE/robottelo/pull/16238
=> [6.16.z] CV UI - Promote, Publish, Add Content 

airgun/entities/host_new.py, airgun/views/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1347
changes added which will help to remove single ansible role from host.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/16096
=> [6.13.z] added changes in host_new entities

airgun/entities/contentview_new.py, airgun/views/contentview_new.py
To support [robottelo 16283](https://github.com/SatelliteQE/robottelo/pull/16283).
Pulled in @sambible 's additions for New CV UI work in #939 and rebased
Includes fixes for Navigation failures seen in PRT, 'Version' tab, 'Publish' button, `read_version_table()` method, 
and handle empty/no table in `search()` method, when there are no CVs in the Org
=> New CV UI - ContentView and ContentViewVersion Delete

airgun/entities/contentview_new.py, airgun/views/contentview_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1592
To support [robottelo 16283](https://github.com/SatelliteQE/robottelo/pull/16283).
Pulled in @sambible 's additions for New CV UI work in #939 and rebased
Includes fixes for Navigation failures seen in PRT, 'Version' tab, 'Publish' button, `read_version_table()` method, 
and handle empty/no table in `search()` method, when there are no CVs in the Org
=> [6.16.z] New CV UI - ContentView and ContentViewVersion Delete

airgun/views/ansible_variable.py
Previously, the test case was failing because it couldn’t retrieve the locator. I updated the locator to ensure it fetches the correct value when creating the Ansible variable.
=> update ansible variable matcher_value locator

airgun/views/ansible_variable.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1607
Previously, the test case was failing because it couldn’t retrieve the locator. I updated the locator to ensure it fetches the correct value when creating the Ansible variable.
=> [6.14.z] update ansible variable matcher_value locator

airgun/views/ansible_variable.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1607
Previously, the test case was failing because it couldn’t retrieve the locator. I updated the locator to ensure it fetches the correct value when creating the Ansible variable.
=> [6.15.z] update ansible variable matcher_value locator

airgun/views/ansible_variable.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1607
Previously, the test case was failing because it couldn’t retrieve the locator. I updated the locator to ensure it fetches the correct value when creating the Ansible variable.
=> [6.16.z] update ansible variable matcher_value locator

airgun/entities/host_new.py
Occasionally see no such element exception for ErrataManagement CI results, 
in `get_packages()` method on `view.content.packages.select()`
locally it runs without issue, but we should wait for the packages tab to appear before selecting it, after we navigate to the page.
See for prt [Robottelo#16814](https://github.com/SatelliteQE/robottelo/pull/16814)
two tests using this method, New Host UI > Installed Packages tab > read table :
- tests/foreman/ui/test_errata.py:: test_positive_apply_for_all_hosts (upgrade)
- tests/foreman/ui/test_host.py:: test_positive_update_delete_package (rhel8 only) _Fails in setup_
```
Error Message
selenium.common.exceptions.NoSuchElementException: Message: Could not find an element Locator(by='xpath', locator='.//div[contains(@class, …
```
=> Fix inconsistently failing Errata UI, checking New Host > Installed Packages > table

airgun/views/capsule.py
Just adding the reclaim_space_warning node to the capsule view so that we can test its hiding from robottelo.
=> Add reclaim_space_warning node to the capsule view

airgun/views/capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1615
Just adding the reclaim_space_warning node to the capsule view so that we can test its hiding from robottelo.
=> [6.16.z] Add reclaim_space_warning node to the capsule view

airgun/entities/about.py, airgun/entities/fact_value.py, airgun/entities/global_parameter.py, airgun/session.py, airgun/views/about.py, airgun/views/common.py, airgun/views/global_parameter.py
Historically, after a Satellite release, we have found that the documentation links on Satellite pages were broken, causing bugs and customer cases to be filed, resulting in a poor user experience. 
This PR adds support to get the Documentation related links from a Satellite page. It also adds basic code for missing entities/pages in Airgun/
See SAT-27552
=> Add support for getting documentation related urls from Satellite page

airgun/entities/about.py, airgun/entities/fact_value.py, airgun/entities/global_parameter.py, airgun/session.py, airgun/views/about.py, airgun/views/common.py, airgun/views/global_parameter.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1611
Historically, after a Satellite release, we have found that the documentation links on Satellite pages were broken, causing bugs and customer cases to be filed, resulting in a poor user experience. 
This PR adds support to get the Documentation related links from a Satellite page. It also adds basic code for missing entities/pages in Airgun/
See SAT-27552
=> [6.16.z] Add support for getting documentation related urls from Satellite page

airgun/entities/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1612
Occasionally see no such element exception for ErrataManagement CI results, 
in `get_packages()` method on `view.content.packages.select()`
locally it runs without issue, but we should wait for the packages tab to appear before selecting it, after we navigate to the page.
See for prt [Robottelo#16814](https://github.com/SatelliteQE/robottelo/pull/16814)
two tests using this method, New Host UI > Installed Packages tab > read table :
- tests/foreman/ui/test_errata.py:: test_positive_apply_for_all_hosts (upgrade)
- tests/foreman/ui/test_host.py:: test_positive_update_delete_package (rhel8 only) _Fails in setup_
```
Error Message
selenium.common.exceptions.NoSuchElementException: Message: Could not find an element …
```
=> [6.16.z] Fix inconsistently failing Errata UI, checking New Host > Installed Packages > table

airgun/entities/ansible_role.py, airgun/views/ansible_role.py
Added the `read_all` method to read all Ansible roles before importing.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/16873
=> add read ansible role entities and views

airgun/views/acs.py
Capsule went upper case in ACS create modal in 6.17:
This PR updates the locator accordingly.
=> Fix locator for ACSes

airgun/entities/ansible_role.py, airgun/views/ansible_role.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1620
Added the `read_all` method to read all Ansible roles before importing.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/16873
=> [6.16.z] add read ansible role entities and views

airgun/entities/ansible_role.py, airgun/views/ansible_role.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1620
Added the `read_all` method to read all Ansible roles before importing.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/16873
=> [6.15.z] add read ansible role entities and views

airgun/entities/redhat_repository.py
Couple of tests for RH repos pages are failing with `NoSuchElementException` and it looks like they don't wait for the page display. This should fix it.
=> Add a couple of waits to RH repos pages

airgun/entities/redhat_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1631
Couple of tests for RH repos pages are failing with `NoSuchElementException` and it looks like they don't wait for the page display. This should fix it.
=> [6.14.z] Add a couple of waits to RH repos pages

airgun/entities/redhat_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1631
Couple of tests for RH repos pages are failing with `NoSuchElementException` and it looks like they don't wait for the page display. This should fix it.
=> [6.16.z] Add a couple of waits to RH repos pages

airgun/entities/redhat_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1631
Couple of tests for RH repos pages are failing with `NoSuchElementException` and it looks like they don't wait for the page display. This should fix it.
=> [6.15.z] Add a couple of waits to RH repos pages

airgun/views/host.py
Re-introducing this fix after being reverted.
This commit unintentionally broke navigation to host details page,
which was caused by another issue in the Sat hosts table
and fixed in https://github.com/SatelliteQE/airgun/pull/1465
Description:
The `HostsView` `Name` table column XPath was missing leading '.' character,
which caused that all host rows that were returned, had the same Name value,
equal to the first table row host Name.
=> hosts table: Name locator fix (again)

airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1603
Re-introducing this fix after being reverted.
This commit unintentionally broke navigation to host details page,
which was caused by another issue in the Sat hosts table
and fixed in https://github.com/SatelliteQE/airgun/pull/1465
Description:
The `HostsView` `Name` table column XPath was missing leading '.' character,
which caused that all host rows that were returned, had the same Name value,
equal to the first table row host Name.
=> [6.16.z] hosts table: Name locator fix (again)

airgun/views/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1603
Re-introducing this fix after being reverted.
This commit unintentionally broke navigation to host details page,
which was caused by another issue in the Sat hosts table
and fixed in https://github.com/SatelliteQE/airgun/pull/1465
Description:
The `HostsView` `Name` table column XPath was missing leading '.' character,
which caused that all host rows that were returned, had the same Name value,
equal to the first table row host Name.
=> [6.15.z] hosts table: Name locator fix (again)

airgun/entities/capsule.py, airgun/views/capsule.py
A new kebab for the content counts update has been added in 6.17 to granularize the counts calculation.
This PR just adds the ability to refresh content counts for particular CV under a LCE.
Tested locally with packit instance for https://github.com/Katello/katello/pull/11187 and some populated capsule and a dummie like this worked 
```
def test_dummie(target_sat, module_capsule_configured):
with target_sat.ui_session() as session:
session.organization.select(org_name='Any organization')
details = session.capsule.read_details(module_capsule_configured.hostname)
session.capsule.refresh_lce_counts(module_capsule_configured.hostname, lce_name='etPJDb')
session.capsule.refresh_lce_counts(
module_capsule_configured.hostname, lce_name='etPJDb', cv_name='AzrxdmTifn'
)
```
=> Add new Refresh button in capsule content

airgun/entities/contentview_new.py, airgun/views/contentview_new.py
small airgun PR to add support for a new test: https://github.com/SatelliteQE/robottelo/pull/15268
=> add support for versions dropdown

airgun/entities/job_invocation.py, airgun/views/job_invocation.py
Add view for leapp preupgrade remidiation.
Robottelo PR: https://github.com/SatelliteQE/robottelo/pull/17180
=> Add leapp preupgrade remidiation view

.github/workflows/pull_request.yml
=> Cross check Airgun installation with robottelo's dependencies

.github/workflows/pull_request.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1676
=> [6.16.z] Cross check Airgun installation with robottelo's dependencies

.github/workflows/pull_request.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1676
=> [6.15.z] Cross check Airgun installation with robottelo's dependencies

.github/workflows/pull_request.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1676
=> [6.14.z] Cross check Airgun installation with robottelo's dependencies

.github/workflows/pull_request.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1676
=> [6.13.z] Cross check Airgun installation with robottelo's dependencies

airgun/entities/package.py, airgun/views/package.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1593
CC Automation SAT-26967
Related robottelo PR - https://github.com/SatelliteQE/robottelo/pull/16641
=> [6.16.z] add airgun support for parsing package details page link

airgun/entities/host_new.py, airgun/views/host_new.py
Added to the entities with their respective locators:
- `update_variable_value`: Updating the ansible variable value in the host.
- `del_variable_value`: Deletes the updated value, reverts to the default value.
- `read_variable_value`: Read the value of ansible variable in the host.
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/16969
=> removing updated value and takes default value

airgun/widgets.py
After a thorough debugging session. It was discovered that when a user selects a new LCE, the "edit" button disappears and then requires and additional "fill" and "save" action. This is the case for PF4 as well. 
This was introduced by a logic change here: https://github.com/SatelliteQE/airgun/pull/939
If you think this looks gross... IT IS. But  I want to clarify that we cannot add any additional parameters/arguments to the fill method and we have nothing to really iterate over. So if you have any suggestions on how to make this look pretty im all ears :)
=> Update fill method logic for button values

.github/workflows/pull_request.yml
=> Switch Airgun CI/CQ to uv

.github/workflows/pull_request.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1685
=> [6.13.z] Switch Airgun CI/CQ to uv

.github/workflows/pull_request.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1685
=> [6.15.z] Switch Airgun CI/CQ to uv

.github/workflows/pull_request.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1685
=> [6.14.z] Switch Airgun CI/CQ to uv

.github/workflows/pull_request.yml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1685
=> [6.16.z] Switch Airgun CI/CQ to uv

airgun/views/subscription.py
- Test case `test_positive_access_with_non_admin_user_with_manifest` was failing due to Error 
`TypeError: 'NoneType' object is not subscriptable`
- Class variable `search_field` from airgun view `SubscriptionSearch` need to be updated
Update `search_field` with expected locator.
https://github.com/SatelliteQE/robottelo/pull/17382
=> subscription page search field ui selector update

airgun/entities/hostgroup.py
When we read the value of a host group set within a specific organization, and then attempt to change to a different organization without clicking the "Submit" button, an alert is triggered. This alert is handled by the `WrongContextAlert` class, but its button locator needs to be updated. The locator is part of the `widgetastic_patternfly4` library, which is supported only up to `Python 3.10`.
To avoid this issue, after reading the value in the host group, the "Submit" button will be clicked and change the organization.
=> updated read func which will read the value and click on submit.

airgun/entities/sync_status.py, airgun/views/sync_status.py
There is the "Active only" check-box on the sync status page which adjusts the product/repos table to hide the lines where no sync happens. This is done through the `tr`'s `style` set to `display: none`, which means the table remains still complete, only the style change hides what needs to be hidden.
Unfortunately Airgun does not care about styles and returns the complete table since it's still there in the page.
This PR changes this behaviour to let Airgun return the table just like the user can see it based on the style (via `is_displayed` property).
Second change allows user to set the Active only check-box before read.
Third and last change allows user to sync a repo asynchronously without waiting for result.
Test PR: https://github.com/SatelliteQE/robottelo/pull/17413
=> Extend sync_status page with active_only support

airgun/entities/hostgroup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1701
When we read the value of a host group set within a specific organization, and then attempt to change to a different organization without clicking the "Submit" button, an alert is triggered. This alert is handled by the `WrongContextAlert` class, but its button locator needs to be updated. The locator is part of the `widgetastic_patternfly4` library, which is supported only up to `Python 3.10`.
To avoid this issue, after reading the value in the host group, the "Submit" button will be clicked and change the organization.
=> [6.16.z] updated read func which will read the value and click on submit.

airgun/entities/hostgroup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1701
When we read the value of a host group set within a specific organization, and then attempt to change to a different organization without clicking the "Submit" button, an alert is triggered. This alert is handled by the `WrongContextAlert` class, but its button locator needs to be updated. The locator is part of the `widgetastic_patternfly4` library, which is supported only up to `Python 3.10`.
To avoid this issue, after reading the value in the host group, the "Submit" button will be clicked and change the organization.
=> [6.14.z] updated read func which will read the value and click on submit.

airgun/entities/sync_status.py, airgun/views/sync_status.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1708
There is the "Active only" check-box on the sync status page which adjusts the product/repos table to hide the lines where no sync happens. This is done through the `tr`'s `style` set to `display: none`, which means the table remains still complete, only the style change hides what needs to be hidden.
Unfortunately Airgun does not care about styles and returns the complete table since it's still there in the page.
This PR changes this behaviour to let Airgun return the table just like the user can see it based on the style (via `is_displayed` property).
Second change allows user to set the Active only check-box before read.
Third and last change allows user to sync a repo asynchronously without waiting for result.
Test PR: …
=> [6.16.z] Extend sync_status page with active_only support

.github/workflows/pull_request.yml, setup.py
Python 3.13 was released on October 7, 2024, and we're not covering this in the PR checks in GHA yet
Add Python 3.13 for PR checks in GHA
=> Add Python 3.13 for PR checks in GHA

airgun/entities/cloud_insights.py, airgun/entities/cloud_inventory.py
Reflect the UI changes in https://github.com/theforeman/foreman_rh_cloud/pull/945:
Configure > Insights is now a top-level Insights item:
Configure > Insights > Inventory Upload is now Insights > Inventory Upload
Configure > Insights > Recommendations is now Insights > Recommendations
=> Move "Insights" navigation menu items from under "Configure"

airgun/views/subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1702
- Test case `test_positive_access_with_non_admin_user_with_manifest` was failing due to Error 
`TypeError: 'NoneType' object is not subscriptable`
- Class variable `search_field` from airgun view `SubscriptionSearch` need to be updated
Update `search_field` with expected locator.
https://github.com/SatelliteQE/robottelo/pull/17382
=> [6.16.z] subscription page search field ui selector update

.github/workflows/pull_request.yml, setup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1703
Python 3.13 was released on October 7, 2024, and we're not covering this in the PR checks in GHA yet
Add Python 3.13 for PR checks in GHA
=> [6.15.z] Add Python 3.13 for PR checks in GHA

.github/workflows/pull_request.yml, setup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1703
Python 3.13 was released on October 7, 2024, and we're not covering this in the PR checks in GHA yet
Add Python 3.13 for PR checks in GHA
=> [6.16.z] Add Python 3.13 for PR checks in GHA

airgun/entities/http_proxy.py, airgun/views/http_proxy.py
Change introduced in https://github.com/Katello/katello/pull/11183 and https://github.com/Katello/katello/pull/11266
=> Add locator for content_default_http_proxy checkbox on HTTP proxy create page

airgun/views/job_invocation.py, airgun/widgets.py
Added few more widgets for the new job invocations page.
This patch adds the expandable sections `Target Hosts` and `User Inputs`.
The expandable host table below currently doesn't seem to work with the widgetastic
table widgets, nor PF4, PF4/OUIA, etc., even with modifications.
After this issue is addressed and solved, the table widget will be added in a separate PR.
=> RFE: added widgets for the new job invocation page

airgun/entities/activationkey.py, airgun/views/activationkey.py
This PR adds an entity that enables modification of the AK host limit and adds some missing view elements.
Dependant PR https://github.com/SatelliteQE/robottelo/pull/17631
=> Add AK update host limit entity

.github/dependabot.yml
New 6.17.z downstream and master points to stream that is 6.18
- Dependabot.yaml cherrypicks to 6.17.z
=> [master]: Changes for 6.17.z new branch

airgun/entities/bootc.py, airgun/session.py, airgun/views/bootc.py
Quick little airgun PR adding support for the booted container image page.
Supports: https://github.com/SatelliteQE/robottelo/pull/17634
=> Add view/entity for booted container images page

airgun/views/capsule.py, airgun/views/computeresource.py, airgun/views/host.py, airgun/views/hostgroup.py, airgun/views/oscappolicy.py, airgun/views/partitiontable.py, airgun/views/report_template.py, airgun/views/usergroup.py, airgun/widgets.py
Some locators have changed after the jQuery3 update, so update the locators accordingly to ensure the test functions correctly.
=> remove s2id from the locator

airgun/views/os.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1755
Update the locator to retrieve the value from the operating system template.
=> [6.17.z] fix TemplatesList locator to fetch value

airgun/entities/bootc.py, airgun/session.py, airgun/views/bootc.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1745
Quick little airgun PR adding support for the booted container image page.
Supports: https://github.com/SatelliteQE/robottelo/pull/17634
=> [6.17.z] Add view/entity for booted container images page

.github/workflows/pull_request.yml, setup.py
We can not update the Sphinx library without dropping Python 3.10 - SatelliteQE/robottelo#17638.
Drop Python 3.10 suport.
SatelliteQE/robottelo#17638
SatelliteQE/robottelo#17666
SatelliteQE/robottelo#17557
=> Remove Python 3.10 support

.github/workflows/pull_request.yml, setup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1758
We can not update the Sphinx library without dropping Python 3.10 - SatelliteQE/robottelo#17638.
Drop Python 3.10 suport.
SatelliteQE/robottelo#17638
SatelliteQE/robottelo#17666
SatelliteQE/robottelo#17557
=> [6.17.z] Remove Python 3.10 support

.github/workflows/pull_request.yml, setup.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1758
We can not update the Sphinx library without dropping Python 3.10 - SatelliteQE/robottelo#17638.
Drop Python 3.10 suport.
SatelliteQE/robottelo#17638
SatelliteQE/robottelo#17666
SatelliteQE/robottelo#17557
=> [6.15.z] Remove Python 3.10 support

airgun/entities/bootc.py
SAT-31160 is fixed as of 6.17 - snap 3, so the workaround needs to be removed.
=> JIRA issues is fixed, removing workaround

airgun/entities/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1776
After host creation, the page load takes time. Therefore, increasing the page load time and the wait time for puppet_sat.
=> [6.17.z] Fixing the timing to ensure smooth host creation.

airgun/entities/host.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1776
After host creation, the page load takes time. Therefore, increasing the page load time and the wait time for puppet_sat.
=> [6.16.z] Fixing the timing to ensure smooth host creation.

airgun/views/host_new.py
Fix for this locator landed in 6.17, need to get this merged in quickly, so we can see accurate UI test results.
=> Update host details bootc card to use proper locator

airgun/views/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1785
Fix for this locator landed in 6.17, need to get this merged in quickly, so we can see accurate UI test results.
=> [6.17.z] Update host details bootc card to use proper locator

airgun/entities/http_proxy.py, airgun/views/http_proxy.py
Just a small addition to the HTTP proxy view and entity.
Robottelo test PR follows: https://github.com/SatelliteQE/robottelo/pull/18128
=> Extend http proxy with Test Connection button

airgun/entities/http_proxy.py, airgun/views/http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1787
Just a small addition to the HTTP proxy view and entity.
Robottelo test PR follows: https://github.com/SatelliteQE/robottelo/pull/18128
=> [6.17.z] Extend http proxy with Test Connection button

airgun/entities/all_hosts.py, airgun/widgets.py
This PR updates `SatFlashMessages` so it corresponds to its PF5 definition.
Also, this PR fixes one `manage_errata` entity, which unblocks the test from another failure that is caused by already filed BZ.
=> Alert Fix PF4 to PF5

airgun/entities/product.py, airgun/views/product.py, airgun/views/repository.py
In 6.17 the HTTP proxy was generally lower-cased, which makes related UI tests to fail.
This PR updates the related views.
=> Lowercase HTTP proxy

airgun/entities/product.py, airgun/views/product.py, airgun/views/repository.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1797
In 6.17 the HTTP proxy was generally lower-cased, which makes related UI tests to fail.
This PR updates the related views.
=> [6.17.z] Lowercase HTTP proxy

airgun/entities/job_invocation.py
=> wait_to_success_job_task

airgun/entities/job_invocation.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1801
=> [6.17.z] wait_to_success_job_task

airgun/entities/job_invocation.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1801
=> [6.16.z] wait_to_success_job_task

airgun/entities/job_invocation.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1801
=> [6.15.z] wait_to_success_job_task

airgun/entities/job_invocation.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1801
=> [6.14.z] wait_to_success_job_task

airgun/views/all_hosts.py, airgun/views/host_new.py
This PR fixes managing all hosts table columns.
Fixes `test_all_hosts_manage_columns`
PRT Example
```
pytest: tests/foreman/ui/test_host.py -k 'test_all_hosts_manage_columns'
```
=> Fix ManageColumns View PF4->PF5

airgun/browser.py, airgun/widgets.py
Airgun needs to recognize the deletion confirmation modal in PF5, affects a bunch of tests that delete stuff in the UI
=> confirm modal for PF5

airgun/entities/hostgroup.py, airgun/views/hostgroup.py
*** hostgroups: PF5 update & navigation improvements
Requires https://github.com/SatelliteQE/airgun/pull/1812
PatternFly5 updates for the host groups pages.
Additional changes:
- several `view.wait_displayed()` added for more reliable page loading
- Host Groups page now also expects if no host groups are present
- `hostgroup.read()` no longer submits the form
- it can cause to submit unintentional data (not likely, but still)
- it prolongs the test time as new page needs to load
- the navigation can clash with actions chains like `read() && update(...)`
where `read()` submitted the form while `update()` expects to interact with the page immediately
*** PRT Example
```
pytest: tests/foreman/ui/test_hostgroup.py -k test_positive_end_to_end
airgun: 1812
```
=> hostgroups: PF5 update & navigation improvements

.pre-commit-config.yaml
Manual cherry-pick of pre-commit upgrade to 6.17.z.
Fixes https://github.com/SatelliteQE/airgun/issues/1809
=> [6.17.z] pre-commit upgrade

.pre-commit-config.yaml
Manual cherry-pick of pre-commit upgrade to 6.14.z.
Fixes https://github.com/SatelliteQE/airgun/issues/1808
=> [6.14.z] pre-commit upgrade

.pre-commit-config.yaml
Manual cherry-pick of pre-commit upgrade to 6.15.z.
Fixes https://github.com/SatelliteQE/airgun/issues/1807
=> [6.15.z] pre-commit upgrade

.pre-commit-config.yaml
Manual cherry-pick of pre-commit upgrade to 6.16.z.
Fixes https://github.com/SatelliteQE/airgun/issues/1810
=> [6.16.z] pre-commit upgrade

airgun/entities/capsule.py, airgun/views/capsule.py
This PR proposes a PF5 update for the Capsule view, mainly for the Content tab - the current state does not read the content page at all, this PR should fix it.
~The only thing I was not able to get working in PF5 is the refresh `Dropdown` click-ability. A call like `session.capsule.refresh_lce_counts(module_capsule_configured.hostname, lce_name='Library')` should expand the kebab and click on `Refresh counts`. Any help here is appreciated.~
=> Update Capsule with PF5

airgun/views/subscription.py
This PR fixes `test_positive_check_manifest_validity_notification`.
The update of alert view was needed.
```
pytest: tests/foreman/ui/test_subscription.py -k 'test_positive_check_manifest_validity_notification'
```
=> Fix Manifest Alert View PF4->PF5

airgun/entities/all_hosts.py, airgun/views/all_hosts.py, airgun/views/common.py, airgun/views/contentview_new.py, airgun/widgets.py
This PR fixes `test_all_hosts_bulk_cve_reassign` test by updating related views and some entities to PF5
```
pytest: tests/foreman/ui/test_host.py -k 'test_all_hosts_bulk_cve_reassign'
```
=> fix CVE Reassign PF4->PF5

.pre-commit-config.yaml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1836
updates:
- [github.com/astral-sh/ruff-pre-commit: v0.11.7 → v0.11.9](https://github.com/astral-sh/ruff-pre-commit/compare/v0.11.7...v0.11.9)
=> [6.17.z] [pre-commit.ci] pre-commit autoupdate

airgun/entities/contentview_new.py
Updates publish entity to support multi environment promote.
Supports: https://github.com/SatelliteQE/robottelo/pull/17949
=> Add multi promote support to publish/promote entity

airgun/views/all_hosts.py
This PR adds the implementation of `MenuToggleDropdownInTable`.
It represents the kebab dropdown within the AllHost page table rows.
Upon this implementation we should come up with some global implementation of some view that would cover all the PF5(MenuToggle->Dropdown) menu views across the Satellite.
This PR also fixes `all_hosts_delete`.
```
pytest: tests/foreman/ui/test_host.py -k 'all_hosts_delete'
```
=> [PF5] MenuToggleDropdownInTable

airgun/entities/flatpak.py, airgun/session.py, airgun/views/flatpak.py
In 6.18.0 we are adding UI support for Flatpak. Initial is the Content > Flatpak Remotes page, which this PR aims to cover.
As of now, the Scan, Edit and Delete actions are not implemented yet in Katello, but they are to be added soon.
Robottelo companion PR: https://github.com/SatelliteQE/robottelo/pull/18419
=> Add view and entities for Flatpak Remotes

airgun/views/host_new.py
Failed auto-cherrypick: https://github.com/SatelliteQE/airgun/issues/1913
=> [6.15.z Cherrypick] Fix class name typo (#1911)

airgun/entities/contentview_new.py, airgun/views/common.py, airgun/views/contentview_new.py
There were few minor fixes needed for new contentview view and entities.
- Contentview Views:
1. version_dropdown = Dropdown(
locator='.//div[@data-ouia-component-id="cv-version-header-actions-dropdown"]'
)
locator was mentioned twice in views which could be confusing.
2. Fixed lce_selector locator.
- Contentview Entities:
1. Renamed `version_name` variable to `version` to maintain consistency in the module.
2.  def promote does not handle errors in case incorrect lce or invalid promote happens, added a check for handing and reading the error message. 
3. There is no lce variable in views so updated it to lce_selector.
4. Updated class PromoteContentViewVersion in views
=> Fix ContentView view

airgun/views/hardware_model.py, airgun/views/host_new.py
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/2040
Fixed NewHostDetailsView -> overview to read details correctly 
- Locators were changed for All Host -> Host details ->Overview
- Also added PF5OUIATable support for hardware_model
=> [6.18.z] Fixed NewHostDetailsView -> overview to read details correctly

airgun/views/host_new.py
Fix host status locator  which was broken due to earlier changes
verified by running earlier as well as broken test cases
=> Fix host status locator  which was broken due to earlier changes

airgun/entities/redhat_repository.py, airgun/views/redhat_repository.py
**Problem Statement**
No support presented for `recommended kickstart repositories` in airgun entities & in views.
**Solution**
Update `RedHatRepositoryEntity` read method and `RedHatRepositoriesView` with required changes.
**Related robottelo PR**
https://github.com/SatelliteQE/robottelo/pull/19676
=> read recommended repositories by it types

airgun/entities/contenthost.py
Make job invocation view more stable  by adding view.wait_displayed as PRT was failng for robotello PR https://github.com/SatelliteQE/robottelo/pull/19747
=> [6.17.z] Make job invocation view more stable as PRT was failng

.github/workflows/pull_request.yml
=> [6.16.z] Bump actions/setup-python from 5 to 6

.pre-commit-config.yaml
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/2105
updates:
- [github.com/astral-sh/ruff-pre-commit: v0.13.1 → v0.13.2](https://github.com/astral-sh/ruff-pre-commit/compare/v0.13.1...v0.13.2)
=> [6.18.z] [pre-commit.ci] pre-commit autoupdate

airgun/views/host_new.py
PF4 to PF5 conversion of dialog windows.
Fixes `test_positive_crud_module_streams`.
Needed by https://github.com/SatelliteQE/robottelo/pull/19803 PRT passed here
=> PF4 to PF5 conversion of dialog windows
